/// <reference path="../../utils/assert.ts" />
/// <reference path="../../utils/c.ts" />
/// <reference path="../../utils/todo.ts" />
/// <reference path="../../utils/types.ts" />

/// <reference path="../../eduke32/headers/namesdyn.h.ts" />

//-------------------------------------------------------------------------
/*
Copyright (C) 2010 EDuke32 developers and contributors

This file is part of EDuke32.

EDuke32 is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 2
as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/
//-------------------------------------------------------------------------

//#include "compat.h"
//#include "build.h"

//#include "namesdyn.h"
//#include "global.h"

//#ifdef DYNTILEREMAP_ENABLE
//# define DVPTR(x) &x
//#else
//# define DVPTR(x) NULL
//#endif
function DVPTR(v: number): number {
    // todo: remove later
    return v;
}


//int16_t DynamicTileMap[MAXTILES];

function dynitem(str: string, dynvalptr: number, staticval: number)
{
    this.str = str;
    this.dynvalptr = dynvalptr;
    this.staticval = staticval;
};

var g_dynTileList =
[
new dynitem( "SECTOREFFECTOR", DVPTR(SECTOREFFECTOR), SECTOREFFECTOR__STATIC ),
new dynitem( "ACTIVATOR", DVPTR(ACTIVATOR), ACTIVATOR__STATIC ),
new dynitem( "TOUCHPLATE", DVPTR(TOUCHPLATE), TOUCHPLATE__STATIC ),
new dynitem( "ACTIVATORLOCKED", DVPTR(ACTIVATORLOCKED), ACTIVATORLOCKED__STATIC ),
new dynitem( "MUSICANDSFX", DVPTR(MUSICANDSFX), MUSICANDSFX__STATIC ),
new dynitem( "LOCATORS", DVPTR(LOCATORS), LOCATORS__STATIC ),
new dynitem( "CYCLER", DVPTR(CYCLER), CYCLER__STATIC ),
new dynitem( "MASTERSWITCH", DVPTR(MASTERSWITCH), MASTERSWITCH__STATIC ),
new dynitem( "RESPAWN", DVPTR(RESPAWN), RESPAWN__STATIC ),
new dynitem( "GPSPEED", DVPTR(GPSPEED), GPSPEED__STATIC ),
new dynitem( "FOF", DVPTR(FOF), FOF__STATIC ),
new dynitem( "ARROW", DVPTR(ARROW), ARROW__STATIC ),
new dynitem( "FIRSTGUNSPRITE", DVPTR(FIRSTGUNSPRITE), FIRSTGUNSPRITE__STATIC ),
new dynitem( "CHAINGUNSPRITE", DVPTR(CHAINGUNSPRITE), CHAINGUNSPRITE__STATIC ),
new dynitem( "RPGSPRITE", DVPTR(RPGSPRITE), RPGSPRITE__STATIC ),
new dynitem( "FREEZESPRITE", DVPTR(FREEZESPRITE), FREEZESPRITE__STATIC ),
new dynitem( "SHRINKERSPRITE", DVPTR(SHRINKERSPRITE), SHRINKERSPRITE__STATIC ),
new dynitem( "HEAVYHBOMB", DVPTR(HEAVYHBOMB), HEAVYHBOMB__STATIC ),
new dynitem( "TRIPBOMBSPRITE", DVPTR(TRIPBOMBSPRITE), TRIPBOMBSPRITE__STATIC ),
new dynitem( "SHOTGUNSPRITE", DVPTR(SHOTGUNSPRITE), SHOTGUNSPRITE__STATIC ),
new dynitem( "DEVISTATORSPRITE", DVPTR(DEVISTATORSPRITE), DEVISTATORSPRITE__STATIC ),
new dynitem( "HEALTHBOX", DVPTR(HEALTHBOX), HEALTHBOX__STATIC ),
new dynitem( "AMMOBOX", DVPTR(AMMOBOX), AMMOBOX__STATIC ),
new dynitem( "GROWSPRITEICON", DVPTR(GROWSPRITEICON), GROWSPRITEICON__STATIC ),
new dynitem( "INVENTORYBOX", DVPTR(INVENTORYBOX), INVENTORYBOX__STATIC ),
new dynitem( "FREEZEAMMO", DVPTR(FREEZEAMMO), FREEZEAMMO__STATIC ),
new dynitem( "AMMO", DVPTR(AMMO), AMMO__STATIC ),
new dynitem( "BATTERYAMMO", DVPTR(BATTERYAMMO), BATTERYAMMO__STATIC ),
new dynitem( "DEVISTATORAMMO", DVPTR(DEVISTATORAMMO), DEVISTATORAMMO__STATIC ),
new dynitem( "RPGAMMO", DVPTR(RPGAMMO), RPGAMMO__STATIC ),
new dynitem( "GROWAMMO", DVPTR(GROWAMMO), GROWAMMO__STATIC ),
new dynitem( "CRYSTALAMMO", DVPTR(CRYSTALAMMO), CRYSTALAMMO__STATIC ),
new dynitem( "HBOMBAMMO", DVPTR(HBOMBAMMO), HBOMBAMMO__STATIC ),
new dynitem( "AMMOLOTS", DVPTR(AMMOLOTS), AMMOLOTS__STATIC ),
new dynitem( "SHOTGUNAMMO", DVPTR(SHOTGUNAMMO), SHOTGUNAMMO__STATIC ),
new dynitem( "COLA", DVPTR(COLA), COLA__STATIC ),
new dynitem( "SIXPAK", DVPTR(SIXPAK), SIXPAK__STATIC ),
new dynitem( "FIRSTAID", DVPTR(FIRSTAID), FIRSTAID__STATIC ),
new dynitem( "SHIELD", DVPTR(SHIELD), SHIELD__STATIC ),
new dynitem( "STEROIDS", DVPTR(STEROIDS), STEROIDS__STATIC ),
new dynitem( "AIRTANK", DVPTR(AIRTANK), AIRTANK__STATIC ),
new dynitem( "JETPACK", DVPTR(JETPACK), JETPACK__STATIC ),
new dynitem( "HEATSENSOR", DVPTR(HEATSENSOR), HEATSENSOR__STATIC ),
new dynitem( "ACCESSCARD", DVPTR(ACCESSCARD), ACCESSCARD__STATIC ),
new dynitem( "BOOTS", DVPTR(BOOTS), BOOTS__STATIC ),
new dynitem( "MIRRORBROKE", DVPTR(MIRRORBROKE), MIRRORBROKE__STATIC ),
new dynitem( "CLOUDYOCEAN", DVPTR(CLOUDYOCEAN), CLOUDYOCEAN__STATIC ),
new dynitem( "CLOUDYSKIES", DVPTR(CLOUDYSKIES), CLOUDYSKIES__STATIC ),
new dynitem( "MOONSKY1", DVPTR(MOONSKY1), MOONSKY1__STATIC ),
new dynitem( "MOONSKY2", DVPTR(MOONSKY2), MOONSKY2__STATIC ),
new dynitem( "MOONSKY3", DVPTR(MOONSKY3), MOONSKY3__STATIC ),
new dynitem( "MOONSKY4", DVPTR(MOONSKY4), MOONSKY4__STATIC ),
new dynitem( "BIGORBIT1", DVPTR(BIGORBIT1), BIGORBIT1__STATIC ),
new dynitem( "BIGORBIT2", DVPTR(BIGORBIT2), BIGORBIT2__STATIC ),
new dynitem( "BIGORBIT3", DVPTR(BIGORBIT3), BIGORBIT3__STATIC ),
new dynitem( "BIGORBIT4", DVPTR(BIGORBIT4), BIGORBIT4__STATIC ),
new dynitem( "BIGORBIT5", DVPTR(BIGORBIT5), BIGORBIT5__STATIC ),
new dynitem( "LA", DVPTR(LA), LA__STATIC ),
new dynitem( "REDSKY1", DVPTR(REDSKY1), REDSKY1__STATIC ),
new dynitem( "REDSKY2", DVPTR(REDSKY2), REDSKY2__STATIC ),
new dynitem( "ATOMICHEALTH", DVPTR(ATOMICHEALTH), ATOMICHEALTH__STATIC ),
new dynitem( "TECHLIGHT2", DVPTR(TECHLIGHT2), TECHLIGHT2__STATIC ),
new dynitem( "TECHLIGHTBUST2", DVPTR(TECHLIGHTBUST2), TECHLIGHTBUST2__STATIC ),
new dynitem( "TECHLIGHT4", DVPTR(TECHLIGHT4), TECHLIGHT4__STATIC ),
new dynitem( "TECHLIGHTBUST4", DVPTR(TECHLIGHTBUST4), TECHLIGHTBUST4__STATIC ),
new dynitem( "WALLLIGHT4", DVPTR(WALLLIGHT4), WALLLIGHT4__STATIC ),
new dynitem( "WALLLIGHTBUST4", DVPTR(WALLLIGHTBUST4), WALLLIGHTBUST4__STATIC ),
new dynitem( "ACCESSSWITCH", DVPTR(ACCESSSWITCH), ACCESSSWITCH__STATIC ),
new dynitem( "SLOTDOOR", DVPTR(SLOTDOOR), SLOTDOOR__STATIC ),
new dynitem( "LIGHTSWITCH", DVPTR(LIGHTSWITCH), LIGHTSWITCH__STATIC ),
new dynitem( "SPACEDOORSWITCH", DVPTR(SPACEDOORSWITCH), SPACEDOORSWITCH__STATIC ),
new dynitem( "SPACELIGHTSWITCH", DVPTR(SPACELIGHTSWITCH), SPACELIGHTSWITCH__STATIC ),
new dynitem( "FRANKENSTINESWITCH", DVPTR(FRANKENSTINESWITCH), FRANKENSTINESWITCH__STATIC ),
new dynitem( "NUKEBUTTON", DVPTR(NUKEBUTTON), NUKEBUTTON__STATIC ),
new dynitem( "MULTISWITCH", DVPTR(MULTISWITCH), MULTISWITCH__STATIC ),
new dynitem( "DOORTILE5", DVPTR(DOORTILE5), DOORTILE5__STATIC ),
new dynitem( "DOORTILE6", DVPTR(DOORTILE6), DOORTILE6__STATIC ),
new dynitem( "DOORTILE1", DVPTR(DOORTILE1), DOORTILE1__STATIC ),
new dynitem( "DOORTILE2", DVPTR(DOORTILE2), DOORTILE2__STATIC ),
new dynitem( "DOORTILE3", DVPTR(DOORTILE3), DOORTILE3__STATIC ),
new dynitem( "DOORTILE4", DVPTR(DOORTILE4), DOORTILE4__STATIC ),
new dynitem( "DOORTILE7", DVPTR(DOORTILE7), DOORTILE7__STATIC ),
new dynitem( "DOORTILE8", DVPTR(DOORTILE8), DOORTILE8__STATIC ),
new dynitem( "DOORTILE9", DVPTR(DOORTILE9), DOORTILE9__STATIC ),
new dynitem( "DOORTILE10", DVPTR(DOORTILE10), DOORTILE10__STATIC ),
new dynitem( "DOORSHOCK", DVPTR(DOORSHOCK), DOORSHOCK__STATIC ),
new dynitem( "DIPSWITCH", DVPTR(DIPSWITCH), DIPSWITCH__STATIC ),
new dynitem( "DIPSWITCH2", DVPTR(DIPSWITCH2), DIPSWITCH2__STATIC ),
new dynitem( "TECHSWITCH", DVPTR(TECHSWITCH), TECHSWITCH__STATIC ),
new dynitem( "DIPSWITCH3", DVPTR(DIPSWITCH3), DIPSWITCH3__STATIC ),
new dynitem( "ACCESSSWITCH2", DVPTR(ACCESSSWITCH2), ACCESSSWITCH2__STATIC ),
new dynitem( "REFLECTWATERTILE", DVPTR(REFLECTWATERTILE), REFLECTWATERTILE__STATIC ),
new dynitem( "FLOORSLIME", DVPTR(FLOORSLIME), FLOORSLIME__STATIC ),
new dynitem( "BIGFORCE", DVPTR(BIGFORCE), BIGFORCE__STATIC ),
new dynitem( "EPISODE", DVPTR(EPISODE), EPISODE__STATIC ),
new dynitem( "MASKWALL9", DVPTR(MASKWALL9), MASKWALL9__STATIC ),
new dynitem( "W_LIGHT", DVPTR(W_LIGHT), W_LIGHT__STATIC ),
new dynitem( "SCREENBREAK1", DVPTR(SCREENBREAK1), SCREENBREAK1__STATIC ),
new dynitem( "SCREENBREAK2", DVPTR(SCREENBREAK2), SCREENBREAK2__STATIC ),
new dynitem( "SCREENBREAK3", DVPTR(SCREENBREAK3), SCREENBREAK3__STATIC ),
new dynitem( "SCREENBREAK4", DVPTR(SCREENBREAK4), SCREENBREAK4__STATIC ),
new dynitem( "SCREENBREAK5", DVPTR(SCREENBREAK5), SCREENBREAK5__STATIC ),
new dynitem( "SCREENBREAK6", DVPTR(SCREENBREAK6), SCREENBREAK6__STATIC ),
new dynitem( "SCREENBREAK7", DVPTR(SCREENBREAK7), SCREENBREAK7__STATIC ),
new dynitem( "SCREENBREAK8", DVPTR(SCREENBREAK8), SCREENBREAK8__STATIC ),
new dynitem( "SCREENBREAK9", DVPTR(SCREENBREAK9), SCREENBREAK9__STATIC ),
new dynitem( "SCREENBREAK10", DVPTR(SCREENBREAK10), SCREENBREAK10__STATIC ),
new dynitem( "SCREENBREAK11", DVPTR(SCREENBREAK11), SCREENBREAK11__STATIC ),
new dynitem( "SCREENBREAK12", DVPTR(SCREENBREAK12), SCREENBREAK12__STATIC ),
new dynitem( "SCREENBREAK13", DVPTR(SCREENBREAK13), SCREENBREAK13__STATIC ),
new dynitem( "MASKWALL1", DVPTR(MASKWALL1), MASKWALL1__STATIC ),
new dynitem( "W_TECHWALL1", DVPTR(W_TECHWALL1), W_TECHWALL1__STATIC ),
new dynitem( "W_TECHWALL2", DVPTR(W_TECHWALL2), W_TECHWALL2__STATIC ),
new dynitem( "W_TECHWALL15", DVPTR(W_TECHWALL15), W_TECHWALL15__STATIC ),
new dynitem( "W_TECHWALL3", DVPTR(W_TECHWALL3), W_TECHWALL3__STATIC ),
new dynitem( "W_TECHWALL4", DVPTR(W_TECHWALL4), W_TECHWALL4__STATIC ),
new dynitem( "W_TECHWALL10", DVPTR(W_TECHWALL10), W_TECHWALL10__STATIC ),
new dynitem( "W_TECHWALL16", DVPTR(W_TECHWALL16), W_TECHWALL16__STATIC ),
new dynitem( "WATERTILE2", DVPTR(WATERTILE2), WATERTILE2__STATIC ),
new dynitem( "BPANNEL1", DVPTR(BPANNEL1), BPANNEL1__STATIC ),
new dynitem( "PANNEL1", DVPTR(PANNEL1), PANNEL1__STATIC ),
new dynitem( "PANNEL2", DVPTR(PANNEL2), PANNEL2__STATIC ),
new dynitem( "WATERTILE", DVPTR(WATERTILE), WATERTILE__STATIC ),
new dynitem( "STATIC", DVPTR(STATIC), STATIC__STATIC ),
new dynitem( "W_SCREENBREAK", DVPTR(W_SCREENBREAK), W_SCREENBREAK__STATIC ),
new dynitem( "W_HITTECHWALL3", DVPTR(W_HITTECHWALL3), W_HITTECHWALL3__STATIC ),
new dynitem( "W_HITTECHWALL4", DVPTR(W_HITTECHWALL4), W_HITTECHWALL4__STATIC ),
new dynitem( "W_HITTECHWALL2", DVPTR(W_HITTECHWALL2), W_HITTECHWALL2__STATIC ),
new dynitem( "W_HITTECHWALL1", DVPTR(W_HITTECHWALL1), W_HITTECHWALL1__STATIC ),
new dynitem( "MASKWALL10", DVPTR(MASKWALL10), MASKWALL10__STATIC ),
new dynitem( "MASKWALL11", DVPTR(MASKWALL11), MASKWALL11__STATIC ),
new dynitem( "DOORTILE22", DVPTR(DOORTILE22), DOORTILE22__STATIC ),
new dynitem( "FANSPRITE", DVPTR(FANSPRITE), FANSPRITE__STATIC ),
new dynitem( "FANSPRITEBROKE", DVPTR(FANSPRITEBROKE), FANSPRITEBROKE__STATIC ),
new dynitem( "FANSHADOW", DVPTR(FANSHADOW), FANSHADOW__STATIC ),
new dynitem( "FANSHADOWBROKE", DVPTR(FANSHADOWBROKE), FANSHADOWBROKE__STATIC ),
new dynitem( "DOORTILE18", DVPTR(DOORTILE18), DOORTILE18__STATIC ),
new dynitem( "DOORTILE19", DVPTR(DOORTILE19), DOORTILE19__STATIC ),
new dynitem( "DOORTILE20", DVPTR(DOORTILE20), DOORTILE20__STATIC ),
new dynitem( "SATELLITE", DVPTR(SATELLITE), SATELLITE__STATIC ),
new dynitem( "VIEWSCREEN2", DVPTR(VIEWSCREEN2), VIEWSCREEN2__STATIC ),
new dynitem( "VIEWSCREENBROKE", DVPTR(VIEWSCREENBROKE), VIEWSCREENBROKE__STATIC ),
new dynitem( "VIEWSCREEN", DVPTR(VIEWSCREEN), VIEWSCREEN__STATIC ),
new dynitem( "GLASS", DVPTR(GLASS), GLASS__STATIC ),
new dynitem( "GLASS2", DVPTR(GLASS2), GLASS2__STATIC ),
new dynitem( "STAINGLASS1", DVPTR(STAINGLASS1), STAINGLASS1__STATIC ),
new dynitem( "MASKWALL5", DVPTR(MASKWALL5), MASKWALL5__STATIC ),
new dynitem( "SATELITE", DVPTR(SATELITE), SATELITE__STATIC ),
new dynitem( "FUELPOD", DVPTR(FUELPOD), FUELPOD__STATIC ),
new dynitem( "SLIMEPIPE", DVPTR(SLIMEPIPE), SLIMEPIPE__STATIC ),
new dynitem( "CRACK1", DVPTR(CRACK1), CRACK1__STATIC ),
new dynitem( "CRACK2", DVPTR(CRACK2), CRACK2__STATIC ),
new dynitem( "CRACK3", DVPTR(CRACK3), CRACK3__STATIC ),
new dynitem( "CRACK4", DVPTR(CRACK4), CRACK4__STATIC ),
new dynitem( "FOOTPRINTS", DVPTR(FOOTPRINTS), FOOTPRINTS__STATIC ),
new dynitem( "DOMELITE", DVPTR(DOMELITE), DOMELITE__STATIC ),
new dynitem( "CAMERAPOLE", DVPTR(CAMERAPOLE), CAMERAPOLE__STATIC ),
new dynitem( "CHAIR1", DVPTR(CHAIR1), CHAIR1__STATIC ),
new dynitem( "CHAIR2", DVPTR(CHAIR2), CHAIR2__STATIC ),
new dynitem( "BROKENCHAIR", DVPTR(BROKENCHAIR), BROKENCHAIR__STATIC ),
new dynitem( "MIRROR", DVPTR(MIRROR), MIRROR__STATIC ),
new dynitem( "WATERFOUNTAIN", DVPTR(WATERFOUNTAIN), WATERFOUNTAIN__STATIC ),
new dynitem( "WATERFOUNTAINBROKE", DVPTR(WATERFOUNTAINBROKE), WATERFOUNTAINBROKE__STATIC ),
new dynitem( "FEMMAG1", DVPTR(FEMMAG1), FEMMAG1__STATIC ),
new dynitem( "TOILET", DVPTR(TOILET), TOILET__STATIC ),
new dynitem( "STALL", DVPTR(STALL), STALL__STATIC ),
new dynitem( "STALLBROKE", DVPTR(STALLBROKE), STALLBROKE__STATIC ),
new dynitem( "FEMMAG2", DVPTR(FEMMAG2), FEMMAG2__STATIC ),
new dynitem( "REACTOR2", DVPTR(REACTOR2), REACTOR2__STATIC ),
new dynitem( "REACTOR2BURNT", DVPTR(REACTOR2BURNT), REACTOR2BURNT__STATIC ),
new dynitem( "REACTOR2SPARK", DVPTR(REACTOR2SPARK), REACTOR2SPARK__STATIC ),
new dynitem( "GRATE1", DVPTR(GRATE1), GRATE1__STATIC ),
new dynitem( "BGRATE1", DVPTR(BGRATE1), BGRATE1__STATIC ),
new dynitem( "SOLARPANNEL", DVPTR(SOLARPANNEL), SOLARPANNEL__STATIC ),
new dynitem( "NAKED1", DVPTR(NAKED1), NAKED1__STATIC ),
new dynitem( "ANTENNA", DVPTR(ANTENNA), ANTENNA__STATIC ),
new dynitem( "MASKWALL12", DVPTR(MASKWALL12), MASKWALL12__STATIC ),
new dynitem( "TOILETBROKE", DVPTR(TOILETBROKE), TOILETBROKE__STATIC ),
new dynitem( "PIPE2", DVPTR(PIPE2), PIPE2__STATIC ),
new dynitem( "PIPE1B", DVPTR(PIPE1B), PIPE1B__STATIC ),
new dynitem( "PIPE3", DVPTR(PIPE3), PIPE3__STATIC ),
new dynitem( "PIPE1", DVPTR(PIPE1), PIPE1__STATIC ),
new dynitem( "CAMERA1", DVPTR(CAMERA1), CAMERA1__STATIC ),
new dynitem( "BRICK", DVPTR(BRICK), BRICK__STATIC ),
new dynitem( "SPLINTERWOOD", DVPTR(SPLINTERWOOD), SPLINTERWOOD__STATIC ),
new dynitem( "PIPE2B", DVPTR(PIPE2B), PIPE2B__STATIC ),
new dynitem( "BOLT1", DVPTR(BOLT1), BOLT1__STATIC ),
new dynitem( "W_NUMBERS", DVPTR(W_NUMBERS), W_NUMBERS__STATIC ),
new dynitem( "WATERDRIP", DVPTR(WATERDRIP), WATERDRIP__STATIC ),
new dynitem( "WATERBUBBLE", DVPTR(WATERBUBBLE), WATERBUBBLE__STATIC ),
new dynitem( "WATERBUBBLEMAKER", DVPTR(WATERBUBBLEMAKER), WATERBUBBLEMAKER__STATIC ),
new dynitem( "W_FORCEFIELD", DVPTR(W_FORCEFIELD), W_FORCEFIELD__STATIC ),
new dynitem( "VACUUM", DVPTR(VACUUM), VACUUM__STATIC ),
new dynitem( "FOOTPRINTS2", DVPTR(FOOTPRINTS2), FOOTPRINTS2__STATIC ),
new dynitem( "FOOTPRINTS3", DVPTR(FOOTPRINTS3), FOOTPRINTS3__STATIC ),
new dynitem( "FOOTPRINTS4", DVPTR(FOOTPRINTS4), FOOTPRINTS4__STATIC ),
new dynitem( "EGG", DVPTR(EGG), EGG__STATIC ),
new dynitem( "SCALE", DVPTR(SCALE), SCALE__STATIC ),
new dynitem( "CHAIR3", DVPTR(CHAIR3), CHAIR3__STATIC ),
new dynitem( "CAMERALIGHT", DVPTR(CAMERALIGHT), CAMERALIGHT__STATIC ),
new dynitem( "MOVIECAMERA", DVPTR(MOVIECAMERA), MOVIECAMERA__STATIC ),
new dynitem( "IVUNIT", DVPTR(IVUNIT), IVUNIT__STATIC ),
new dynitem( "POT1", DVPTR(POT1), POT1__STATIC ),
new dynitem( "POT2", DVPTR(POT2), POT2__STATIC ),
new dynitem( "POT3", DVPTR(POT3), POT3__STATIC ),
new dynitem( "PIPE3B", DVPTR(PIPE3B), PIPE3B__STATIC ),
new dynitem( "WALLLIGHT3", DVPTR(WALLLIGHT3), WALLLIGHT3__STATIC ),
new dynitem( "WALLLIGHTBUST3", DVPTR(WALLLIGHTBUST3), WALLLIGHTBUST3__STATIC ),
new dynitem( "WALLLIGHT1", DVPTR(WALLLIGHT1), WALLLIGHT1__STATIC ),
new dynitem( "WALLLIGHTBUST1", DVPTR(WALLLIGHTBUST1), WALLLIGHTBUST1__STATIC ),
new dynitem( "WALLLIGHT2", DVPTR(WALLLIGHT2), WALLLIGHT2__STATIC ),
new dynitem( "WALLLIGHTBUST2", DVPTR(WALLLIGHTBUST2), WALLLIGHTBUST2__STATIC ),
new dynitem( "LIGHTSWITCH2", DVPTR(LIGHTSWITCH2), LIGHTSWITCH2__STATIC ),
new dynitem( "WAITTOBESEATED", DVPTR(WAITTOBESEATED), WAITTOBESEATED__STATIC ),
new dynitem( "DOORTILE14", DVPTR(DOORTILE14), DOORTILE14__STATIC ),
new dynitem( "STATUE", DVPTR(STATUE), STATUE__STATIC ),
new dynitem( "MIKE", DVPTR(MIKE), MIKE__STATIC ),
new dynitem( "VASE", DVPTR(VASE), VASE__STATIC ),
new dynitem( "SUSHIPLATE1", DVPTR(SUSHIPLATE1), SUSHIPLATE1__STATIC ),
new dynitem( "SUSHIPLATE2", DVPTR(SUSHIPLATE2), SUSHIPLATE2__STATIC ),
new dynitem( "SUSHIPLATE3", DVPTR(SUSHIPLATE3), SUSHIPLATE3__STATIC ),
new dynitem( "SUSHIPLATE4", DVPTR(SUSHIPLATE4), SUSHIPLATE4__STATIC ),
new dynitem( "DOORTILE16", DVPTR(DOORTILE16), DOORTILE16__STATIC ),
new dynitem( "SUSHIPLATE5", DVPTR(SUSHIPLATE5), SUSHIPLATE5__STATIC ),
new dynitem( "OJ", DVPTR(OJ), OJ__STATIC ),
new dynitem( "MASKWALL13", DVPTR(MASKWALL13), MASKWALL13__STATIC ),
new dynitem( "HURTRAIL", DVPTR(HURTRAIL), HURTRAIL__STATIC ),
new dynitem( "POWERSWITCH1", DVPTR(POWERSWITCH1), POWERSWITCH1__STATIC ),
new dynitem( "LOCKSWITCH1", DVPTR(LOCKSWITCH1), LOCKSWITCH1__STATIC ),
new dynitem( "POWERSWITCH2", DVPTR(POWERSWITCH2), POWERSWITCH2__STATIC ),
new dynitem( "ATM", DVPTR(ATM), ATM__STATIC ),
new dynitem( "STATUEFLASH", DVPTR(STATUEFLASH), STATUEFLASH__STATIC ),
new dynitem( "ATMBROKE", DVPTR(ATMBROKE), ATMBROKE__STATIC ),
new dynitem( "BIGHOLE2", DVPTR(BIGHOLE2), BIGHOLE2__STATIC ),
new dynitem( "STRIPEBALL", DVPTR(STRIPEBALL), STRIPEBALL__STATIC ),
new dynitem( "QUEBALL", DVPTR(QUEBALL), QUEBALL__STATIC ),
new dynitem( "POCKET", DVPTR(POCKET), POCKET__STATIC ),
new dynitem( "WOODENHORSE", DVPTR(WOODENHORSE), WOODENHORSE__STATIC ),
new dynitem( "TREE1", DVPTR(TREE1), TREE1__STATIC ),
new dynitem( "TREE2", DVPTR(TREE2), TREE2__STATIC ),
new dynitem( "CACTUS", DVPTR(CACTUS), CACTUS__STATIC ),
new dynitem( "MASKWALL2", DVPTR(MASKWALL2), MASKWALL2__STATIC ),
new dynitem( "MASKWALL3", DVPTR(MASKWALL3), MASKWALL3__STATIC ),
new dynitem( "MASKWALL4", DVPTR(MASKWALL4), MASKWALL4__STATIC ),
new dynitem( "FIREEXT", DVPTR(FIREEXT), FIREEXT__STATIC ),
new dynitem( "TOILETWATER", DVPTR(TOILETWATER), TOILETWATER__STATIC ),
new dynitem( "NEON1", DVPTR(NEON1), NEON1__STATIC ),
new dynitem( "NEON2", DVPTR(NEON2), NEON2__STATIC ),
new dynitem( "CACTUSBROKE", DVPTR(CACTUSBROKE), CACTUSBROKE__STATIC ),
new dynitem( "BOUNCEMINE", DVPTR(BOUNCEMINE), BOUNCEMINE__STATIC ),
new dynitem( "BROKEFIREHYDRENT", DVPTR(BROKEFIREHYDRENT), BROKEFIREHYDRENT__STATIC ),
new dynitem( "BOX", DVPTR(BOX), BOX__STATIC ),
new dynitem( "BULLETHOLE", DVPTR(BULLETHOLE), BULLETHOLE__STATIC ),
new dynitem( "BOTTLE1", DVPTR(BOTTLE1), BOTTLE1__STATIC ),
new dynitem( "BOTTLE2", DVPTR(BOTTLE2), BOTTLE2__STATIC ),
new dynitem( "BOTTLE3", DVPTR(BOTTLE3), BOTTLE3__STATIC ),
new dynitem( "BOTTLE4", DVPTR(BOTTLE4), BOTTLE4__STATIC ),
new dynitem( "FEMPIC5", DVPTR(FEMPIC5), FEMPIC5__STATIC ),
new dynitem( "FEMPIC6", DVPTR(FEMPIC6), FEMPIC6__STATIC ),
new dynitem( "FEMPIC7", DVPTR(FEMPIC7), FEMPIC7__STATIC ),
new dynitem( "HYDROPLANT", DVPTR(HYDROPLANT), HYDROPLANT__STATIC ),
new dynitem( "OCEANSPRITE1", DVPTR(OCEANSPRITE1), OCEANSPRITE1__STATIC ),
new dynitem( "OCEANSPRITE2", DVPTR(OCEANSPRITE2), OCEANSPRITE2__STATIC ),
new dynitem( "OCEANSPRITE3", DVPTR(OCEANSPRITE3), OCEANSPRITE3__STATIC ),
new dynitem( "OCEANSPRITE4", DVPTR(OCEANSPRITE4), OCEANSPRITE4__STATIC ),
new dynitem( "OCEANSPRITE5", DVPTR(OCEANSPRITE5), OCEANSPRITE5__STATIC ),
new dynitem( "GENERICPOLE", DVPTR(GENERICPOLE), GENERICPOLE__STATIC ),
new dynitem( "CONE", DVPTR(CONE), CONE__STATIC ),
new dynitem( "HANGLIGHT", DVPTR(HANGLIGHT), HANGLIGHT__STATIC ),
new dynitem( "HYDRENT", DVPTR(HYDRENT), HYDRENT__STATIC ),
new dynitem( "MASKWALL14", DVPTR(MASKWALL14), MASKWALL14__STATIC ),
new dynitem( "TIRE", DVPTR(TIRE), TIRE__STATIC ),
new dynitem( "PIPE5", DVPTR(PIPE5), PIPE5__STATIC ),
new dynitem( "PIPE6", DVPTR(PIPE6), PIPE6__STATIC ),
new dynitem( "PIPE4", DVPTR(PIPE4), PIPE4__STATIC ),
new dynitem( "PIPE4B", DVPTR(PIPE4B), PIPE4B__STATIC ),
new dynitem( "BROKEHYDROPLANT", DVPTR(BROKEHYDROPLANT), BROKEHYDROPLANT__STATIC ),
new dynitem( "PIPE5B", DVPTR(PIPE5B), PIPE5B__STATIC ),
new dynitem( "NEON3", DVPTR(NEON3), NEON3__STATIC ),
new dynitem( "NEON4", DVPTR(NEON4), NEON4__STATIC ),
new dynitem( "NEON5", DVPTR(NEON5), NEON5__STATIC ),
new dynitem( "BOTTLE5", DVPTR(BOTTLE5), BOTTLE5__STATIC ),
new dynitem( "BOTTLE6", DVPTR(BOTTLE6), BOTTLE6__STATIC ),
new dynitem( "BOTTLE8", DVPTR(BOTTLE8), BOTTLE8__STATIC ),
new dynitem( "SPOTLITE", DVPTR(SPOTLITE), SPOTLITE__STATIC ),
new dynitem( "HANGOOZ", DVPTR(HANGOOZ), HANGOOZ__STATIC ),
new dynitem( "MASKWALL15", DVPTR(MASKWALL15), MASKWALL15__STATIC ),
new dynitem( "BOTTLE7", DVPTR(BOTTLE7), BOTTLE7__STATIC ),
new dynitem( "HORSEONSIDE", DVPTR(HORSEONSIDE), HORSEONSIDE__STATIC ),
new dynitem( "GLASSPIECES", DVPTR(GLASSPIECES), GLASSPIECES__STATIC ),
new dynitem( "HORSELITE", DVPTR(HORSELITE), HORSELITE__STATIC ),
new dynitem( "DONUTS", DVPTR(DONUTS), DONUTS__STATIC ),
new dynitem( "NEON6", DVPTR(NEON6), NEON6__STATIC ),
new dynitem( "MASKWALL6", DVPTR(MASKWALL6), MASKWALL6__STATIC ),
new dynitem( "CLOCK", DVPTR(CLOCK), CLOCK__STATIC ),
new dynitem( "RUBBERCAN", DVPTR(RUBBERCAN), RUBBERCAN__STATIC ),
new dynitem( "BROKENCLOCK", DVPTR(BROKENCLOCK), BROKENCLOCK__STATIC ),
new dynitem( "PLUG", DVPTR(PLUG), PLUG__STATIC ),
new dynitem( "OOZFILTER", DVPTR(OOZFILTER), OOZFILTER__STATIC ),
new dynitem( "FLOORPLASMA", DVPTR(FLOORPLASMA), FLOORPLASMA__STATIC ),
new dynitem( "REACTOR", DVPTR(REACTOR), REACTOR__STATIC ),
new dynitem( "REACTORSPARK", DVPTR(REACTORSPARK), REACTORSPARK__STATIC ),
new dynitem( "REACTORBURNT", DVPTR(REACTORBURNT), REACTORBURNT__STATIC ),
new dynitem( "DOORTILE15", DVPTR(DOORTILE15), DOORTILE15__STATIC ),
new dynitem( "HANDSWITCH", DVPTR(HANDSWITCH), HANDSWITCH__STATIC ),
new dynitem( "CIRCLEPANNEL", DVPTR(CIRCLEPANNEL), CIRCLEPANNEL__STATIC ),
new dynitem( "CIRCLEPANNELBROKE", DVPTR(CIRCLEPANNELBROKE), CIRCLEPANNELBROKE__STATIC ),
new dynitem( "PULLSWITCH", DVPTR(PULLSWITCH), PULLSWITCH__STATIC ),
new dynitem( "MASKWALL8", DVPTR(MASKWALL8), MASKWALL8__STATIC ),
new dynitem( "BIGHOLE", DVPTR(BIGHOLE), BIGHOLE__STATIC ),
new dynitem( "ALIENSWITCH", DVPTR(ALIENSWITCH), ALIENSWITCH__STATIC ),
new dynitem( "DOORTILE21", DVPTR(DOORTILE21), DOORTILE21__STATIC ),
new dynitem( "HANDPRINTSWITCH", DVPTR(HANDPRINTSWITCH), HANDPRINTSWITCH__STATIC ),
new dynitem( "BOTTLE10", DVPTR(BOTTLE10), BOTTLE10__STATIC ),
new dynitem( "BOTTLE11", DVPTR(BOTTLE11), BOTTLE11__STATIC ),
new dynitem( "BOTTLE12", DVPTR(BOTTLE12), BOTTLE12__STATIC ),
new dynitem( "BOTTLE13", DVPTR(BOTTLE13), BOTTLE13__STATIC ),
new dynitem( "BOTTLE14", DVPTR(BOTTLE14), BOTTLE14__STATIC ),
new dynitem( "BOTTLE15", DVPTR(BOTTLE15), BOTTLE15__STATIC ),
new dynitem( "BOTTLE16", DVPTR(BOTTLE16), BOTTLE16__STATIC ),
new dynitem( "BOTTLE17", DVPTR(BOTTLE17), BOTTLE17__STATIC ),
new dynitem( "BOTTLE18", DVPTR(BOTTLE18), BOTTLE18__STATIC ),
new dynitem( "BOTTLE19", DVPTR(BOTTLE19), BOTTLE19__STATIC ),
new dynitem( "DOORTILE17", DVPTR(DOORTILE17), DOORTILE17__STATIC ),
new dynitem( "MASKWALL7", DVPTR(MASKWALL7), MASKWALL7__STATIC ),
new dynitem( "JAILBARBREAK", DVPTR(JAILBARBREAK), JAILBARBREAK__STATIC ),
new dynitem( "DOORTILE11", DVPTR(DOORTILE11), DOORTILE11__STATIC ),
new dynitem( "DOORTILE12", DVPTR(DOORTILE12), DOORTILE12__STATIC ),
new dynitem( "VENDMACHINE", DVPTR(VENDMACHINE), VENDMACHINE__STATIC ),
new dynitem( "VENDMACHINEBROKE", DVPTR(VENDMACHINEBROKE), VENDMACHINEBROKE__STATIC ),
new dynitem( "COLAMACHINE", DVPTR(COLAMACHINE), COLAMACHINE__STATIC ),
new dynitem( "COLAMACHINEBROKE", DVPTR(COLAMACHINEBROKE), COLAMACHINEBROKE__STATIC ),
new dynitem( "CRANEPOLE", DVPTR(CRANEPOLE), CRANEPOLE__STATIC ),
new dynitem( "CRANE", DVPTR(CRANE), CRANE__STATIC ),
new dynitem( "BARBROKE", DVPTR(BARBROKE), BARBROKE__STATIC ),
new dynitem( "BLOODPOOL", DVPTR(BLOODPOOL), BLOODPOOL__STATIC ),
new dynitem( "NUKEBARREL", DVPTR(NUKEBARREL), NUKEBARREL__STATIC ),
new dynitem( "NUKEBARRELDENTED", DVPTR(NUKEBARRELDENTED), NUKEBARRELDENTED__STATIC ),
new dynitem( "NUKEBARRELLEAKED", DVPTR(NUKEBARRELLEAKED), NUKEBARRELLEAKED__STATIC ),
new dynitem( "CANWITHSOMETHING", DVPTR(CANWITHSOMETHING), CANWITHSOMETHING__STATIC ),
new dynitem( "MONEY", DVPTR(MONEY), MONEY__STATIC ),
new dynitem( "BANNER", DVPTR(BANNER), BANNER__STATIC ),
new dynitem( "EXPLODINGBARREL", DVPTR(EXPLODINGBARREL), EXPLODINGBARREL__STATIC ),
new dynitem( "EXPLODINGBARREL2", DVPTR(EXPLODINGBARREL2), EXPLODINGBARREL2__STATIC ),
new dynitem( "FIREBARREL", DVPTR(FIREBARREL), FIREBARREL__STATIC ),
new dynitem( "SEENINE", DVPTR(SEENINE), SEENINE__STATIC ),
new dynitem( "SEENINEDEAD", DVPTR(SEENINEDEAD), SEENINEDEAD__STATIC ),
new dynitem( "STEAM", DVPTR(STEAM), STEAM__STATIC ),
new dynitem( "CEILINGSTEAM", DVPTR(CEILINGSTEAM), CEILINGSTEAM__STATIC ),
new dynitem( "PIPE6B", DVPTR(PIPE6B), PIPE6B__STATIC ),
new dynitem( "TRANSPORTERBEAM", DVPTR(TRANSPORTERBEAM), TRANSPORTERBEAM__STATIC ),
new dynitem( "RAT", DVPTR(RAT), RAT__STATIC ),
new dynitem( "TRASH", DVPTR(TRASH), TRASH__STATIC ),
new dynitem( "FEMPIC1", DVPTR(FEMPIC1), FEMPIC1__STATIC ),
new dynitem( "FEMPIC2", DVPTR(FEMPIC2), FEMPIC2__STATIC ),
new dynitem( "BLANKSCREEN", DVPTR(BLANKSCREEN), BLANKSCREEN__STATIC ),
new dynitem( "PODFEM1", DVPTR(PODFEM1), PODFEM1__STATIC ),
new dynitem( "FEMPIC3", DVPTR(FEMPIC3), FEMPIC3__STATIC ),
new dynitem( "FEMPIC4", DVPTR(FEMPIC4), FEMPIC4__STATIC ),
new dynitem( "FEM1", DVPTR(FEM1), FEM1__STATIC ),
new dynitem( "FEM2", DVPTR(FEM2), FEM2__STATIC ),
new dynitem( "FEM3", DVPTR(FEM3), FEM3__STATIC ),
new dynitem( "FEM5", DVPTR(FEM5), FEM5__STATIC ),
new dynitem( "BLOODYPOLE", DVPTR(BLOODYPOLE), BLOODYPOLE__STATIC ),
new dynitem( "FEM4", DVPTR(FEM4), FEM4__STATIC ),
new dynitem( "FEM6", DVPTR(FEM6), FEM6__STATIC ),
new dynitem( "FEM6PAD", DVPTR(FEM6PAD), FEM6PAD__STATIC ),
new dynitem( "FEM8", DVPTR(FEM8), FEM8__STATIC ),
new dynitem( "HELECOPT", DVPTR(HELECOPT), HELECOPT__STATIC ),
new dynitem( "FETUSJIB", DVPTR(FETUSJIB), FETUSJIB__STATIC ),
new dynitem( "HOLODUKE", DVPTR(HOLODUKE), HOLODUKE__STATIC ),
new dynitem( "SPACEMARINE", DVPTR(SPACEMARINE), SPACEMARINE__STATIC ),
new dynitem( "INDY", DVPTR(INDY), INDY__STATIC ),
new dynitem( "FETUS", DVPTR(FETUS), FETUS__STATIC ),
new dynitem( "FETUSBROKE", DVPTR(FETUSBROKE), FETUSBROKE__STATIC ),
new dynitem( "MONK", DVPTR(MONK), MONK__STATIC ),
new dynitem( "LUKE", DVPTR(LUKE), LUKE__STATIC ),
new dynitem( "COOLEXPLOSION1", DVPTR(COOLEXPLOSION1), COOLEXPLOSION1__STATIC ),
new dynitem( "WATERSPLASH2", DVPTR(WATERSPLASH2), WATERSPLASH2__STATIC ),
new dynitem( "FIREVASE", DVPTR(FIREVASE), FIREVASE__STATIC ),
new dynitem( "SCRATCH", DVPTR(SCRATCH), SCRATCH__STATIC ),
new dynitem( "FEM7", DVPTR(FEM7), FEM7__STATIC ),
new dynitem( "APLAYERTOP", DVPTR(APLAYERTOP), APLAYERTOP__STATIC ),
new dynitem( "APLAYER", DVPTR(APLAYER), APLAYER__STATIC ),
new dynitem( "PLAYERONWATER", DVPTR(PLAYERONWATER), PLAYERONWATER__STATIC ),
new dynitem( "DUKELYINGDEAD", DVPTR(DUKELYINGDEAD), DUKELYINGDEAD__STATIC ),
new dynitem( "DUKETORSO", DVPTR(DUKETORSO), DUKETORSO__STATIC ),
new dynitem( "DUKEGUN", DVPTR(DUKEGUN), DUKEGUN__STATIC ),
new dynitem( "DUKELEG", DVPTR(DUKELEG), DUKELEG__STATIC ),
new dynitem( "SHARK", DVPTR(SHARK), SHARK__STATIC ),
new dynitem( "BLOOD", DVPTR(BLOOD), BLOOD__STATIC ),
new dynitem( "FIRELASER", DVPTR(FIRELASER), FIRELASER__STATIC ),
new dynitem( "TRANSPORTERSTAR", DVPTR(TRANSPORTERSTAR), TRANSPORTERSTAR__STATIC ),
new dynitem( "SPIT", DVPTR(SPIT), SPIT__STATIC ),
new dynitem( "LOOGIE", DVPTR(LOOGIE), LOOGIE__STATIC ),
new dynitem( "FIST", DVPTR(FIST), FIST__STATIC ),
new dynitem( "FREEZEBLAST", DVPTR(FREEZEBLAST), FREEZEBLAST__STATIC ),
new dynitem( "DEVISTATORBLAST", DVPTR(DEVISTATORBLAST), DEVISTATORBLAST__STATIC ),
new dynitem( "SHRINKSPARK", DVPTR(SHRINKSPARK), SHRINKSPARK__STATIC ),
new dynitem( "TONGUE", DVPTR(TONGUE), TONGUE__STATIC ),
new dynitem( "MORTER", DVPTR(MORTER), MORTER__STATIC ),
new dynitem( "SHRINKEREXPLOSION", DVPTR(SHRINKEREXPLOSION), SHRINKEREXPLOSION__STATIC ),
new dynitem( "RADIUSEXPLOSION", DVPTR(RADIUSEXPLOSION), RADIUSEXPLOSION__STATIC ),
new dynitem( "FORCERIPPLE", DVPTR(FORCERIPPLE), FORCERIPPLE__STATIC ),
new dynitem( "LIZTROOP", DVPTR(LIZTROOP), LIZTROOP__STATIC ),
new dynitem( "LIZTROOPRUNNING", DVPTR(LIZTROOPRUNNING), LIZTROOPRUNNING__STATIC ),
new dynitem( "LIZTROOPSTAYPUT", DVPTR(LIZTROOPSTAYPUT), LIZTROOPSTAYPUT__STATIC ),
new dynitem( "LIZTOP", DVPTR(LIZTOP), LIZTOP__STATIC ),
new dynitem( "LIZTROOPSHOOT", DVPTR(LIZTROOPSHOOT), LIZTROOPSHOOT__STATIC ),
new dynitem( "LIZTROOPJETPACK", DVPTR(LIZTROOPJETPACK), LIZTROOPJETPACK__STATIC ),
new dynitem( "LIZTROOPDSPRITE", DVPTR(LIZTROOPDSPRITE), LIZTROOPDSPRITE__STATIC ),
new dynitem( "LIZTROOPONTOILET", DVPTR(LIZTROOPONTOILET), LIZTROOPONTOILET__STATIC ),
new dynitem( "LIZTROOPJUSTSIT", DVPTR(LIZTROOPJUSTSIT), LIZTROOPJUSTSIT__STATIC ),
new dynitem( "LIZTROOPDUCKING", DVPTR(LIZTROOPDUCKING), LIZTROOPDUCKING__STATIC ),
new dynitem( "HEADJIB1", DVPTR(HEADJIB1), HEADJIB1__STATIC ),
new dynitem( "ARMJIB1", DVPTR(ARMJIB1), ARMJIB1__STATIC ),
new dynitem( "LEGJIB1", DVPTR(LEGJIB1), LEGJIB1__STATIC ),
new dynitem( "CANNONBALL", DVPTR(CANNONBALL), CANNONBALL__STATIC ),
new dynitem( "OCTABRAIN", DVPTR(OCTABRAIN), OCTABRAIN__STATIC ),
new dynitem( "OCTABRAINSTAYPUT", DVPTR(OCTABRAINSTAYPUT), OCTABRAINSTAYPUT__STATIC ),
new dynitem( "OCTATOP", DVPTR(OCTATOP), OCTATOP__STATIC ),
new dynitem( "OCTADEADSPRITE", DVPTR(OCTADEADSPRITE), OCTADEADSPRITE__STATIC ),
new dynitem( "INNERJAW", DVPTR(INNERJAW), INNERJAW__STATIC ),
new dynitem( "DRONE", DVPTR(DRONE), DRONE__STATIC ),
new dynitem( "EXPLOSION2", DVPTR(EXPLOSION2), EXPLOSION2__STATIC ),
new dynitem( "COMMANDER", DVPTR(COMMANDER), COMMANDER__STATIC ),
new dynitem( "COMMANDERSTAYPUT", DVPTR(COMMANDERSTAYPUT), COMMANDERSTAYPUT__STATIC ),
new dynitem( "RECON", DVPTR(RECON), RECON__STATIC ),
new dynitem( "TANK", DVPTR(TANK), TANK__STATIC ),
new dynitem( "PIGCOP", DVPTR(PIGCOP), PIGCOP__STATIC ),
new dynitem( "PIGCOPSTAYPUT", DVPTR(PIGCOPSTAYPUT), PIGCOPSTAYPUT__STATIC ),
new dynitem( "PIGCOPDIVE", DVPTR(PIGCOPDIVE), PIGCOPDIVE__STATIC ),
new dynitem( "PIGCOPDEADSPRITE", DVPTR(PIGCOPDEADSPRITE), PIGCOPDEADSPRITE__STATIC ),
new dynitem( "PIGTOP", DVPTR(PIGTOP), PIGTOP__STATIC ),
new dynitem( "LIZMAN", DVPTR(LIZMAN), LIZMAN__STATIC ),
new dynitem( "LIZMANSTAYPUT", DVPTR(LIZMANSTAYPUT), LIZMANSTAYPUT__STATIC ),
new dynitem( "LIZMANSPITTING", DVPTR(LIZMANSPITTING), LIZMANSPITTING__STATIC ),
new dynitem( "LIZMANFEEDING", DVPTR(LIZMANFEEDING), LIZMANFEEDING__STATIC ),
new dynitem( "LIZMANJUMP", DVPTR(LIZMANJUMP), LIZMANJUMP__STATIC ),
new dynitem( "LIZMANDEADSPRITE", DVPTR(LIZMANDEADSPRITE), LIZMANDEADSPRITE__STATIC ),
new dynitem( "FECES", DVPTR(FECES), FECES__STATIC ),
new dynitem( "LIZMANHEAD1", DVPTR(LIZMANHEAD1), LIZMANHEAD1__STATIC ),
new dynitem( "LIZMANARM1", DVPTR(LIZMANARM1), LIZMANARM1__STATIC ),
new dynitem( "LIZMANLEG1", DVPTR(LIZMANLEG1), LIZMANLEG1__STATIC ),
new dynitem( "EXPLOSION2BOT", DVPTR(EXPLOSION2BOT), EXPLOSION2BOT__STATIC ),
new dynitem( "USERWEAPON", DVPTR(USERWEAPON), USERWEAPON__STATIC ),
new dynitem( "HEADERBAR", DVPTR(HEADERBAR), HEADERBAR__STATIC ),
new dynitem( "JIBS1", DVPTR(JIBS1), JIBS1__STATIC ),
new dynitem( "JIBS2", DVPTR(JIBS2), JIBS2__STATIC ),
new dynitem( "JIBS3", DVPTR(JIBS3), JIBS3__STATIC ),
new dynitem( "JIBS4", DVPTR(JIBS4), JIBS4__STATIC ),
new dynitem( "JIBS5", DVPTR(JIBS5), JIBS5__STATIC ),
new dynitem( "BURNING", DVPTR(BURNING), BURNING__STATIC ),
new dynitem( "FIRE", DVPTR(FIRE), FIRE__STATIC ),
new dynitem( "JIBS6", DVPTR(JIBS6), JIBS6__STATIC ),
new dynitem( "BLOODSPLAT1", DVPTR(BLOODSPLAT1), BLOODSPLAT1__STATIC ),
new dynitem( "BLOODSPLAT3", DVPTR(BLOODSPLAT3), BLOODSPLAT3__STATIC ),
new dynitem( "BLOODSPLAT2", DVPTR(BLOODSPLAT2), BLOODSPLAT2__STATIC ),
new dynitem( "BLOODSPLAT4", DVPTR(BLOODSPLAT4), BLOODSPLAT4__STATIC ),
new dynitem( "OOZ", DVPTR(OOZ), OOZ__STATIC ),
new dynitem( "OOZ2", DVPTR(OOZ2), OOZ2__STATIC ),
new dynitem( "WALLBLOOD1", DVPTR(WALLBLOOD1), WALLBLOOD1__STATIC ),
new dynitem( "WALLBLOOD2", DVPTR(WALLBLOOD2), WALLBLOOD2__STATIC ),
new dynitem( "WALLBLOOD3", DVPTR(WALLBLOOD3), WALLBLOOD3__STATIC ),
new dynitem( "WALLBLOOD4", DVPTR(WALLBLOOD4), WALLBLOOD4__STATIC ),
new dynitem( "WALLBLOOD5", DVPTR(WALLBLOOD5), WALLBLOOD5__STATIC ),
new dynitem( "WALLBLOOD6", DVPTR(WALLBLOOD6), WALLBLOOD6__STATIC ),
new dynitem( "WALLBLOOD7", DVPTR(WALLBLOOD7), WALLBLOOD7__STATIC ),
new dynitem( "WALLBLOOD8", DVPTR(WALLBLOOD8), WALLBLOOD8__STATIC ),
new dynitem( "BURNING2", DVPTR(BURNING2), BURNING2__STATIC ),
new dynitem( "FIRE2", DVPTR(FIRE2), FIRE2__STATIC ),
new dynitem( "CRACKKNUCKLES", DVPTR(CRACKKNUCKLES), CRACKKNUCKLES__STATIC ),
new dynitem( "SMALLSMOKE", DVPTR(SMALLSMOKE), SMALLSMOKE__STATIC ),
new dynitem( "SMALLSMOKEMAKER", DVPTR(SMALLSMOKEMAKER), SMALLSMOKEMAKER__STATIC ),
new dynitem( "FLOORFLAME", DVPTR(FLOORFLAME), FLOORFLAME__STATIC ),
new dynitem( "ROTATEGUN", DVPTR(ROTATEGUN), ROTATEGUN__STATIC ),
new dynitem( "GREENSLIME", DVPTR(GREENSLIME), GREENSLIME__STATIC ),
new dynitem( "WATERDRIPSPLASH", DVPTR(WATERDRIPSPLASH), WATERDRIPSPLASH__STATIC ),
new dynitem( "SCRAP6", DVPTR(SCRAP6), SCRAP6__STATIC ),
new dynitem( "SCRAP1", DVPTR(SCRAP1), SCRAP1__STATIC ),
new dynitem( "SCRAP2", DVPTR(SCRAP2), SCRAP2__STATIC ),
new dynitem( "SCRAP3", DVPTR(SCRAP3), SCRAP3__STATIC ),
new dynitem( "SCRAP4", DVPTR(SCRAP4), SCRAP4__STATIC ),
new dynitem( "SCRAP5", DVPTR(SCRAP5), SCRAP5__STATIC ),
new dynitem( "ORGANTIC", DVPTR(ORGANTIC), ORGANTIC__STATIC ),
new dynitem( "BETAVERSION", DVPTR(BETAVERSION), BETAVERSION__STATIC ),
new dynitem( "PLAYERISHERE", DVPTR(PLAYERISHERE), PLAYERISHERE__STATIC ),
new dynitem( "PLAYERWASHERE", DVPTR(PLAYERWASHERE), PLAYERWASHERE__STATIC ),
new dynitem( "SELECTDIR", DVPTR(SELECTDIR), SELECTDIR__STATIC ),
new dynitem( "F1HELP", DVPTR(F1HELP), F1HELP__STATIC ),
new dynitem( "NOTCHON", DVPTR(NOTCHON), NOTCHON__STATIC ),
new dynitem( "NOTCHOFF", DVPTR(NOTCHOFF), NOTCHOFF__STATIC ),
new dynitem( "GROWSPARK", DVPTR(GROWSPARK), GROWSPARK__STATIC ),
new dynitem( "DUKEICON", DVPTR(DUKEICON), DUKEICON__STATIC ),
new dynitem( "BADGUYICON", DVPTR(BADGUYICON), BADGUYICON__STATIC ),
new dynitem( "FOODICON", DVPTR(FOODICON), FOODICON__STATIC ),
new dynitem( "GETICON", DVPTR(GETICON), GETICON__STATIC ),
new dynitem( "MENUSCREEN", DVPTR(MENUSCREEN), MENUSCREEN__STATIC ),
new dynitem( "MENUBAR", DVPTR(MENUBAR), MENUBAR__STATIC ),
new dynitem( "KILLSICON", DVPTR(KILLSICON), KILLSICON__STATIC ),
new dynitem( "FIRSTAID_ICON", DVPTR(FIRSTAID_ICON), FIRSTAID_ICON__STATIC ),
new dynitem( "HEAT_ICON", DVPTR(HEAT_ICON), HEAT_ICON__STATIC ),
new dynitem( "BOTTOMSTATUSBAR", DVPTR(BOTTOMSTATUSBAR), BOTTOMSTATUSBAR__STATIC ),
new dynitem( "BOOT_ICON", DVPTR(BOOT_ICON), BOOT_ICON__STATIC ),
new dynitem( "FRAGBAR", DVPTR(FRAGBAR), FRAGBAR__STATIC ),
new dynitem( "JETPACK_ICON", DVPTR(JETPACK_ICON), JETPACK_ICON__STATIC ),
new dynitem( "AIRTANK_ICON", DVPTR(AIRTANK_ICON), AIRTANK_ICON__STATIC ),
new dynitem( "STEROIDS_ICON", DVPTR(STEROIDS_ICON), STEROIDS_ICON__STATIC ),
new dynitem( "HOLODUKE_ICON", DVPTR(HOLODUKE_ICON), HOLODUKE_ICON__STATIC ),
new dynitem( "ACCESS_ICON", DVPTR(ACCESS_ICON), ACCESS_ICON__STATIC ),
new dynitem( "DIGITALNUM", DVPTR(DIGITALNUM), DIGITALNUM__STATIC ),
new dynitem( "DUKECAR", DVPTR(DUKECAR), DUKECAR__STATIC ),
new dynitem( "CAMCORNER", DVPTR(CAMCORNER), CAMCORNER__STATIC ),
new dynitem( "CAMLIGHT", DVPTR(CAMLIGHT), CAMLIGHT__STATIC ),
new dynitem( "LOGO", DVPTR(LOGO), LOGO__STATIC ),
new dynitem( "TITLE", DVPTR(TITLE), TITLE__STATIC ),
new dynitem( "NUKEWARNINGICON", DVPTR(NUKEWARNINGICON), NUKEWARNINGICON__STATIC ),
new dynitem( "MOUSECURSOR", DVPTR(MOUSECURSOR), MOUSECURSOR__STATIC ),
new dynitem( "SLIDEBAR", DVPTR(SLIDEBAR), SLIDEBAR__STATIC ),
new dynitem( "DREALMS", DVPTR(DREALMS), DREALMS__STATIC ),
new dynitem( "BETASCREEN", DVPTR(BETASCREEN), BETASCREEN__STATIC ),
new dynitem( "WINDOWBORDER1", DVPTR(WINDOWBORDER1), WINDOWBORDER1__STATIC ),
new dynitem( "TEXTBOX", DVPTR(TEXTBOX), TEXTBOX__STATIC ),
new dynitem( "WINDOWBORDER2", DVPTR(WINDOWBORDER2), WINDOWBORDER2__STATIC ),
new dynitem( "DUKENUKEM", DVPTR(DUKENUKEM), DUKENUKEM__STATIC ),
new dynitem( "THREEDEE", DVPTR(THREEDEE), THREEDEE__STATIC ),
new dynitem( "INGAMEDUKETHREEDEE", DVPTR(INGAMEDUKETHREEDEE), INGAMEDUKETHREEDEE__STATIC ),
new dynitem( "TENSCREEN", DVPTR(TENSCREEN), TENSCREEN__STATIC ),
new dynitem( "PLUTOPAKSPRITE", DVPTR(PLUTOPAKSPRITE), PLUTOPAKSPRITE__STATIC ),
new dynitem( "DEVISTATOR", DVPTR(DEVISTATOR), DEVISTATOR__STATIC ),
new dynitem( "KNEE", DVPTR(KNEE), KNEE__STATIC ),
new dynitem( "CROSSHAIR", DVPTR(CROSSHAIR), CROSSHAIR__STATIC ),
new dynitem( "FIRSTGUN", DVPTR(FIRSTGUN), FIRSTGUN__STATIC ),
new dynitem( "FIRSTGUNRELOAD", DVPTR(FIRSTGUNRELOAD), FIRSTGUNRELOAD__STATIC ),
new dynitem( "FALLINGCLIP", DVPTR(FALLINGCLIP), FALLINGCLIP__STATIC ),
new dynitem( "CLIPINHAND", DVPTR(CLIPINHAND), CLIPINHAND__STATIC ),
new dynitem( "HAND", DVPTR(HAND), HAND__STATIC ),
new dynitem( "SHELL", DVPTR(SHELL), SHELL__STATIC ),
new dynitem( "SHOTGUNSHELL", DVPTR(SHOTGUNSHELL), SHOTGUNSHELL__STATIC ),
new dynitem( "CHAINGUN", DVPTR(CHAINGUN), CHAINGUN__STATIC ),
new dynitem( "RPGGUN", DVPTR(RPGGUN), RPGGUN__STATIC ),
new dynitem( "RPGMUZZLEFLASH", DVPTR(RPGMUZZLEFLASH), RPGMUZZLEFLASH__STATIC ),
new dynitem( "FREEZE", DVPTR(FREEZE), FREEZE__STATIC ),
new dynitem( "CATLITE", DVPTR(CATLITE), CATLITE__STATIC ),
new dynitem( "SHRINKER", DVPTR(SHRINKER), SHRINKER__STATIC ),
new dynitem( "HANDHOLDINGLASER", DVPTR(HANDHOLDINGLASER), HANDHOLDINGLASER__STATIC ),
new dynitem( "TRIPBOMB", DVPTR(TRIPBOMB), TRIPBOMB__STATIC ),
new dynitem( "LASERLINE", DVPTR(LASERLINE), LASERLINE__STATIC ),
new dynitem( "HANDHOLDINGACCESS", DVPTR(HANDHOLDINGACCESS), HANDHOLDINGACCESS__STATIC ),
new dynitem( "HANDREMOTE", DVPTR(HANDREMOTE), HANDREMOTE__STATIC ),
new dynitem( "HANDTHROW", DVPTR(HANDTHROW), HANDTHROW__STATIC ),
new dynitem( "TIP", DVPTR(TIP), TIP__STATIC ),
new dynitem( "GLAIR", DVPTR(GLAIR), GLAIR__STATIC ),
new dynitem( "SCUBAMASK", DVPTR(SCUBAMASK), SCUBAMASK__STATIC ),
new dynitem( "SPACEMASK", DVPTR(SPACEMASK), SPACEMASK__STATIC ),
new dynitem( "FORCESPHERE", DVPTR(FORCESPHERE), FORCESPHERE__STATIC ),
new dynitem( "SHOTSPARK1", DVPTR(SHOTSPARK1), SHOTSPARK1__STATIC ),
new dynitem( "RPG", DVPTR(RPG), RPG__STATIC ),
new dynitem( "LASERSITE", DVPTR(LASERSITE), LASERSITE__STATIC ),
new dynitem( "SHOTGUN", DVPTR(SHOTGUN), SHOTGUN__STATIC ),
new dynitem( "BOSS1", DVPTR(BOSS1), BOSS1__STATIC ),
new dynitem( "BOSS1STAYPUT", DVPTR(BOSS1STAYPUT), BOSS1STAYPUT__STATIC ),
new dynitem( "BOSS1SHOOT", DVPTR(BOSS1SHOOT), BOSS1SHOOT__STATIC ),
new dynitem( "BOSS1LOB", DVPTR(BOSS1LOB), BOSS1LOB__STATIC ),
new dynitem( "BOSSTOP", DVPTR(BOSSTOP), BOSSTOP__STATIC ),
new dynitem( "BOSS2", DVPTR(BOSS2), BOSS2__STATIC ),
new dynitem( "BOSS3", DVPTR(BOSS3), BOSS3__STATIC ),
new dynitem( "SPINNINGNUKEICON", DVPTR(SPINNINGNUKEICON), SPINNINGNUKEICON__STATIC ),
new dynitem( "BIGFNTCURSOR", DVPTR(BIGFNTCURSOR), BIGFNTCURSOR__STATIC ),
new dynitem( "SMALLFNTCURSOR", DVPTR(SMALLFNTCURSOR), SMALLFNTCURSOR__STATIC ),
new dynitem( "STARTALPHANUM", DVPTR(STARTALPHANUM), STARTALPHANUM__STATIC ),
new dynitem( "ENDALPHANUM", DVPTR(ENDALPHANUM), ENDALPHANUM__STATIC ),
new dynitem( "BIGALPHANUM", DVPTR(BIGALPHANUM), BIGALPHANUM__STATIC ),
new dynitem( "BIGPERIOD", DVPTR(BIGPERIOD), BIGPERIOD__STATIC ),
new dynitem( "BIGCOMMA", DVPTR(BIGCOMMA), BIGCOMMA__STATIC ),
new dynitem( "BIGX", DVPTR(BIGX_), BIGX__STATIC ),
new dynitem( "BIGQ", DVPTR(BIGQ), BIGQ__STATIC ),
new dynitem( "BIGSEMI", DVPTR(BIGSEMI), BIGSEMI__STATIC ),
new dynitem( "BIGCOLIN", DVPTR(BIGCOLIN), BIGCOLIN__STATIC ),
new dynitem( "THREEBYFIVE", DVPTR(THREEBYFIVE), THREEBYFIVE__STATIC ),
new dynitem( "BIGAPPOS", DVPTR(BIGAPPOS), BIGAPPOS__STATIC ),
new dynitem( "BLANK", DVPTR(BLANK), BLANK__STATIC ),
new dynitem( "MINIFONT", DVPTR(MINIFONT), MINIFONT__STATIC ),
new dynitem( "BUTTON1", DVPTR(BUTTON1), BUTTON1__STATIC ),
new dynitem( "GLASS3", DVPTR(GLASS3), GLASS3__STATIC ),
new dynitem( "RESPAWNMARKERRED", DVPTR(RESPAWNMARKERRED), RESPAWNMARKERRED__STATIC ),
new dynitem( "RESPAWNMARKERYELLOW", DVPTR(RESPAWNMARKERYELLOW), RESPAWNMARKERYELLOW__STATIC ),
new dynitem( "RESPAWNMARKERGREEN", DVPTR(RESPAWNMARKERGREEN), RESPAWNMARKERGREEN__STATIC ),
new dynitem( "BONUSSCREEN", DVPTR(BONUSSCREEN), BONUSSCREEN__STATIC ),
new dynitem( "VIEWBORDER", DVPTR(VIEWBORDER), VIEWBORDER__STATIC ),
new dynitem( "VICTORY1", DVPTR(VICTORY1), VICTORY1__STATIC ),
new dynitem( "ORDERING", DVPTR(ORDERING), ORDERING__STATIC ),
new dynitem( "TEXTSTORY", DVPTR(TEXTSTORY), TEXTSTORY__STATIC ),
new dynitem( "LOADSCREEN", DVPTR(LOADSCREEN), LOADSCREEN__STATIC ),
new dynitem( "BORNTOBEWILDSCREEN", DVPTR(BORNTOBEWILDSCREEN), BORNTOBEWILDSCREEN__STATIC ),
new dynitem( "BLIMP", DVPTR(BLIMP), BLIMP__STATIC ),
new dynitem( "FEM9", DVPTR(FEM9), FEM9__STATIC ),
new dynitem( "FOOTPRINT", DVPTR(FOOTPRINT), FOOTPRINT__STATIC ),
new dynitem( "FRAMEEFFECT1_13", DVPTR(FRAMEEFFECT1_13), FRAMEEFFECT1_13__STATIC ),
new dynitem( "POOP", DVPTR(POOP), POOP__STATIC ),
new dynitem( "FRAMEEFFECT1", DVPTR(FRAMEEFFECT1), FRAMEEFFECT1__STATIC ),
new dynitem( "PANNEL3", DVPTR(PANNEL3), PANNEL3__STATIC ),
new dynitem( "SCREENBREAK14", DVPTR(SCREENBREAK14), SCREENBREAK14__STATIC ),
new dynitem( "SCREENBREAK15", DVPTR(SCREENBREAK15), SCREENBREAK15__STATIC ),
new dynitem( "SCREENBREAK19", DVPTR(SCREENBREAK19), SCREENBREAK19__STATIC ),
new dynitem( "SCREENBREAK16", DVPTR(SCREENBREAK16), SCREENBREAK16__STATIC ),
new dynitem( "SCREENBREAK17", DVPTR(SCREENBREAK17), SCREENBREAK17__STATIC ),
new dynitem( "SCREENBREAK18", DVPTR(SCREENBREAK18), SCREENBREAK18__STATIC ),
new dynitem( "W_TECHWALL11", DVPTR(W_TECHWALL11), W_TECHWALL11__STATIC ),
new dynitem( "W_TECHWALL12", DVPTR(W_TECHWALL12), W_TECHWALL12__STATIC ),
new dynitem( "W_TECHWALL13", DVPTR(W_TECHWALL13), W_TECHWALL13__STATIC ),
new dynitem( "W_TECHWALL14", DVPTR(W_TECHWALL14), W_TECHWALL14__STATIC ),
new dynitem( "W_TECHWALL5", DVPTR(W_TECHWALL5), W_TECHWALL5__STATIC ),
new dynitem( "W_TECHWALL6", DVPTR(W_TECHWALL6), W_TECHWALL6__STATIC ),
new dynitem( "W_TECHWALL7", DVPTR(W_TECHWALL7), W_TECHWALL7__STATIC ),
new dynitem( "W_TECHWALL8", DVPTR(W_TECHWALL8), W_TECHWALL8__STATIC ),
new dynitem( "W_TECHWALL9", DVPTR(W_TECHWALL9), W_TECHWALL9__STATIC ),
new dynitem( "BPANNEL3", DVPTR(BPANNEL3), BPANNEL3__STATIC ),
new dynitem( "W_HITTECHWALL16", DVPTR(W_HITTECHWALL16), W_HITTECHWALL16__STATIC ),
new dynitem( "W_HITTECHWALL10", DVPTR(W_HITTECHWALL10), W_HITTECHWALL10__STATIC ),
new dynitem( "W_HITTECHWALL15", DVPTR(W_HITTECHWALL15), W_HITTECHWALL15__STATIC ),
new dynitem( "W_MILKSHELF", DVPTR(W_MILKSHELF), W_MILKSHELF__STATIC ),
new dynitem( "W_MILKSHELFBROKE", DVPTR(W_MILKSHELFBROKE), W_MILKSHELFBROKE__STATIC ),
new dynitem( "PURPLELAVA", DVPTR(PURPLELAVA), PURPLELAVA__STATIC ),
new dynitem( "LAVABUBBLE", DVPTR(LAVABUBBLE), LAVABUBBLE__STATIC ),
new dynitem( "DUKECUTOUT", DVPTR(DUKECUTOUT), DUKECUTOUT__STATIC ),
new dynitem( "TARGET", DVPTR(TARGET), TARGET__STATIC ),
new dynitem( "GUNPOWDERBARREL", DVPTR(GUNPOWDERBARREL), GUNPOWDERBARREL__STATIC ),
new dynitem( "DUCK", DVPTR(DUCK), DUCK__STATIC ),
new dynitem( "HATRACK", DVPTR(HATRACK), HATRACK__STATIC ),
new dynitem( "DESKLAMP", DVPTR(DESKLAMP), DESKLAMP__STATIC ),
new dynitem( "COFFEEMACHINE", DVPTR(COFFEEMACHINE), COFFEEMACHINE__STATIC ),
new dynitem( "CUPS", DVPTR(CUPS), CUPS__STATIC ),
new dynitem( "GAVALS", DVPTR(GAVALS), GAVALS__STATIC ),
new dynitem( "GAVALS2", DVPTR(GAVALS2), GAVALS2__STATIC ),
new dynitem( "POLICELIGHTPOLE", DVPTR(POLICELIGHTPOLE), POLICELIGHTPOLE__STATIC ),
new dynitem( "FLOORBASKET", DVPTR(FLOORBASKET), FLOORBASKET__STATIC ),
new dynitem( "PUKE", DVPTR(PUKE), PUKE__STATIC ),
new dynitem( "DOORTILE23", DVPTR(DOORTILE23), DOORTILE23__STATIC ),
new dynitem( "TOPSECRET", DVPTR(TOPSECRET), TOPSECRET__STATIC ),
new dynitem( "SPEAKER", DVPTR(SPEAKER), SPEAKER__STATIC ),
new dynitem( "TEDDYBEAR", DVPTR(TEDDYBEAR), TEDDYBEAR__STATIC ),
new dynitem( "ROBOTDOG", DVPTR(ROBOTDOG), ROBOTDOG__STATIC ),
new dynitem( "ROBOTPIRATE", DVPTR(ROBOTPIRATE), ROBOTPIRATE__STATIC ),
new dynitem( "ROBOTMOUSE", DVPTR(ROBOTMOUSE), ROBOTMOUSE__STATIC ),
new dynitem( "MAIL", DVPTR(MAIL), MAIL__STATIC ),
new dynitem( "MAILBAG", DVPTR(MAILBAG), MAILBAG__STATIC ),
new dynitem( "HOTMEAT", DVPTR(HOTMEAT), HOTMEAT__STATIC ),
new dynitem( "COFFEEMUG", DVPTR(COFFEEMUG), COFFEEMUG__STATIC ),
new dynitem( "DONUTS2", DVPTR(DONUTS2), DONUTS2__STATIC ),
new dynitem( "TRIPODCAMERA", DVPTR(TRIPODCAMERA), TRIPODCAMERA__STATIC ),
new dynitem( "METER", DVPTR(METER), METER__STATIC ),
new dynitem( "DESKPHONE", DVPTR(DESKPHONE), DESKPHONE__STATIC ),
new dynitem( "GUMBALLMACHINE", DVPTR(GUMBALLMACHINE), GUMBALLMACHINE__STATIC ),
new dynitem( "GUMBALLMACHINEBROKE", DVPTR(GUMBALLMACHINEBROKE), GUMBALLMACHINEBROKE__STATIC ),
new dynitem( "PAPER", DVPTR(PAPER), PAPER__STATIC ),
new dynitem( "MACE", DVPTR(MACE), MACE__STATIC ),
new dynitem( "GENERICPOLE2", DVPTR(GENERICPOLE2), GENERICPOLE2__STATIC ),
new dynitem( "XXXSTACY", DVPTR(XXXSTACY), XXXSTACY__STATIC ),
new dynitem( "WETFLOOR", DVPTR(WETFLOOR), WETFLOOR__STATIC ),
new dynitem( "BROOM", DVPTR(BROOM), BROOM__STATIC ),
new dynitem( "MOP", DVPTR(MOP), MOP__STATIC ),
new dynitem( "LETTER", DVPTR(LETTER), LETTER__STATIC ),
new dynitem( "PIRATE1A", DVPTR(PIRATE1A), PIRATE1A__STATIC ),
new dynitem( "PIRATE4A", DVPTR(PIRATE4A), PIRATE4A__STATIC ),
new dynitem( "PIRATE2A", DVPTR(PIRATE2A), PIRATE2A__STATIC ),
new dynitem( "PIRATE5A", DVPTR(PIRATE5A), PIRATE5A__STATIC ),
new dynitem( "PIRATE3A", DVPTR(PIRATE3A), PIRATE3A__STATIC ),
new dynitem( "PIRATE6A", DVPTR(PIRATE6A), PIRATE6A__STATIC ),
new dynitem( "PIRATEHALF", DVPTR(PIRATEHALF), PIRATEHALF__STATIC ),
new dynitem( "CHESTOFGOLD", DVPTR(CHESTOFGOLD), CHESTOFGOLD__STATIC ),
new dynitem( "SIDEBOLT1", DVPTR(SIDEBOLT1), SIDEBOLT1__STATIC ),
new dynitem( "FOODOBJECT1", DVPTR(FOODOBJECT1), FOODOBJECT1__STATIC ),
new dynitem( "FOODOBJECT2", DVPTR(FOODOBJECT2), FOODOBJECT2__STATIC ),
new dynitem( "FOODOBJECT3", DVPTR(FOODOBJECT3), FOODOBJECT3__STATIC ),
new dynitem( "FOODOBJECT4", DVPTR(FOODOBJECT4), FOODOBJECT4__STATIC ),
new dynitem( "FOODOBJECT5", DVPTR(FOODOBJECT5), FOODOBJECT5__STATIC ),
new dynitem( "FOODOBJECT6", DVPTR(FOODOBJECT6), FOODOBJECT6__STATIC ),
new dynitem( "FOODOBJECT7", DVPTR(FOODOBJECT7), FOODOBJECT7__STATIC ),
new dynitem( "FOODOBJECT8", DVPTR(FOODOBJECT8), FOODOBJECT8__STATIC ),
new dynitem( "FOODOBJECT9", DVPTR(FOODOBJECT9), FOODOBJECT9__STATIC ),
new dynitem( "FOODOBJECT10", DVPTR(FOODOBJECT10), FOODOBJECT10__STATIC ),
new dynitem( "FOODOBJECT11", DVPTR(FOODOBJECT11), FOODOBJECT11__STATIC ),
new dynitem( "FOODOBJECT12", DVPTR(FOODOBJECT12), FOODOBJECT12__STATIC ),
new dynitem( "FOODOBJECT13", DVPTR(FOODOBJECT13), FOODOBJECT13__STATIC ),
new dynitem( "FOODOBJECT14", DVPTR(FOODOBJECT14), FOODOBJECT14__STATIC ),
new dynitem( "FOODOBJECT15", DVPTR(FOODOBJECT15), FOODOBJECT15__STATIC ),
new dynitem( "FOODOBJECT16", DVPTR(FOODOBJECT16), FOODOBJECT16__STATIC ),
new dynitem( "FOODOBJECT17", DVPTR(FOODOBJECT17), FOODOBJECT17__STATIC ),
new dynitem( "FOODOBJECT18", DVPTR(FOODOBJECT18), FOODOBJECT18__STATIC ),
new dynitem( "FOODOBJECT19", DVPTR(FOODOBJECT19), FOODOBJECT19__STATIC ),
new dynitem( "FOODOBJECT20", DVPTR(FOODOBJECT20), FOODOBJECT20__STATIC ),
new dynitem( "HEADLAMP", DVPTR(HEADLAMP), HEADLAMP__STATIC ),
new dynitem( "TAMPON", DVPTR(TAMPON), TAMPON__STATIC ),
new dynitem( "SKINNEDCHICKEN", DVPTR(SKINNEDCHICKEN), SKINNEDCHICKEN__STATIC ),
new dynitem( "FEATHEREDCHICKEN", DVPTR(FEATHEREDCHICKEN), FEATHEREDCHICKEN__STATIC ),
new dynitem( "ROBOTDOG2", DVPTR(ROBOTDOG2), ROBOTDOG2__STATIC ),
new dynitem( "JOLLYMEAL", DVPTR(JOLLYMEAL), JOLLYMEAL__STATIC ),
new dynitem( "DUKEBURGER", DVPTR(DUKEBURGER), DUKEBURGER__STATIC ),
new dynitem( "SHOPPINGCART", DVPTR(SHOPPINGCART), SHOPPINGCART__STATIC ),
new dynitem( "CANWITHSOMETHING2", DVPTR(CANWITHSOMETHING2), CANWITHSOMETHING2__STATIC ),
new dynitem( "CANWITHSOMETHING3", DVPTR(CANWITHSOMETHING3), CANWITHSOMETHING3__STATIC ),
new dynitem( "CANWITHSOMETHING4", DVPTR(CANWITHSOMETHING4), CANWITHSOMETHING4__STATIC ),
new dynitem( "SNAKEP", DVPTR(SNAKEP), SNAKEP__STATIC ),
new dynitem( "DOLPHIN1", DVPTR(DOLPHIN1), DOLPHIN1__STATIC ),
new dynitem( "DOLPHIN2", DVPTR(DOLPHIN2), DOLPHIN2__STATIC ),
new dynitem( "NEWBEAST", DVPTR(NEWBEAST), NEWBEAST__STATIC ),
new dynitem( "NEWBEASTSTAYPUT", DVPTR(NEWBEASTSTAYPUT), NEWBEASTSTAYPUT__STATIC ),
new dynitem( "NEWBEASTJUMP", DVPTR(NEWBEASTJUMP), NEWBEASTJUMP__STATIC ),
new dynitem( "NEWBEASTHANG", DVPTR(NEWBEASTHANG), NEWBEASTHANG__STATIC ),
new dynitem( "NEWBEASTHANGDEAD", DVPTR(NEWBEASTHANGDEAD), NEWBEASTHANGDEAD__STATIC ),
new dynitem( "BOSS4", DVPTR(BOSS4), BOSS4__STATIC ),
new dynitem( "BOSS4STAYPUT", DVPTR(BOSS4STAYPUT), BOSS4STAYPUT__STATIC ),
new dynitem( "FEM10", DVPTR(FEM10), FEM10__STATIC ),
new dynitem( "TOUGHGAL", DVPTR(TOUGHGAL), TOUGHGAL__STATIC ),
new dynitem( "MAN", DVPTR(MAN), MAN__STATIC ),
new dynitem( "MAN2", DVPTR(MAN2), MAN2__STATIC ),
new dynitem( "WOMAN", DVPTR(WOMAN), WOMAN__STATIC ),
new dynitem( "PLEASEWAIT", DVPTR(PLEASEWAIT), PLEASEWAIT__STATIC ),
new dynitem( "NATURALLIGHTNING", DVPTR(NATURALLIGHTNING), NATURALLIGHTNING__STATIC ),
new dynitem( "WEATHERWARN", DVPTR(WEATHERWARN), WEATHERWARN__STATIC ),
new dynitem( "DUKETAG", DVPTR(DUKETAG), DUKETAG__STATIC ),
new dynitem( "SIGN1", DVPTR(SIGN1), SIGN1__STATIC ),
new dynitem( "SIGN2", DVPTR(SIGN2), SIGN2__STATIC ),
new dynitem( "JURYGUY", DVPTR(JURYGUY), JURYGUY__STATIC ),
new dynitem( "RESERVEDSLOT1", DVPTR(RESERVEDSLOT1), RESERVEDSLOT1__STATIC ),
new dynitem( "RESERVEDSLOT2", DVPTR(RESERVEDSLOT2), RESERVEDSLOT2__STATIC ),
new dynitem( "RESERVEDSLOT3", DVPTR(RESERVEDSLOT3), RESERVEDSLOT3__STATIC ),
new dynitem( "RESERVEDSLOT4", DVPTR(RESERVEDSLOT4), RESERVEDSLOT4__STATIC ),
new dynitem( "RESERVEDSLOT5", DVPTR(RESERVEDSLOT5), RESERVEDSLOT5__STATIC ),
new dynitem( "RESERVEDSLOT6", DVPTR(RESERVEDSLOT6), RESERVEDSLOT6__STATIC ),
new dynitem( "RESERVEDSLOT7", DVPTR(RESERVEDSLOT7), RESERVEDSLOT7__STATIC ),
new dynitem( "RESERVEDSLOT8", DVPTR(RESERVEDSLOT8), RESERVEDSLOT8__STATIC ),
new dynitem( "RESERVEDSLOT9", DVPTR(RESERVEDSLOT9), RESERVEDSLOT9__STATIC ),
new dynitem( "RESERVEDSLOT10", DVPTR(RESERVEDSLOT10), RESERVEDSLOT10__STATIC ),
new dynitem( "RESERVEDSLOT11", DVPTR(RESERVEDSLOT11), RESERVEDSLOT11__STATIC ),
new dynitem( "RESERVEDSLOT12", DVPTR(RESERVEDSLOT12), RESERVEDSLOT12__STATIC ),
new dynitem( null, null, -1 ),
];

//#ifdef DYNTILEREMAP_ENABLE

var SECTOREFFECTOR = SECTOREFFECTOR__STATIC;
var ACTIVATOR = ACTIVATOR__STATIC;
var TOUCHPLATE = TOUCHPLATE__STATIC;
var ACTIVATORLOCKED = ACTIVATORLOCKED__STATIC;
var MUSICANDSFX = MUSICANDSFX__STATIC;
var LOCATORS = LOCATORS__STATIC;
var CYCLER = CYCLER__STATIC;
var MASTERSWITCH = MASTERSWITCH__STATIC;
var RESPAWN = RESPAWN__STATIC;
var GPSPEED = GPSPEED__STATIC;
var FOF = FOF__STATIC;
var ARROW = ARROW__STATIC;
var FIRSTGUNSPRITE = FIRSTGUNSPRITE__STATIC;
var CHAINGUNSPRITE = CHAINGUNSPRITE__STATIC;
var RPGSPRITE = RPGSPRITE__STATIC;
var FREEZESPRITE = FREEZESPRITE__STATIC;
var SHRINKERSPRITE = SHRINKERSPRITE__STATIC;
var HEAVYHBOMB = HEAVYHBOMB__STATIC;
var TRIPBOMBSPRITE = TRIPBOMBSPRITE__STATIC;
var SHOTGUNSPRITE = SHOTGUNSPRITE__STATIC;
var DEVISTATORSPRITE = DEVISTATORSPRITE__STATIC;
var HEALTHBOX = HEALTHBOX__STATIC;
var AMMOBOX = AMMOBOX__STATIC;
var GROWSPRITEICON = GROWSPRITEICON__STATIC;
var INVENTORYBOX = INVENTORYBOX__STATIC;
var FREEZEAMMO = FREEZEAMMO__STATIC;
var AMMO = AMMO__STATIC;
var BATTERYAMMO = BATTERYAMMO__STATIC;
var DEVISTATORAMMO = DEVISTATORAMMO__STATIC;
var RPGAMMO = RPGAMMO__STATIC;
var GROWAMMO = GROWAMMO__STATIC;
var CRYSTALAMMO = CRYSTALAMMO__STATIC;
var HBOMBAMMO = HBOMBAMMO__STATIC;
var AMMOLOTS = AMMOLOTS__STATIC;
var SHOTGUNAMMO = SHOTGUNAMMO__STATIC;
var COLA = COLA__STATIC;
var SIXPAK = SIXPAK__STATIC;
var FIRSTAID = FIRSTAID__STATIC;
var SHIELD = SHIELD__STATIC;
var STEROIDS = STEROIDS__STATIC;
var AIRTANK = AIRTANK__STATIC;
var JETPACK = JETPACK__STATIC;
var HEATSENSOR = HEATSENSOR__STATIC;
var ACCESSCARD = ACCESSCARD__STATIC;
var BOOTS = BOOTS__STATIC;
var MIRRORBROKE = MIRRORBROKE__STATIC;
var CLOUDYOCEAN = CLOUDYOCEAN__STATIC;
var CLOUDYSKIES = CLOUDYSKIES__STATIC;
var MOONSKY1 = MOONSKY1__STATIC;
var MOONSKY2 = MOONSKY2__STATIC;
var MOONSKY3 = MOONSKY3__STATIC;
var MOONSKY4 = MOONSKY4__STATIC;
var BIGORBIT1 = BIGORBIT1__STATIC;
var BIGORBIT2 = BIGORBIT2__STATIC;
var BIGORBIT3 = BIGORBIT3__STATIC;
var BIGORBIT4 = BIGORBIT4__STATIC;
var BIGORBIT5 = BIGORBIT5__STATIC;
var LA = LA__STATIC;
var REDSKY1 = REDSKY1__STATIC;
var REDSKY2 = REDSKY2__STATIC;
var ATOMICHEALTH = ATOMICHEALTH__STATIC;
var TECHLIGHT2 = TECHLIGHT2__STATIC;
var TECHLIGHTBUST2 = TECHLIGHTBUST2__STATIC;
var TECHLIGHT4 = TECHLIGHT4__STATIC;
var TECHLIGHTBUST4 = TECHLIGHTBUST4__STATIC;
var WALLLIGHT4 = WALLLIGHT4__STATIC;
var WALLLIGHTBUST4 = WALLLIGHTBUST4__STATIC;
var ACCESSSWITCH = ACCESSSWITCH__STATIC;
var SLOTDOOR = SLOTDOOR__STATIC;
var LIGHTSWITCH = LIGHTSWITCH__STATIC;
var SPACEDOORSWITCH = SPACEDOORSWITCH__STATIC;
var SPACELIGHTSWITCH = SPACELIGHTSWITCH__STATIC;
var FRANKENSTINESWITCH = FRANKENSTINESWITCH__STATIC;
var NUKEBUTTON = NUKEBUTTON__STATIC;
var MULTISWITCH = MULTISWITCH__STATIC;
var DOORTILE5 = DOORTILE5__STATIC;
var DOORTILE6 = DOORTILE6__STATIC;
var DOORTILE1 = DOORTILE1__STATIC;
var DOORTILE2 = DOORTILE2__STATIC;
var DOORTILE3 = DOORTILE3__STATIC;
var DOORTILE4 = DOORTILE4__STATIC;
var DOORTILE7 = DOORTILE7__STATIC;
var DOORTILE8 = DOORTILE8__STATIC;
var DOORTILE9 = DOORTILE9__STATIC;
var DOORTILE10 = DOORTILE10__STATIC;
var DOORSHOCK = DOORSHOCK__STATIC;
var DIPSWITCH = DIPSWITCH__STATIC;
var DIPSWITCH2 = DIPSWITCH2__STATIC;
var TECHSWITCH = TECHSWITCH__STATIC;
var DIPSWITCH3 = DIPSWITCH3__STATIC;
var ACCESSSWITCH2 = ACCESSSWITCH2__STATIC;
var REFLECTWATERTILE = REFLECTWATERTILE__STATIC;
var FLOORSLIME = FLOORSLIME__STATIC;
var BIGFORCE = BIGFORCE__STATIC;
var EPISODE = EPISODE__STATIC;
var MASKWALL9 = MASKWALL9__STATIC;
var W_LIGHT = W_LIGHT__STATIC;
var SCREENBREAK1 = SCREENBREAK1__STATIC;
var SCREENBREAK2 = SCREENBREAK2__STATIC;
var SCREENBREAK3 = SCREENBREAK3__STATIC;
var SCREENBREAK4 = SCREENBREAK4__STATIC;
var SCREENBREAK5 = SCREENBREAK5__STATIC;
var SCREENBREAK6 = SCREENBREAK6__STATIC;
var SCREENBREAK7 = SCREENBREAK7__STATIC;
var SCREENBREAK8 = SCREENBREAK8__STATIC;
var SCREENBREAK9 = SCREENBREAK9__STATIC;
var SCREENBREAK10 = SCREENBREAK10__STATIC;
var SCREENBREAK11 = SCREENBREAK11__STATIC;
var SCREENBREAK12 = SCREENBREAK12__STATIC;
var SCREENBREAK13 = SCREENBREAK13__STATIC;
var MASKWALL1 = MASKWALL1__STATIC;
var W_TECHWALL1 = W_TECHWALL1__STATIC;
var W_TECHWALL2 = W_TECHWALL2__STATIC;
var W_TECHWALL15 = W_TECHWALL15__STATIC;
var W_TECHWALL3 = W_TECHWALL3__STATIC;
var W_TECHWALL4 = W_TECHWALL4__STATIC;
var W_TECHWALL10 = W_TECHWALL10__STATIC;
var W_TECHWALL16 = W_TECHWALL16__STATIC;
var WATERTILE2 = WATERTILE2__STATIC;
var BPANNEL1 = BPANNEL1__STATIC;
var PANNEL1 = PANNEL1__STATIC;
var PANNEL2 = PANNEL2__STATIC;
var WATERTILE = WATERTILE__STATIC;
var STATIC = STATIC__STATIC;
var W_SCREENBREAK = W_SCREENBREAK__STATIC;
var W_HITTECHWALL3 = W_HITTECHWALL3__STATIC;
var W_HITTECHWALL4 = W_HITTECHWALL4__STATIC;
var W_HITTECHWALL2 = W_HITTECHWALL2__STATIC;
var W_HITTECHWALL1 = W_HITTECHWALL1__STATIC;
var MASKWALL10 = MASKWALL10__STATIC;
var MASKWALL11 = MASKWALL11__STATIC;
var DOORTILE22 = DOORTILE22__STATIC;
var FANSPRITE = FANSPRITE__STATIC;
var FANSPRITEBROKE = FANSPRITEBROKE__STATIC;
var FANSHADOW = FANSHADOW__STATIC;
var FANSHADOWBROKE = FANSHADOWBROKE__STATIC;
var DOORTILE18 = DOORTILE18__STATIC;
var DOORTILE19 = DOORTILE19__STATIC;
var DOORTILE20 = DOORTILE20__STATIC;
var SATELLITE = SATELLITE__STATIC;
var VIEWSCREEN2 = VIEWSCREEN2__STATIC;
var VIEWSCREENBROKE = VIEWSCREENBROKE__STATIC;
var VIEWSCREEN = VIEWSCREEN__STATIC;
var GLASS = GLASS__STATIC;
var GLASS2 = GLASS2__STATIC;
var STAINGLASS1 = STAINGLASS1__STATIC;
var MASKWALL5 = MASKWALL5__STATIC;
var SATELITE = SATELITE__STATIC;
var FUELPOD = FUELPOD__STATIC;
var SLIMEPIPE = SLIMEPIPE__STATIC;
var CRACK1 = CRACK1__STATIC;
var CRACK2 = CRACK2__STATIC;
var CRACK3 = CRACK3__STATIC;
var CRACK4 = CRACK4__STATIC;
var FOOTPRINTS = FOOTPRINTS__STATIC;
var DOMELITE = DOMELITE__STATIC;
var CAMERAPOLE = CAMERAPOLE__STATIC;
var CHAIR1 = CHAIR1__STATIC;
var CHAIR2 = CHAIR2__STATIC;
var BROKENCHAIR = BROKENCHAIR__STATIC;
var MIRROR = MIRROR__STATIC;
var WATERFOUNTAIN = WATERFOUNTAIN__STATIC;
var WATERFOUNTAINBROKE = WATERFOUNTAINBROKE__STATIC;
var FEMMAG1 = FEMMAG1__STATIC;
var TOILET = TOILET__STATIC;
var STALL = STALL__STATIC;
var STALLBROKE = STALLBROKE__STATIC;
var FEMMAG2 = FEMMAG2__STATIC;
var REACTOR2 = REACTOR2__STATIC;
var REACTOR2BURNT = REACTOR2BURNT__STATIC;
var REACTOR2SPARK = REACTOR2SPARK__STATIC;
var GRATE1 = GRATE1__STATIC;
var BGRATE1 = BGRATE1__STATIC;
var SOLARPANNEL = SOLARPANNEL__STATIC;
var NAKED1 = NAKED1__STATIC;
var ANTENNA = ANTENNA__STATIC;
var MASKWALL12 = MASKWALL12__STATIC;
var TOILETBROKE = TOILETBROKE__STATIC;
var PIPE2 = PIPE2__STATIC;
var PIPE1B = PIPE1B__STATIC;
var PIPE3 = PIPE3__STATIC;
var PIPE1 = PIPE1__STATIC;
var CAMERA1 = CAMERA1__STATIC;
var BRICK = BRICK__STATIC;
var SPLINTERWOOD = SPLINTERWOOD__STATIC;
var PIPE2B = PIPE2B__STATIC;
var BOLT1 = BOLT1__STATIC;
var W_NUMBERS = W_NUMBERS__STATIC;
var WATERDRIP = WATERDRIP__STATIC;
var WATERBUBBLE = WATERBUBBLE__STATIC;
var WATERBUBBLEMAKER = WATERBUBBLEMAKER__STATIC;
var W_FORCEFIELD = W_FORCEFIELD__STATIC;
var VACUUM = VACUUM__STATIC;
var FOOTPRINTS2 = FOOTPRINTS2__STATIC;
var FOOTPRINTS3 = FOOTPRINTS3__STATIC;
var FOOTPRINTS4 = FOOTPRINTS4__STATIC;
var EGG = EGG__STATIC;
var SCALE = SCALE__STATIC;
var CHAIR3 = CHAIR3__STATIC;
var CAMERALIGHT = CAMERALIGHT__STATIC;
var MOVIECAMERA = MOVIECAMERA__STATIC;
var IVUNIT = IVUNIT__STATIC;
var POT1 = POT1__STATIC;
var POT2 = POT2__STATIC;
var POT3 = POT3__STATIC;
var PIPE3B = PIPE3B__STATIC;
var WALLLIGHT3 = WALLLIGHT3__STATIC;
var WALLLIGHTBUST3 = WALLLIGHTBUST3__STATIC;
var WALLLIGHT1 = WALLLIGHT1__STATIC;
var WALLLIGHTBUST1 = WALLLIGHTBUST1__STATIC;
var WALLLIGHT2 = WALLLIGHT2__STATIC;
var WALLLIGHTBUST2 = WALLLIGHTBUST2__STATIC;
var LIGHTSWITCH2 = LIGHTSWITCH2__STATIC;
var WAITTOBESEATED = WAITTOBESEATED__STATIC;
var DOORTILE14 = DOORTILE14__STATIC;
var STATUE = STATUE__STATIC;
var MIKE = MIKE__STATIC;
var VASE = VASE__STATIC;
var SUSHIPLATE1 = SUSHIPLATE1__STATIC;
var SUSHIPLATE2 = SUSHIPLATE2__STATIC;
var SUSHIPLATE3 = SUSHIPLATE3__STATIC;
var SUSHIPLATE4 = SUSHIPLATE4__STATIC;
var DOORTILE16 = DOORTILE16__STATIC;
var SUSHIPLATE5 = SUSHIPLATE5__STATIC;
var OJ = OJ__STATIC;
var MASKWALL13 = MASKWALL13__STATIC;
var HURTRAIL = HURTRAIL__STATIC;
var POWERSWITCH1 = POWERSWITCH1__STATIC;
var LOCKSWITCH1 = LOCKSWITCH1__STATIC;
var POWERSWITCH2 = POWERSWITCH2__STATIC;
var ATM = ATM__STATIC;
var STATUEFLASH = STATUEFLASH__STATIC;
var ATMBROKE = ATMBROKE__STATIC;
var BIGHOLE2 = BIGHOLE2__STATIC;
var STRIPEBALL = STRIPEBALL__STATIC;
var QUEBALL = QUEBALL__STATIC;
var POCKET = POCKET__STATIC;
var WOODENHORSE = WOODENHORSE__STATIC;
var TREE1 = TREE1__STATIC;
var TREE2 = TREE2__STATIC;
var CACTUS = CACTUS__STATIC;
var MASKWALL2 = MASKWALL2__STATIC;
var MASKWALL3 = MASKWALL3__STATIC;
var MASKWALL4 = MASKWALL4__STATIC;
var FIREEXT = FIREEXT__STATIC;
var TOILETWATER = TOILETWATER__STATIC;
var NEON1 = NEON1__STATIC;
var NEON2 = NEON2__STATIC;
var CACTUSBROKE = CACTUSBROKE__STATIC;
var BOUNCEMINE = BOUNCEMINE__STATIC;
var BROKEFIREHYDRENT = BROKEFIREHYDRENT__STATIC;
var BOX = BOX__STATIC;
var BULLETHOLE = BULLETHOLE__STATIC;
var BOTTLE1 = BOTTLE1__STATIC;
var BOTTLE2 = BOTTLE2__STATIC;
var BOTTLE3 = BOTTLE3__STATIC;
var BOTTLE4 = BOTTLE4__STATIC;
var FEMPIC5 = FEMPIC5__STATIC;
var FEMPIC6 = FEMPIC6__STATIC;
var FEMPIC7 = FEMPIC7__STATIC;
var HYDROPLANT = HYDROPLANT__STATIC;
var OCEANSPRITE1 = OCEANSPRITE1__STATIC;
var OCEANSPRITE2 = OCEANSPRITE2__STATIC;
var OCEANSPRITE3 = OCEANSPRITE3__STATIC;
var OCEANSPRITE4 = OCEANSPRITE4__STATIC;
var OCEANSPRITE5 = OCEANSPRITE5__STATIC;
var GENERICPOLE = GENERICPOLE__STATIC;
var CONE = CONE__STATIC;
var HANGLIGHT = HANGLIGHT__STATIC;
var HYDRENT = HYDRENT__STATIC;
var MASKWALL14 = MASKWALL14__STATIC;
var TIRE = TIRE__STATIC;
var PIPE5 = PIPE5__STATIC;
var PIPE6 = PIPE6__STATIC;
var PIPE4 = PIPE4__STATIC;
var PIPE4B = PIPE4B__STATIC;
var BROKEHYDROPLANT = BROKEHYDROPLANT__STATIC;
var PIPE5B = PIPE5B__STATIC;
var NEON3 = NEON3__STATIC;
var NEON4 = NEON4__STATIC;
var NEON5 = NEON5__STATIC;
var BOTTLE5 = BOTTLE5__STATIC;
var BOTTLE6 = BOTTLE6__STATIC;
var BOTTLE8 = BOTTLE8__STATIC;
var SPOTLITE = SPOTLITE__STATIC;
var HANGOOZ = HANGOOZ__STATIC;
var MASKWALL15 = MASKWALL15__STATIC;
var BOTTLE7 = BOTTLE7__STATIC;
var HORSEONSIDE = HORSEONSIDE__STATIC;
var GLASSPIECES = GLASSPIECES__STATIC;
var HORSELITE = HORSELITE__STATIC;
var DONUTS = DONUTS__STATIC;
var NEON6 = NEON6__STATIC;
var MASKWALL6 = MASKWALL6__STATIC;
var CLOCK = CLOCK__STATIC;
var RUBBERCAN = RUBBERCAN__STATIC;
var BROKENCLOCK = BROKENCLOCK__STATIC;
var PLUG = PLUG__STATIC;
var OOZFILTER = OOZFILTER__STATIC;
var FLOORPLASMA = FLOORPLASMA__STATIC;
var REACTOR = REACTOR__STATIC;
var REACTORSPARK = REACTORSPARK__STATIC;
var REACTORBURNT = REACTORBURNT__STATIC;
var DOORTILE15 = DOORTILE15__STATIC;
var HANDSWITCH = HANDSWITCH__STATIC;
var CIRCLEPANNEL = CIRCLEPANNEL__STATIC;
var CIRCLEPANNELBROKE = CIRCLEPANNELBROKE__STATIC;
var PULLSWITCH = PULLSWITCH__STATIC;
var MASKWALL8 = MASKWALL8__STATIC;
var BIGHOLE = BIGHOLE__STATIC;
var ALIENSWITCH = ALIENSWITCH__STATIC;
var DOORTILE21 = DOORTILE21__STATIC;
var HANDPRINTSWITCH = HANDPRINTSWITCH__STATIC;
var BOTTLE10 = BOTTLE10__STATIC;
var BOTTLE11 = BOTTLE11__STATIC;
var BOTTLE12 = BOTTLE12__STATIC;
var BOTTLE13 = BOTTLE13__STATIC;
var BOTTLE14 = BOTTLE14__STATIC;
var BOTTLE15 = BOTTLE15__STATIC;
var BOTTLE16 = BOTTLE16__STATIC;
var BOTTLE17 = BOTTLE17__STATIC;
var BOTTLE18 = BOTTLE18__STATIC;
var BOTTLE19 = BOTTLE19__STATIC;
var DOORTILE17 = DOORTILE17__STATIC;
var MASKWALL7 = MASKWALL7__STATIC;
var JAILBARBREAK = JAILBARBREAK__STATIC;
var DOORTILE11 = DOORTILE11__STATIC;
var DOORTILE12 = DOORTILE12__STATIC;
var VENDMACHINE = VENDMACHINE__STATIC;
var VENDMACHINEBROKE = VENDMACHINEBROKE__STATIC;
var COLAMACHINE = COLAMACHINE__STATIC;
var COLAMACHINEBROKE = COLAMACHINEBROKE__STATIC;
var CRANEPOLE = CRANEPOLE__STATIC;
var CRANE = CRANE__STATIC;
var BARBROKE = BARBROKE__STATIC;
var BLOODPOOL = BLOODPOOL__STATIC;
var NUKEBARREL = NUKEBARREL__STATIC;
var NUKEBARRELDENTED = NUKEBARRELDENTED__STATIC;
var NUKEBARRELLEAKED = NUKEBARRELLEAKED__STATIC;
var CANWITHSOMETHING = CANWITHSOMETHING__STATIC;
var MONEY = MONEY__STATIC;
var BANNER = BANNER__STATIC;
var EXPLODINGBARREL = EXPLODINGBARREL__STATIC;
var EXPLODINGBARREL2 = EXPLODINGBARREL2__STATIC;
var FIREBARREL = FIREBARREL__STATIC;
var SEENINE = SEENINE__STATIC;
var SEENINEDEAD = SEENINEDEAD__STATIC;
var STEAM = STEAM__STATIC;
var CEILINGSTEAM = CEILINGSTEAM__STATIC;
var PIPE6B = PIPE6B__STATIC;
var TRANSPORTERBEAM = TRANSPORTERBEAM__STATIC;
var RAT = RAT__STATIC;
var TRASH = TRASH__STATIC;
var FEMPIC1 = FEMPIC1__STATIC;
var FEMPIC2 = FEMPIC2__STATIC;
var BLANKSCREEN = BLANKSCREEN__STATIC;
var PODFEM1 = PODFEM1__STATIC;
var FEMPIC3 = FEMPIC3__STATIC;
var FEMPIC4 = FEMPIC4__STATIC;
var FEM1 = FEM1__STATIC;
var FEM2 = FEM2__STATIC;
var FEM3 = FEM3__STATIC;
var FEM5 = FEM5__STATIC;
var BLOODYPOLE = BLOODYPOLE__STATIC;
var FEM4 = FEM4__STATIC;
var FEM6 = FEM6__STATIC;
var FEM6PAD = FEM6PAD__STATIC;
var FEM8 = FEM8__STATIC;
var HELECOPT = HELECOPT__STATIC;
var FETUSJIB = FETUSJIB__STATIC;
var HOLODUKE = HOLODUKE__STATIC;
var SPACEMARINE = SPACEMARINE__STATIC;
var INDY = INDY__STATIC;
var FETUS = FETUS__STATIC;
var FETUSBROKE = FETUSBROKE__STATIC;
var MONK = MONK__STATIC;
var LUKE = LUKE__STATIC;
var COOLEXPLOSION1 = COOLEXPLOSION1__STATIC;
var WATERSPLASH2 = WATERSPLASH2__STATIC;
var FIREVASE = FIREVASE__STATIC;
var SCRATCH = SCRATCH__STATIC;
var FEM7 = FEM7__STATIC;
var APLAYERTOP = APLAYERTOP__STATIC;
var APLAYER = APLAYER__STATIC;
var PLAYERONWATER = PLAYERONWATER__STATIC;
var DUKELYINGDEAD = DUKELYINGDEAD__STATIC;
var DUKETORSO = DUKETORSO__STATIC;
var DUKEGUN = DUKEGUN__STATIC;
var DUKELEG = DUKELEG__STATIC;
var SHARK = SHARK__STATIC;
var BLOOD = BLOOD__STATIC;
var FIRELASER = FIRELASER__STATIC;
var TRANSPORTERSTAR = TRANSPORTERSTAR__STATIC;
var SPIT = SPIT__STATIC;
var LOOGIE = LOOGIE__STATIC;
var FIST = FIST__STATIC;
var FREEZEBLAST = FREEZEBLAST__STATIC;
var DEVISTATORBLAST = DEVISTATORBLAST__STATIC;
var SHRINKSPARK = SHRINKSPARK__STATIC;
var TONGUE = TONGUE__STATIC;
var MORTER = MORTER__STATIC;
var SHRINKEREXPLOSION = SHRINKEREXPLOSION__STATIC;
var RADIUSEXPLOSION = RADIUSEXPLOSION__STATIC;
var FORCERIPPLE = FORCERIPPLE__STATIC;
var LIZTROOP = LIZTROOP__STATIC;
var LIZTROOPRUNNING = LIZTROOPRUNNING__STATIC;
var LIZTROOPSTAYPUT = LIZTROOPSTAYPUT__STATIC;
var LIZTOP = LIZTOP__STATIC;
var LIZTROOPSHOOT = LIZTROOPSHOOT__STATIC;
var LIZTROOPJETPACK = LIZTROOPJETPACK__STATIC;
var LIZTROOPDSPRITE = LIZTROOPDSPRITE__STATIC;
var LIZTROOPONTOILET = LIZTROOPONTOILET__STATIC;
var LIZTROOPJUSTSIT = LIZTROOPJUSTSIT__STATIC;
var LIZTROOPDUCKING = LIZTROOPDUCKING__STATIC;
var HEADJIB1 = HEADJIB1__STATIC;
var ARMJIB1 = ARMJIB1__STATIC;
var LEGJIB1 = LEGJIB1__STATIC;
var CANNONBALL = CANNONBALL__STATIC;
var OCTABRAIN = OCTABRAIN__STATIC;
var OCTABRAINSTAYPUT = OCTABRAINSTAYPUT__STATIC;
var OCTATOP = OCTATOP__STATIC;
var OCTADEADSPRITE = OCTADEADSPRITE__STATIC;
var INNERJAW = INNERJAW__STATIC;
var DRONE = DRONE__STATIC;
var EXPLOSION2 = EXPLOSION2__STATIC;
var COMMANDER = COMMANDER__STATIC;
var COMMANDERSTAYPUT = COMMANDERSTAYPUT__STATIC;
var RECON = RECON__STATIC;
var TANK = TANK__STATIC;
var PIGCOP = PIGCOP__STATIC;
var PIGCOPSTAYPUT = PIGCOPSTAYPUT__STATIC;
var PIGCOPDIVE = PIGCOPDIVE__STATIC;
var PIGCOPDEADSPRITE = PIGCOPDEADSPRITE__STATIC;
var PIGTOP = PIGTOP__STATIC;
var LIZMAN = LIZMAN__STATIC;
var LIZMANSTAYPUT = LIZMANSTAYPUT__STATIC;
var LIZMANSPITTING = LIZMANSPITTING__STATIC;
var LIZMANFEEDING = LIZMANFEEDING__STATIC;
var LIZMANJUMP = LIZMANJUMP__STATIC;
var LIZMANDEADSPRITE = LIZMANDEADSPRITE__STATIC;
var FECES = FECES__STATIC;
var LIZMANHEAD1 = LIZMANHEAD1__STATIC;
var LIZMANARM1 = LIZMANARM1__STATIC;
var LIZMANLEG1 = LIZMANLEG1__STATIC;
var EXPLOSION2BOT = EXPLOSION2BOT__STATIC;
var USERWEAPON = USERWEAPON__STATIC;
var HEADERBAR = HEADERBAR__STATIC;
var JIBS1 = JIBS1__STATIC;
var JIBS2 = JIBS2__STATIC;
var JIBS3 = JIBS3__STATIC;
var JIBS4 = JIBS4__STATIC;
var JIBS5 = JIBS5__STATIC;
var BURNING = BURNING__STATIC;
var FIRE = FIRE__STATIC;
var JIBS6 = JIBS6__STATIC;
var BLOODSPLAT1 = BLOODSPLAT1__STATIC;
var BLOODSPLAT3 = BLOODSPLAT3__STATIC;
var BLOODSPLAT2 = BLOODSPLAT2__STATIC;
var BLOODSPLAT4 = BLOODSPLAT4__STATIC;
var OOZ = OOZ__STATIC;
var OOZ2 = OOZ2__STATIC;
var WALLBLOOD1 = WALLBLOOD1__STATIC;
var WALLBLOOD2 = WALLBLOOD2__STATIC;
var WALLBLOOD3 = WALLBLOOD3__STATIC;
var WALLBLOOD4 = WALLBLOOD4__STATIC;
var WALLBLOOD5 = WALLBLOOD5__STATIC;
var WALLBLOOD6 = WALLBLOOD6__STATIC;
var WALLBLOOD7 = WALLBLOOD7__STATIC;
var WALLBLOOD8 = WALLBLOOD8__STATIC;
var BURNING2 = BURNING2__STATIC;
var FIRE2 = FIRE2__STATIC;
var CRACKKNUCKLES = CRACKKNUCKLES__STATIC;
var SMALLSMOKE = SMALLSMOKE__STATIC;
var SMALLSMOKEMAKER = SMALLSMOKEMAKER__STATIC;
var FLOORFLAME = FLOORFLAME__STATIC;
var ROTATEGUN = ROTATEGUN__STATIC;
var GREENSLIME = GREENSLIME__STATIC;
var WATERDRIPSPLASH = WATERDRIPSPLASH__STATIC;
var SCRAP6 = SCRAP6__STATIC;
var SCRAP1 = SCRAP1__STATIC;
var SCRAP2 = SCRAP2__STATIC;
var SCRAP3 = SCRAP3__STATIC;
var SCRAP4 = SCRAP4__STATIC;
var SCRAP5 = SCRAP5__STATIC;
var ORGANTIC = ORGANTIC__STATIC;
var BETAVERSION = BETAVERSION__STATIC;
var PLAYERISHERE = PLAYERISHERE__STATIC;
var PLAYERWASHERE = PLAYERWASHERE__STATIC;
var SELECTDIR = SELECTDIR__STATIC;
var F1HELP = F1HELP__STATIC;
var NOTCHON = NOTCHON__STATIC;
var NOTCHOFF = NOTCHOFF__STATIC;
var GROWSPARK = GROWSPARK__STATIC;
var DUKEICON = DUKEICON__STATIC;
var BADGUYICON = BADGUYICON__STATIC;
var FOODICON = FOODICON__STATIC;
var GETICON = GETICON__STATIC;
var MENUSCREEN = MENUSCREEN__STATIC;
var MENUBAR = MENUBAR__STATIC;
var KILLSICON = KILLSICON__STATIC;
var FIRSTAID_ICON = FIRSTAID_ICON__STATIC;
var HEAT_ICON = HEAT_ICON__STATIC;
var BOTTOMSTATUSBAR = BOTTOMSTATUSBAR__STATIC;
var BOOT_ICON = BOOT_ICON__STATIC;
var FRAGBAR = FRAGBAR__STATIC;
var JETPACK_ICON = JETPACK_ICON__STATIC;
var AIRTANK_ICON = AIRTANK_ICON__STATIC;
var STEROIDS_ICON = STEROIDS_ICON__STATIC;
var HOLODUKE_ICON = HOLODUKE_ICON__STATIC;
var ACCESS_ICON = ACCESS_ICON__STATIC;
var DIGITALNUM = DIGITALNUM__STATIC;
var DUKECAR = DUKECAR__STATIC;
var CAMCORNER = CAMCORNER__STATIC;
var CAMLIGHT = CAMLIGHT__STATIC;
var LOGO = LOGO__STATIC;
var TITLE = TITLE__STATIC;
var NUKEWARNINGICON = NUKEWARNINGICON__STATIC;
var MOUSECURSOR = MOUSECURSOR__STATIC;
var SLIDEBAR = SLIDEBAR__STATIC;
var DREALMS = DREALMS__STATIC;
var BETASCREEN = BETASCREEN__STATIC;
var WINDOWBORDER1 = WINDOWBORDER1__STATIC;
var TEXTBOX = TEXTBOX__STATIC;
var WINDOWBORDER2 = WINDOWBORDER2__STATIC;
var DUKENUKEM = DUKENUKEM__STATIC;
var THREEDEE = THREEDEE__STATIC;
var INGAMEDUKETHREEDEE = INGAMEDUKETHREEDEE__STATIC;
var TENSCREEN = TENSCREEN__STATIC;
var PLUTOPAKSPRITE = PLUTOPAKSPRITE__STATIC;
var DEVISTATOR = DEVISTATOR__STATIC;
var KNEE = KNEE__STATIC;
var CROSSHAIR = CROSSHAIR__STATIC;
var FIRSTGUN = FIRSTGUN__STATIC;
var FIRSTGUNRELOAD = FIRSTGUNRELOAD__STATIC;
var FALLINGCLIP = FALLINGCLIP__STATIC;
var CLIPINHAND = CLIPINHAND__STATIC;
var HAND = HAND__STATIC;
var SHELL = SHELL__STATIC;
var SHOTGUNSHELL = SHOTGUNSHELL__STATIC;
var CHAINGUN = CHAINGUN__STATIC;
var RPGGUN = RPGGUN__STATIC;
var RPGMUZZLEFLASH = RPGMUZZLEFLASH__STATIC;
var FREEZE = FREEZE__STATIC;
var CATLITE = CATLITE__STATIC;
var SHRINKER = SHRINKER__STATIC;
var HANDHOLDINGLASER = HANDHOLDINGLASER__STATIC;
var TRIPBOMB = TRIPBOMB__STATIC;
var LASERLINE = LASERLINE__STATIC;
var HANDHOLDINGACCESS = HANDHOLDINGACCESS__STATIC;
var HANDREMOTE = HANDREMOTE__STATIC;
var HANDTHROW = HANDTHROW__STATIC;
var TIP = TIP__STATIC;
var GLAIR = GLAIR__STATIC;
var SCUBAMASK = SCUBAMASK__STATIC;
var SPACEMASK = SPACEMASK__STATIC;
var FORCESPHERE = FORCESPHERE__STATIC;
var SHOTSPARK1 = SHOTSPARK1__STATIC;
var RPG = RPG__STATIC;
var LASERSITE = LASERSITE__STATIC;
var SHOTGUN = SHOTGUN__STATIC;
var BOSS1 = BOSS1__STATIC;
var BOSS1STAYPUT = BOSS1STAYPUT__STATIC;
var BOSS1SHOOT = BOSS1SHOOT__STATIC;
var BOSS1LOB = BOSS1LOB__STATIC;
var BOSSTOP = BOSSTOP__STATIC;
var BOSS2 = BOSS2__STATIC;
var BOSS3 = BOSS3__STATIC;
var SPINNINGNUKEICON = SPINNINGNUKEICON__STATIC;
var BIGFNTCURSOR = BIGFNTCURSOR__STATIC;
var SMALLFNTCURSOR = SMALLFNTCURSOR__STATIC;
var STARTALPHANUM = STARTALPHANUM__STATIC;
var ENDALPHANUM = ENDALPHANUM__STATIC;
var BIGALPHANUM = BIGALPHANUM__STATIC;
var BIGPERIOD = BIGPERIOD__STATIC;
var BIGCOMMA = BIGCOMMA__STATIC;
// "BIGX" clashes on the Wii?
var BIGX_ = BIGX__STATIC;
var BIGQ = BIGQ__STATIC;
var BIGSEMI = BIGSEMI__STATIC;
var BIGCOLIN = BIGCOLIN__STATIC;
var THREEBYFIVE = THREEBYFIVE__STATIC;
var BIGAPPOS = BIGAPPOS__STATIC;
var BLANK = BLANK__STATIC;
var MINIFONT = MINIFONT__STATIC;
var BUTTON1 = BUTTON1__STATIC;
var GLASS3 = GLASS3__STATIC;
var RESPAWNMARKERRED = RESPAWNMARKERRED__STATIC;
var RESPAWNMARKERYELLOW = RESPAWNMARKERYELLOW__STATIC;
var RESPAWNMARKERGREEN = RESPAWNMARKERGREEN__STATIC;
var BONUSSCREEN = BONUSSCREEN__STATIC;
var VIEWBORDER = VIEWBORDER__STATIC;
var VICTORY1 = VICTORY1__STATIC;
var ORDERING = ORDERING__STATIC;
var TEXTSTORY = TEXTSTORY__STATIC;
var LOADSCREEN = LOADSCREEN__STATIC;
var BORNTOBEWILDSCREEN = BORNTOBEWILDSCREEN__STATIC;
var BLIMP = BLIMP__STATIC;
var FEM9 = FEM9__STATIC;
var FOOTPRINT = FOOTPRINT__STATIC;
var FRAMEEFFECT1_13 = FRAMEEFFECT1_13__STATIC;
var POOP = POOP__STATIC;
var FRAMEEFFECT1 = FRAMEEFFECT1__STATIC;
var PANNEL3 = PANNEL3__STATIC;
var SCREENBREAK14 = SCREENBREAK14__STATIC;
var SCREENBREAK15 = SCREENBREAK15__STATIC;
var SCREENBREAK19 = SCREENBREAK19__STATIC;
var SCREENBREAK16 = SCREENBREAK16__STATIC;
var SCREENBREAK17 = SCREENBREAK17__STATIC;
var SCREENBREAK18 = SCREENBREAK18__STATIC;
var W_TECHWALL11 = W_TECHWALL11__STATIC;
var W_TECHWALL12 = W_TECHWALL12__STATIC;
var W_TECHWALL13 = W_TECHWALL13__STATIC;
var W_TECHWALL14 = W_TECHWALL14__STATIC;
var W_TECHWALL5 = W_TECHWALL5__STATIC;
var W_TECHWALL6 = W_TECHWALL6__STATIC;
var W_TECHWALL7 = W_TECHWALL7__STATIC;
var W_TECHWALL8 = W_TECHWALL8__STATIC;
var W_TECHWALL9 = W_TECHWALL9__STATIC;
var BPANNEL3 = BPANNEL3__STATIC;
var W_HITTECHWALL16 = W_HITTECHWALL16__STATIC;
var W_HITTECHWALL10 = W_HITTECHWALL10__STATIC;
var W_HITTECHWALL15 = W_HITTECHWALL15__STATIC;
var W_MILKSHELF = W_MILKSHELF__STATIC;
var W_MILKSHELFBROKE = W_MILKSHELFBROKE__STATIC;
var PURPLELAVA = PURPLELAVA__STATIC;
var LAVABUBBLE = LAVABUBBLE__STATIC;
var DUKECUTOUT = DUKECUTOUT__STATIC;
var TARGET = TARGET__STATIC;
var GUNPOWDERBARREL = GUNPOWDERBARREL__STATIC;
var DUCK = DUCK__STATIC;
var HATRACK = HATRACK__STATIC;
var DESKLAMP = DESKLAMP__STATIC;
var COFFEEMACHINE = COFFEEMACHINE__STATIC;
var CUPS = CUPS__STATIC;
var GAVALS = GAVALS__STATIC;
var GAVALS2 = GAVALS2__STATIC;
var POLICELIGHTPOLE = POLICELIGHTPOLE__STATIC;
var FLOORBASKET = FLOORBASKET__STATIC;
var PUKE = PUKE__STATIC;
var DOORTILE23 = DOORTILE23__STATIC;
var TOPSECRET = TOPSECRET__STATIC;
var SPEAKER = SPEAKER__STATIC;
var TEDDYBEAR = TEDDYBEAR__STATIC;
var ROBOTDOG = ROBOTDOG__STATIC;
var ROBOTPIRATE = ROBOTPIRATE__STATIC;
var ROBOTMOUSE = ROBOTMOUSE__STATIC;
var MAIL = MAIL__STATIC;
var MAILBAG = MAILBAG__STATIC;
var HOTMEAT = HOTMEAT__STATIC;
var COFFEEMUG = COFFEEMUG__STATIC;
var DONUTS2 = DONUTS2__STATIC;
var TRIPODCAMERA = TRIPODCAMERA__STATIC;
var METER = METER__STATIC;
var DESKPHONE = DESKPHONE__STATIC;
var GUMBALLMACHINE = GUMBALLMACHINE__STATIC;
var GUMBALLMACHINEBROKE = GUMBALLMACHINEBROKE__STATIC;
var PAPER = PAPER__STATIC;
var MACE = MACE__STATIC;
var GENERICPOLE2 = GENERICPOLE2__STATIC;
var XXXSTACY = XXXSTACY__STATIC;
var WETFLOOR = WETFLOOR__STATIC;
var BROOM = BROOM__STATIC;
var MOP = MOP__STATIC;
var LETTER = LETTER__STATIC;
var PIRATE1A = PIRATE1A__STATIC;
var PIRATE4A = PIRATE4A__STATIC;
var PIRATE2A = PIRATE2A__STATIC;
var PIRATE5A = PIRATE5A__STATIC;
var PIRATE3A = PIRATE3A__STATIC;
var PIRATE6A = PIRATE6A__STATIC;
var PIRATEHALF = PIRATEHALF__STATIC;
var CHESTOFGOLD = CHESTOFGOLD__STATIC;
var SIDEBOLT1 = SIDEBOLT1__STATIC;
var FOODOBJECT1 = FOODOBJECT1__STATIC;
var FOODOBJECT2 = FOODOBJECT2__STATIC;
var FOODOBJECT3 = FOODOBJECT3__STATIC;
var FOODOBJECT4 = FOODOBJECT4__STATIC;
var FOODOBJECT5 = FOODOBJECT5__STATIC;
var FOODOBJECT6 = FOODOBJECT6__STATIC;
var FOODOBJECT7 = FOODOBJECT7__STATIC;
var FOODOBJECT8 = FOODOBJECT8__STATIC;
var FOODOBJECT9 = FOODOBJECT9__STATIC;
var FOODOBJECT10 = FOODOBJECT10__STATIC;
var FOODOBJECT11 = FOODOBJECT11__STATIC;
var FOODOBJECT12 = FOODOBJECT12__STATIC;
var FOODOBJECT13 = FOODOBJECT13__STATIC;
var FOODOBJECT14 = FOODOBJECT14__STATIC;
var FOODOBJECT15 = FOODOBJECT15__STATIC;
var FOODOBJECT16 = FOODOBJECT16__STATIC;
var FOODOBJECT17 = FOODOBJECT17__STATIC;
var FOODOBJECT18 = FOODOBJECT18__STATIC;
var FOODOBJECT19 = FOODOBJECT19__STATIC;
var FOODOBJECT20 = FOODOBJECT20__STATIC;
var HEADLAMP = HEADLAMP__STATIC;
var TAMPON = TAMPON__STATIC;
var SKINNEDCHICKEN = SKINNEDCHICKEN__STATIC;
var FEATHEREDCHICKEN = FEATHEREDCHICKEN__STATIC;
var ROBOTDOG2 = ROBOTDOG2__STATIC;
var JOLLYMEAL = JOLLYMEAL__STATIC;
var DUKEBURGER = DUKEBURGER__STATIC;
var SHOPPINGCART = SHOPPINGCART__STATIC;
var CANWITHSOMETHING2 = CANWITHSOMETHING2__STATIC;
var CANWITHSOMETHING3 = CANWITHSOMETHING3__STATIC;
var CANWITHSOMETHING4 = CANWITHSOMETHING4__STATIC;
var SNAKEP = SNAKEP__STATIC;
var DOLPHIN1 = DOLPHIN1__STATIC;
var DOLPHIN2 = DOLPHIN2__STATIC;
var NEWBEAST = NEWBEAST__STATIC;
var NEWBEASTSTAYPUT = NEWBEASTSTAYPUT__STATIC;
var NEWBEASTJUMP = NEWBEASTJUMP__STATIC;
var NEWBEASTHANG = NEWBEASTHANG__STATIC;
var NEWBEASTHANGDEAD = NEWBEASTHANGDEAD__STATIC;
var BOSS4 = BOSS4__STATIC;
var BOSS4STAYPUT = BOSS4STAYPUT__STATIC;
var FEM10 = FEM10__STATIC;
var TOUGHGAL = TOUGHGAL__STATIC;
var MAN = MAN__STATIC;
var MAN2 = MAN2__STATIC;
var WOMAN = WOMAN__STATIC;
var PLEASEWAIT = PLEASEWAIT__STATIC;
var NATURALLIGHTNING = NATURALLIGHTNING__STATIC;
var WEATHERWARN = WEATHERWARN__STATIC;
var DUKETAG = DUKETAG__STATIC;
var SIGN1 = SIGN1__STATIC;
var SIGN2 = SIGN2__STATIC;
var JURYGUY = JURYGUY__STATIC;
var RESERVEDSLOT1 = RESERVEDSLOT1__STATIC;
var RESERVEDSLOT2 = RESERVEDSLOT2__STATIC;
var RESERVEDSLOT3 = RESERVEDSLOT3__STATIC;
var RESERVEDSLOT4 = RESERVEDSLOT4__STATIC;
var RESERVEDSLOT5 = RESERVEDSLOT5__STATIC;
var RESERVEDSLOT6 = RESERVEDSLOT6__STATIC;
var RESERVEDSLOT7 = RESERVEDSLOT7__STATIC;
var RESERVEDSLOT8 = RESERVEDSLOT8__STATIC;
var RESERVEDSLOT9 = RESERVEDSLOT9__STATIC;
var RESERVEDSLOT10 = RESERVEDSLOT10__STATIC;
var RESERVEDSLOT11 = RESERVEDSLOT11__STATIC;
var RESERVEDSLOT12 = RESERVEDSLOT12__STATIC;

//#if !defined LUNATIC
var h_names = {};//static hashtable_t h_names = {512, NULL};

//void G_ProcessDynamicTileMapping(const char *szLabel, int32_t lValue)
//{
//    int32_t i;

//    if ((unsigned)lValue >= MAXTILES || !szLabel)
//        return;

//    i = hash_find(&h_names,szLabel);
//    if (i>=0)
//    {
//        struct dynitem *di = &g_dynTileList[i];
//#ifdef DEBUGGINGAIDS
//        if (di->staticval != lValue)
//            OSD_Printf("REMAP %s (%d) --> %d\n", di->str, di->staticval, lValue);
//#endif
//        *di->dynvalptr = lValue;
//    }
//}

function inithashnames() : void
{
    var i : number;
    debugger
    hash_init(h_names);

    for (i=0; g_dynTileList[i].staticval >= 0; i++)
        hash_add(h_names, g_dynTileList[i].str, i, 0);
}

//void freehashnames(void)
//{
//    hash_free(&h_names);
//}
//#endif
//#endif

//// This is run after all CON define's have been processed to set up the
//// dynamic->static tile mapping.
//void G_InitDynamicTiles(void)
//{
//    int32_t i;

//    Bmemset(DynamicTileMap, 0, sizeof(DynamicTileMap));

//    for (i=0; g_dynTileList[i].staticval >= 0; i++)
//#ifdef DYNTILEREMAP_ENABLE
//        DynamicTileMap[*(g_dynTileList[i].dynvalptr)] = g_dynTileList[i].staticval;
//#else
//        DynamicTileMap[g_dynTileList[i].staticval] = g_dynTileList[i].staticval;
//#endif

//    BlimpSpawnSprites[0] = RPGSPRITE;
//    BlimpSpawnSprites[1] = CHAINGUNSPRITE;
//    BlimpSpawnSprites[2] = DEVISTATORAMMO;
//    BlimpSpawnSprites[3] = RPGAMMO;
//    BlimpSpawnSprites[4] = RPGAMMO;
//    BlimpSpawnSprites[5] = JETPACK;
//    BlimpSpawnSprites[6] = SHIELD;
//    BlimpSpawnSprites[7] = FIRSTAID;
//    BlimpSpawnSprites[8] = STEROIDS;
//    BlimpSpawnSprites[9] = RPGAMMO;
//    BlimpSpawnSprites[10] = RPGAMMO;
//    BlimpSpawnSprites[11] = RPGSPRITE;
//    BlimpSpawnSprites[12] = RPGAMMO;
//    BlimpSpawnSprites[13] = FREEZESPRITE;
//    BlimpSpawnSprites[14] = FREEZEAMMO;

//    WeaponPickupSprites[0] = KNEE;
//    WeaponPickupSprites[1] = FIRSTGUNSPRITE;
//    WeaponPickupSprites[2] = SHOTGUNSPRITE;
//    WeaponPickupSprites[3] = CHAINGUNSPRITE;
//    WeaponPickupSprites[4] = RPGSPRITE;
//    WeaponPickupSprites[5] = HEAVYHBOMB;
//    WeaponPickupSprites[6] = SHRINKERSPRITE;
//    WeaponPickupSprites[7] = DEVISTATORSPRITE;
//    WeaponPickupSprites[8] = TRIPBOMBSPRITE;
//    WeaponPickupSprites[9] = FREEZESPRITE;
//    WeaponPickupSprites[10] = HEAVYHBOMB;
//    WeaponPickupSprites[11] = SHRINKERSPRITE;
//}
