/// <reference path="../../utils/assert.ts" />
/// <reference path="../../utils/c.ts" />
/// <reference path="../../utils/todo.ts" />
/// <reference path="../../utils/types.ts" />

/// <reference path="../../build/headers/build.h.ts" />
/// <reference path="../../build/headers/cache1d.h.ts" />
/// <reference path="../../build/headers/compat.h.ts" />
/// <reference path="../../build/headers/duke3d.h.ts" />
/// <reference path="../../build/headers/engine_priv.h.ts" />
/// <reference path="../../build/headers/hightile.h.ts" />
/// <reference path="../../build/headers/mdsprite.h.ts" />
/// <reference path="../../build/headers/pragmas.h.ts" />

/// <reference path="../../build/source/baselayer.c.ts" />
/// <reference path="../../build/source/build.c.ts" />
/// <reference path="../../build/source/compat.c.ts" />
/// <reference path="../../build/source/crc32.c.ts" />
/// <reference path="../../build/source/engine.c.ts" />
/// <reference path="../../build/source/polymost.c.ts" />
/// <reference path="../../build/source/hightile.c.ts" />

/// <reference path="../../eduke32/headers/_functio.h.ts" />
/// <reference path="../../eduke32/headers/_rts.h.ts" />
/// <reference path="../../eduke32/headers/actors.h.ts" />
/// <reference path="../../eduke32/headers/common_game.h.ts" />
/// <reference path="../../eduke32/headers/function.h.ts" />
/// <reference path="../../eduke32/headers/game.h.ts" />
/// <reference path="../../eduke32/headers/gamedef.h.ts" />
/// <reference path="../../eduke32/headers/gameexec.h.ts" />
/// <reference path="../../eduke32/headers/global.h.ts" />
/// <reference path="../../eduke32/headers/grpscan.h.ts" />
/// <reference path="../../eduke32/headers/namesdyn.h.ts" />
/// <reference path="../../eduke32/headers/player.h.ts" />
/// <reference path="../../eduke32/headers/quotes.h.ts" />
/// <reference path="../../eduke32/headers/soundsdyn.h.ts" />

/// <reference path="../../eduke32/source/baselayer.c.ts" />
/// <reference path="../../eduke32/source/common.c.ts" />
/// <reference path="../../eduke32/source/config.c.ts" />
/// <reference path="../../eduke32/source/game.c.ts" />
/// <reference path="../../eduke32/source/gamedef.c.ts" />
/// <reference path="../../eduke32/source/gamevars.c.ts" />
/// <reference path="../../eduke32/source/global.c.ts" />
/// <reference path="../../eduke32/source/grpscan.c.ts" />
/// <reference path="../../eduke32/source/namesdyn.c.ts" />
/// <reference path="../../eduke32/source/net.c.ts" />
/// <reference path="../../eduke32/source/osd.c.ts" />
/// <reference path="../../eduke32/source/player.c.ts" />
/// <reference path="../../eduke32/source/rts.c.ts" />
/// <reference path="../../eduke32/source/winlayer.c.ts" />

//-------------------------------------------------------------------------
/*
Copyright (C) 2013 EDuke32 developers and contributors

This file is part of EDuke32.

EDuke32 is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 2
as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/
//-------------------------------------------------------------------------

//#include "compat.h"
//#include "build.h"

//#include "namesdyn.h"
//#include "sounds.h"
//#include "soundsdyn.h"
//#include "global.h"

//#ifdef DYNSOUNDREMAP_ENABLE
//# define DVPTR(x) &x
//#else
//# define DVPTR(x) NULL
//#endif

//int16_t DynamicSoundMap[MAXSOUNDS];

//struct dynitem
//{
//    const char *str;
//    int32_t *dynvalptr;
//    const int16_t staticval;
//};

var g_dynSoundList =
[
new dynitem( "KICK_HIT", DVPTR(KICK_HIT), KICK_HIT__STATIC ),
new dynitem( "PISTOL_RICOCHET", DVPTR(PISTOL_RICOCHET), PISTOL_RICOCHET__STATIC ),
new dynitem( "PISTOL_BODYHIT", DVPTR(PISTOL_BODYHIT), PISTOL_BODYHIT__STATIC ),
new dynitem( "PISTOL_FIRE", DVPTR(PISTOL_FIRE), PISTOL_FIRE__STATIC ),
new dynitem( "EJECT_CLIP", DVPTR(EJECT_CLIP), EJECT_CLIP__STATIC ),
new dynitem( "INSERT_CLIP", DVPTR(INSERT_CLIP), INSERT_CLIP__STATIC ),
new dynitem( "CHAINGUN_FIRE", DVPTR(CHAINGUN_FIRE), CHAINGUN_FIRE__STATIC ),
new dynitem( "RPG_SHOOT", DVPTR(RPG_SHOOT), RPG_SHOOT__STATIC ),
new dynitem( "POOLBALLHIT", DVPTR(POOLBALLHIT), POOLBALLHIT__STATIC ),
new dynitem( "RPG_EXPLODE", DVPTR(RPG_EXPLODE), RPG_EXPLODE__STATIC ),
new dynitem( "CAT_FIRE", DVPTR(CAT_FIRE), CAT_FIRE__STATIC ),
new dynitem( "SHRINKER_FIRE", DVPTR(SHRINKER_FIRE), SHRINKER_FIRE__STATIC ),
new dynitem( "ACTOR_SHRINKING", DVPTR(ACTOR_SHRINKING), ACTOR_SHRINKING__STATIC ),
new dynitem( "PIPEBOMB_BOUNCE", DVPTR(PIPEBOMB_BOUNCE), PIPEBOMB_BOUNCE__STATIC ),
new dynitem( "PIPEBOMB_EXPLODE", DVPTR(PIPEBOMB_EXPLODE), PIPEBOMB_EXPLODE__STATIC ),
new dynitem( "LASERTRIP_ONWALL", DVPTR(LASERTRIP_ONWALL), LASERTRIP_ONWALL__STATIC ),
new dynitem( "LASERTRIP_ARMING", DVPTR(LASERTRIP_ARMING), LASERTRIP_ARMING__STATIC ),
new dynitem( "LASERTRIP_EXPLODE", DVPTR(LASERTRIP_EXPLODE), LASERTRIP_EXPLODE__STATIC ),
new dynitem( "VENT_BUST", DVPTR(VENT_BUST), VENT_BUST__STATIC ),
new dynitem( "GLASS_BREAKING", DVPTR(GLASS_BREAKING), GLASS_BREAKING__STATIC ),
new dynitem( "GLASS_HEAVYBREAK", DVPTR(GLASS_HEAVYBREAK), GLASS_HEAVYBREAK__STATIC ),
new dynitem( "SHORT_CIRCUIT", DVPTR(SHORT_CIRCUIT), SHORT_CIRCUIT__STATIC ),
new dynitem( "ITEM_SPLASH", DVPTR(ITEM_SPLASH), ITEM_SPLASH__STATIC ),
new dynitem( "DUKE_BREATHING", DVPTR(DUKE_BREATHING), DUKE_BREATHING__STATIC ),
new dynitem( "DUKE_EXHALING", DVPTR(DUKE_EXHALING), DUKE_EXHALING__STATIC ),
new dynitem( "DUKE_GASP", DVPTR(DUKE_GASP), DUKE_GASP__STATIC ),
new dynitem( "SLIM_RECOG", DVPTR(SLIM_RECOG), SLIM_RECOG__STATIC ),
////     { "ENDSEQVOL3SND1", DVPTR(ENDSEQVOL3SND1), ENDSEQVOL3SND1__STATIC ),
new dynitem( "DUKE_URINATE", DVPTR(DUKE_URINATE), DUKE_URINATE__STATIC ),
new dynitem( "ENDSEQVOL3SND2", DVPTR(ENDSEQVOL3SND2), ENDSEQVOL3SND2__STATIC ),
new dynitem( "ENDSEQVOL3SND3", DVPTR(ENDSEQVOL3SND3), ENDSEQVOL3SND3__STATIC ),
new dynitem( "DUKE_PASSWIND", DVPTR(DUKE_PASSWIND), DUKE_PASSWIND__STATIC ),
new dynitem( "DUKE_CRACK", DVPTR(DUKE_CRACK), DUKE_CRACK__STATIC ),
new dynitem( "SLIM_ATTACK", DVPTR(SLIM_ATTACK), SLIM_ATTACK__STATIC ),
new dynitem( "SOMETHINGHITFORCE", DVPTR(SOMETHINGHITFORCE), SOMETHINGHITFORCE__STATIC ),
new dynitem( "DUKE_DRINKING", DVPTR(DUKE_DRINKING), DUKE_DRINKING__STATIC ),
new dynitem( "DUKE_KILLED1", DVPTR(DUKE_KILLED1), DUKE_KILLED1__STATIC ),
new dynitem( "DUKE_GRUNT", DVPTR(DUKE_GRUNT), DUKE_GRUNT__STATIC ),
new dynitem( "DUKE_HARTBEAT", DVPTR(DUKE_HARTBEAT), DUKE_HARTBEAT__STATIC ),
new dynitem( "DUKE_ONWATER", DVPTR(DUKE_ONWATER), DUKE_ONWATER__STATIC ),
new dynitem( "DUKE_DEAD", DVPTR(DUKE_DEAD), DUKE_DEAD__STATIC ),
new dynitem( "DUKE_LAND", DVPTR(DUKE_LAND), DUKE_LAND__STATIC ),
new dynitem( "DUKE_WALKINDUCTS", DVPTR(DUKE_WALKINDUCTS), DUKE_WALKINDUCTS__STATIC ),
new dynitem( "DUKE_GLAD", DVPTR(DUKE_GLAD), DUKE_GLAD__STATIC ),
new dynitem( "DUKE_YES", DVPTR(DUKE_YES), DUKE_YES__STATIC ),
new dynitem( "DUKE_HEHE", DVPTR(DUKE_HEHE), DUKE_HEHE__STATIC ),
new dynitem( "DUKE_SHUCKS", DVPTR(DUKE_SHUCKS), DUKE_SHUCKS__STATIC ),
new dynitem( "DUKE_UNDERWATER", DVPTR(DUKE_UNDERWATER), DUKE_UNDERWATER__STATIC ),
new dynitem( "DUKE_JETPACK_ON", DVPTR(DUKE_JETPACK_ON), DUKE_JETPACK_ON__STATIC ),
new dynitem( "DUKE_JETPACK_IDLE", DVPTR(DUKE_JETPACK_IDLE), DUKE_JETPACK_IDLE__STATIC ),
new dynitem( "DUKE_JETPACK_OFF", DVPTR(DUKE_JETPACK_OFF), DUKE_JETPACK_OFF__STATIC ),
new dynitem( "LIZTROOP_GROWL", DVPTR(LIZTROOP_GROWL), LIZTROOP_GROWL__STATIC ),
new dynitem( "LIZTROOP_TALK1", DVPTR(LIZTROOP_TALK1), LIZTROOP_TALK1__STATIC ),
new dynitem( "LIZTROOP_TALK2", DVPTR(LIZTROOP_TALK2), LIZTROOP_TALK2__STATIC ),
new dynitem( "LIZTROOP_TALK3", DVPTR(LIZTROOP_TALK3), LIZTROOP_TALK3__STATIC ),
new dynitem( "DUKETALKTOBOSS", DVPTR(DUKETALKTOBOSS), DUKETALKTOBOSS__STATIC ),
new dynitem( "LIZCAPT_GROWL", DVPTR(LIZCAPT_GROWL), LIZCAPT_GROWL__STATIC ),
new dynitem( "LIZCAPT_TALK1", DVPTR(LIZCAPT_TALK1), LIZCAPT_TALK1__STATIC ),
new dynitem( "LIZCAPT_TALK2", DVPTR(LIZCAPT_TALK2), LIZCAPT_TALK2__STATIC ),
new dynitem( "LIZCAPT_TALK3", DVPTR(LIZCAPT_TALK3), LIZCAPT_TALK3__STATIC ),
new dynitem( "LIZARD_BEG", DVPTR(LIZARD_BEG), LIZARD_BEG__STATIC ),
new dynitem( "LIZARD_PAIN", DVPTR(LIZARD_PAIN), LIZARD_PAIN__STATIC ),
new dynitem( "LIZARD_DEATH", DVPTR(LIZARD_DEATH), LIZARD_DEATH__STATIC ),
new dynitem( "LIZARD_SPIT", DVPTR(LIZARD_SPIT), LIZARD_SPIT__STATIC ),
new dynitem( "DRONE1_HISSRATTLE", DVPTR(DRONE1_HISSRATTLE), DRONE1_HISSRATTLE__STATIC ),
new dynitem( "DRONE1_HISSSCREECH", DVPTR(DRONE1_HISSSCREECH), DRONE1_HISSSCREECH__STATIC ),
new dynitem( "DUKE_TIP2", DVPTR(DUKE_TIP2), DUKE_TIP2__STATIC ),
new dynitem( "FLESH_BURNING", DVPTR(FLESH_BURNING), FLESH_BURNING__STATIC ),
new dynitem( "SQUISHED", DVPTR(SQUISHED), SQUISHED__STATIC ),
new dynitem( "TELEPORTER", DVPTR(TELEPORTER), TELEPORTER__STATIC ),
new dynitem( "ELEVATOR_ON", DVPTR(ELEVATOR_ON), ELEVATOR_ON__STATIC ),
new dynitem( "DUKE_KILLED3", DVPTR(DUKE_KILLED3), DUKE_KILLED3__STATIC ),
new dynitem( "ELEVATOR_OFF", DVPTR(ELEVATOR_OFF), ELEVATOR_OFF__STATIC ),
new dynitem( "DOOR_OPERATE1", DVPTR(DOOR_OPERATE1), DOOR_OPERATE1__STATIC ),
new dynitem( "SUBWAY", DVPTR(SUBWAY), SUBWAY__STATIC ),
new dynitem( "SWITCH_ON", DVPTR(SWITCH_ON), SWITCH_ON__STATIC ),
new dynitem( "FAN", DVPTR(FAN), FAN__STATIC ),
new dynitem( "DUKE_GETWEAPON3", DVPTR(DUKE_GETWEAPON3), DUKE_GETWEAPON3__STATIC ),
new dynitem( "FLUSH_TOILET", DVPTR(FLUSH_TOILET), FLUSH_TOILET__STATIC ),
new dynitem( "HOVER_CRAFT", DVPTR(HOVER_CRAFT), HOVER_CRAFT__STATIC ),
new dynitem( "EARTHQUAKE", DVPTR(EARTHQUAKE), EARTHQUAKE__STATIC ),
new dynitem( "INTRUDER_ALERT", DVPTR(INTRUDER_ALERT), INTRUDER_ALERT__STATIC ),
new dynitem( "END_OF_LEVEL_WARN", DVPTR(END_OF_LEVEL_WARN), END_OF_LEVEL_WARN__STATIC ),
new dynitem( "ENGINE_OPERATING", DVPTR(ENGINE_OPERATING), ENGINE_OPERATING__STATIC ),
new dynitem( "REACTOR_ON", DVPTR(REACTOR_ON), REACTOR_ON__STATIC ),
new dynitem( "COMPUTER_AMBIENCE", DVPTR(COMPUTER_AMBIENCE), COMPUTER_AMBIENCE__STATIC ),
new dynitem( "GEARS_GRINDING", DVPTR(GEARS_GRINDING), GEARS_GRINDING__STATIC ),
new dynitem( "BUBBLE_AMBIENCE", DVPTR(BUBBLE_AMBIENCE), BUBBLE_AMBIENCE__STATIC ),
new dynitem( "MACHINE_AMBIENCE", DVPTR(MACHINE_AMBIENCE), MACHINE_AMBIENCE__STATIC ),
new dynitem( "SEWER_AMBIENCE", DVPTR(SEWER_AMBIENCE), SEWER_AMBIENCE__STATIC ),
new dynitem( "WIND_AMBIENCE", DVPTR(WIND_AMBIENCE), WIND_AMBIENCE__STATIC ),
new dynitem( "SOMETHING_DRIPPING", DVPTR(SOMETHING_DRIPPING), SOMETHING_DRIPPING__STATIC ),
new dynitem( "STEAM_HISSING", DVPTR(STEAM_HISSING), STEAM_HISSING__STATIC ),
new dynitem( "THEATER_BREATH", DVPTR(THEATER_BREATH), THEATER_BREATH__STATIC ),
new dynitem( "BAR_MUSIC", DVPTR(BAR_MUSIC), BAR_MUSIC__STATIC ),
new dynitem( "BOS1_ROAM", DVPTR(BOS1_ROAM), BOS1_ROAM__STATIC ),
new dynitem( "BOS1_RECOG", DVPTR(BOS1_RECOG), BOS1_RECOG__STATIC ),
new dynitem( "BOS1_ATTACK1", DVPTR(BOS1_ATTACK1), BOS1_ATTACK1__STATIC ),
new dynitem( "BOS1_PAIN", DVPTR(BOS1_PAIN), BOS1_PAIN__STATIC ),
new dynitem( "BOS1_DYING", DVPTR(BOS1_DYING), BOS1_DYING__STATIC ),
new dynitem( "BOS2_ROAM", DVPTR(BOS2_ROAM), BOS2_ROAM__STATIC ),
new dynitem( "BOS2_RECOG", DVPTR(BOS2_RECOG), BOS2_RECOG__STATIC ),
new dynitem( "BOS2_ATTACK", DVPTR(BOS2_ATTACK), BOS2_ATTACK__STATIC ),
new dynitem( "BOS2_PAIN", DVPTR(BOS2_PAIN), BOS2_PAIN__STATIC ),
new dynitem( "BOS2_DYING", DVPTR(BOS2_DYING), BOS2_DYING__STATIC ),
new dynitem( "GETATOMICHEALTH", DVPTR(GETATOMICHEALTH), GETATOMICHEALTH__STATIC ),
new dynitem( "DUKE_GETWEAPON2", DVPTR(DUKE_GETWEAPON2), DUKE_GETWEAPON2__STATIC ),
new dynitem( "BOS3_DYING", DVPTR(BOS3_DYING), BOS3_DYING__STATIC ),
new dynitem( "SHOTGUN_FIRE", DVPTR(SHOTGUN_FIRE), SHOTGUN_FIRE__STATIC ),
new dynitem( "PRED_ROAM", DVPTR(PRED_ROAM), PRED_ROAM__STATIC ),
new dynitem( "PRED_RECOG", DVPTR(PRED_RECOG), PRED_RECOG__STATIC ),
new dynitem( "PRED_ATTACK", DVPTR(PRED_ATTACK), PRED_ATTACK__STATIC ),
new dynitem( "PRED_PAIN", DVPTR(PRED_PAIN), PRED_PAIN__STATIC ),
new dynitem( "PRED_DYING", DVPTR(PRED_DYING), PRED_DYING__STATIC ),
new dynitem( "CAPT_ROAM", DVPTR(CAPT_ROAM), CAPT_ROAM__STATIC ),
new dynitem( "CAPT_ATTACK", DVPTR(CAPT_ATTACK), CAPT_ATTACK__STATIC ),
new dynitem( "CAPT_RECOG", DVPTR(CAPT_RECOG), CAPT_RECOG__STATIC ),
new dynitem( "CAPT_PAIN", DVPTR(CAPT_PAIN), CAPT_PAIN__STATIC ),
new dynitem( "CAPT_DYING", DVPTR(CAPT_DYING), CAPT_DYING__STATIC ),
new dynitem( "PIG_ROAM", DVPTR(PIG_ROAM), PIG_ROAM__STATIC ),
new dynitem( "PIG_RECOG", DVPTR(PIG_RECOG), PIG_RECOG__STATIC ),
new dynitem( "PIG_ATTACK", DVPTR(PIG_ATTACK), PIG_ATTACK__STATIC ),
new dynitem( "PIG_PAIN", DVPTR(PIG_PAIN), PIG_PAIN__STATIC ),
new dynitem( "PIG_DYING", DVPTR(PIG_DYING), PIG_DYING__STATIC ),
new dynitem( "RECO_ROAM", DVPTR(RECO_ROAM), RECO_ROAM__STATIC ),
new dynitem( "RECO_RECOG", DVPTR(RECO_RECOG), RECO_RECOG__STATIC ),
new dynitem( "RECO_ATTACK", DVPTR(RECO_ATTACK), RECO_ATTACK__STATIC ),
new dynitem( "RECO_PAIN", DVPTR(RECO_PAIN), RECO_PAIN__STATIC ),
new dynitem( "RECO_DYING", DVPTR(RECO_DYING), RECO_DYING__STATIC ),
new dynitem( "DRON_ROAM", DVPTR(DRON_ROAM), DRON_ROAM__STATIC ),
new dynitem( "DRON_RECOG", DVPTR(DRON_RECOG), DRON_RECOG__STATIC ),
new dynitem( "DRON_ATTACK1", DVPTR(DRON_ATTACK1), DRON_ATTACK1__STATIC ),
new dynitem( "DRON_PAIN", DVPTR(DRON_PAIN), DRON_PAIN__STATIC ),
new dynitem( "DRON_DYING", DVPTR(DRON_DYING), DRON_DYING__STATIC ),
new dynitem( "COMM_ROAM", DVPTR(COMM_ROAM), COMM_ROAM__STATIC ),
new dynitem( "COMM_RECOG", DVPTR(COMM_RECOG), COMM_RECOG__STATIC ),
new dynitem( "COMM_ATTACK", DVPTR(COMM_ATTACK), COMM_ATTACK__STATIC ),
new dynitem( "COMM_PAIN", DVPTR(COMM_PAIN), COMM_PAIN__STATIC ),
new dynitem( "COMM_DYING", DVPTR(COMM_DYING), COMM_DYING__STATIC ),
new dynitem( "OCTA_ROAM", DVPTR(OCTA_ROAM), OCTA_ROAM__STATIC ),
new dynitem( "OCTA_RECOG", DVPTR(OCTA_RECOG), OCTA_RECOG__STATIC ),
new dynitem( "OCTA_ATTACK1", DVPTR(OCTA_ATTACK1), OCTA_ATTACK1__STATIC ),
new dynitem( "OCTA_PAIN", DVPTR(OCTA_PAIN), OCTA_PAIN__STATIC ),
new dynitem( "OCTA_DYING", DVPTR(OCTA_DYING), OCTA_DYING__STATIC ),
new dynitem( "TURR_ROAM", DVPTR(TURR_ROAM), TURR_ROAM__STATIC ),
new dynitem( "TURR_RECOG", DVPTR(TURR_RECOG), TURR_RECOG__STATIC ),
new dynitem( "TURR_ATTACK", DVPTR(TURR_ATTACK), TURR_ATTACK__STATIC ),
new dynitem( "DUMPSTER_MOVE", DVPTR(DUMPSTER_MOVE), DUMPSTER_MOVE__STATIC ),
new dynitem( "SLIM_DYING", DVPTR(SLIM_DYING), SLIM_DYING__STATIC ),
new dynitem( "BOS3_ROAM", DVPTR(BOS3_ROAM), BOS3_ROAM__STATIC ),
new dynitem( "BOS3_RECOG", DVPTR(BOS3_RECOG), BOS3_RECOG__STATIC ),
new dynitem( "BOS3_ATTACK1", DVPTR(BOS3_ATTACK1), BOS3_ATTACK1__STATIC ),
new dynitem( "BOS3_PAIN", DVPTR(BOS3_PAIN), BOS3_PAIN__STATIC ),
new dynitem( "BOS1_ATTACK2", DVPTR(BOS1_ATTACK2), BOS1_ATTACK2__STATIC ),
new dynitem( "COMM_SPIN", DVPTR(COMM_SPIN), COMM_SPIN__STATIC ),
new dynitem( "BOS1_WALK", DVPTR(BOS1_WALK), BOS1_WALK__STATIC ),
new dynitem( "DRON_ATTACK2", DVPTR(DRON_ATTACK2), DRON_ATTACK2__STATIC ),
new dynitem( "THUD", DVPTR(THUD), THUD__STATIC ),
new dynitem( "OCTA_ATTACK2", DVPTR(OCTA_ATTACK2), OCTA_ATTACK2__STATIC ),
new dynitem( "WIERDSHOT_FLY", DVPTR(WIERDSHOT_FLY), WIERDSHOT_FLY__STATIC ),
new dynitem( "TURR_PAIN", DVPTR(TURR_PAIN), TURR_PAIN__STATIC ),
new dynitem( "TURR_DYING", DVPTR(TURR_DYING), TURR_DYING__STATIC ),
new dynitem( "SLIM_ROAM", DVPTR(SLIM_ROAM), SLIM_ROAM__STATIC ),
new dynitem( "LADY_SCREAM", DVPTR(LADY_SCREAM), LADY_SCREAM__STATIC ),
new dynitem( "DOOR_OPERATE2", DVPTR(DOOR_OPERATE2), DOOR_OPERATE2__STATIC ),
new dynitem( "DOOR_OPERATE3", DVPTR(DOOR_OPERATE3), DOOR_OPERATE3__STATIC ),
new dynitem( "DOOR_OPERATE4", DVPTR(DOOR_OPERATE4), DOOR_OPERATE4__STATIC ),
new dynitem( "BORNTOBEWILDSND", DVPTR(BORNTOBEWILDSND), BORNTOBEWILDSND__STATIC ),
new dynitem( "SHOTGUN_COCK", DVPTR(SHOTGUN_COCK), SHOTGUN_COCK__STATIC ),
new dynitem( "GENERIC_AMBIENCE1", DVPTR(GENERIC_AMBIENCE1), GENERIC_AMBIENCE1__STATIC ),
new dynitem( "GENERIC_AMBIENCE2", DVPTR(GENERIC_AMBIENCE2), GENERIC_AMBIENCE2__STATIC ),
new dynitem( "GENERIC_AMBIENCE3", DVPTR(GENERIC_AMBIENCE3), GENERIC_AMBIENCE3__STATIC ),
new dynitem( "GENERIC_AMBIENCE4", DVPTR(GENERIC_AMBIENCE4), GENERIC_AMBIENCE4__STATIC ),
new dynitem( "GENERIC_AMBIENCE5", DVPTR(GENERIC_AMBIENCE5), GENERIC_AMBIENCE5__STATIC ),
new dynitem( "GENERIC_AMBIENCE6", DVPTR(GENERIC_AMBIENCE6), GENERIC_AMBIENCE6__STATIC ),
new dynitem( "BOS3_ATTACK2", DVPTR(BOS3_ATTACK2), BOS3_ATTACK2__STATIC ),
new dynitem( "GENERIC_AMBIENCE17", DVPTR(GENERIC_AMBIENCE17), GENERIC_AMBIENCE17__STATIC ),
new dynitem( "GENERIC_AMBIENCE18", DVPTR(GENERIC_AMBIENCE18), GENERIC_AMBIENCE18__STATIC ),
new dynitem( "GENERIC_AMBIENCE19", DVPTR(GENERIC_AMBIENCE19), GENERIC_AMBIENCE19__STATIC ),
new dynitem( "GENERIC_AMBIENCE20", DVPTR(GENERIC_AMBIENCE20), GENERIC_AMBIENCE20__STATIC ),
new dynitem( "GENERIC_AMBIENCE21", DVPTR(GENERIC_AMBIENCE21), GENERIC_AMBIENCE21__STATIC ),
new dynitem( "GENERIC_AMBIENCE22", DVPTR(GENERIC_AMBIENCE22), GENERIC_AMBIENCE22__STATIC ),
new dynitem( "SECRETLEVELSND", DVPTR(SECRETLEVELSND), SECRETLEVELSND__STATIC ),
new dynitem( "GENERIC_AMBIENCE8", DVPTR(GENERIC_AMBIENCE8), GENERIC_AMBIENCE8__STATIC ),
new dynitem( "GENERIC_AMBIENCE9", DVPTR(GENERIC_AMBIENCE9), GENERIC_AMBIENCE9__STATIC ),
new dynitem( "GENERIC_AMBIENCE10", DVPTR(GENERIC_AMBIENCE10), GENERIC_AMBIENCE10__STATIC ),
new dynitem( "GENERIC_AMBIENCE11", DVPTR(GENERIC_AMBIENCE11), GENERIC_AMBIENCE11__STATIC ),
new dynitem( "GENERIC_AMBIENCE12", DVPTR(GENERIC_AMBIENCE12), GENERIC_AMBIENCE12__STATIC ),
new dynitem( "GENERIC_AMBIENCE13", DVPTR(GENERIC_AMBIENCE13), GENERIC_AMBIENCE13__STATIC ),
new dynitem( "GENERIC_AMBIENCE14", DVPTR(GENERIC_AMBIENCE14), GENERIC_AMBIENCE14__STATIC ),
new dynitem( "GENERIC_AMBIENCE15", DVPTR(GENERIC_AMBIENCE15), GENERIC_AMBIENCE15__STATIC ),
new dynitem( "GENERIC_AMBIENCE16", DVPTR(GENERIC_AMBIENCE16), GENERIC_AMBIENCE16__STATIC ),
new dynitem( "FIRE_CRACKLE", DVPTR(FIRE_CRACKLE), FIRE_CRACKLE__STATIC ),
new dynitem( "BONUS_SPEECH1", DVPTR(BONUS_SPEECH1), BONUS_SPEECH1__STATIC ),
new dynitem( "BONUS_SPEECH2", DVPTR(BONUS_SPEECH2), BONUS_SPEECH2__STATIC ),
new dynitem( "BONUS_SPEECH3", DVPTR(BONUS_SPEECH3), BONUS_SPEECH3__STATIC ),
new dynitem( "PIG_CAPTURE_DUKE", DVPTR(PIG_CAPTURE_DUKE), PIG_CAPTURE_DUKE__STATIC ),
new dynitem( "BONUS_SPEECH4", DVPTR(BONUS_SPEECH4), BONUS_SPEECH4__STATIC ),
new dynitem( "DUKE_LAND_HURT", DVPTR(DUKE_LAND_HURT), DUKE_LAND_HURT__STATIC ),
new dynitem( "DUKE_HIT_STRIPPER1", DVPTR(DUKE_HIT_STRIPPER1), DUKE_HIT_STRIPPER1__STATIC ),
new dynitem( "DUKE_TIP1", DVPTR(DUKE_TIP1), DUKE_TIP1__STATIC ),
new dynitem( "DUKE_KILLED2", DVPTR(DUKE_KILLED2), DUKE_KILLED2__STATIC ),
new dynitem( "PRED_ROAM2", DVPTR(PRED_ROAM2), PRED_ROAM2__STATIC ),
new dynitem( "PIG_ROAM2", DVPTR(PIG_ROAM2), PIG_ROAM2__STATIC ),
new dynitem( "DUKE_GETWEAPON1", DVPTR(DUKE_GETWEAPON1), DUKE_GETWEAPON1__STATIC ),
new dynitem( "DUKE_SEARCH2", DVPTR(DUKE_SEARCH2), DUKE_SEARCH2__STATIC ),
new dynitem( "DUKE_CRACK2", DVPTR(DUKE_CRACK2), DUKE_CRACK2__STATIC ),
new dynitem( "DUKE_SEARCH", DVPTR(DUKE_SEARCH), DUKE_SEARCH__STATIC ),
new dynitem( "DUKE_GET", DVPTR(DUKE_GET), DUKE_GET__STATIC ),
new dynitem( "DUKE_LONGTERM_PAIN", DVPTR(DUKE_LONGTERM_PAIN), DUKE_LONGTERM_PAIN__STATIC ),
new dynitem( "MONITOR_ACTIVE", DVPTR(MONITOR_ACTIVE), MONITOR_ACTIVE__STATIC ),
new dynitem( "NITEVISION_ONOFF", DVPTR(NITEVISION_ONOFF), NITEVISION_ONOFF__STATIC ),
new dynitem( "DUKE_HIT_STRIPPER2", DVPTR(DUKE_HIT_STRIPPER2), DUKE_HIT_STRIPPER2__STATIC ),
new dynitem( "DUKE_CRACK_FIRST", DVPTR(DUKE_CRACK_FIRST), DUKE_CRACK_FIRST__STATIC ),
new dynitem( "DUKE_USEMEDKIT", DVPTR(DUKE_USEMEDKIT), DUKE_USEMEDKIT__STATIC ),
new dynitem( "DUKE_TAKEPILLS", DVPTR(DUKE_TAKEPILLS), DUKE_TAKEPILLS__STATIC ),
new dynitem( "DUKE_PISSRELIEF", DVPTR(DUKE_PISSRELIEF), DUKE_PISSRELIEF__STATIC ),
new dynitem( "SELECT_WEAPON", DVPTR(SELECT_WEAPON), SELECT_WEAPON__STATIC ),
new dynitem( "WATER_GURGLE", DVPTR(WATER_GURGLE), WATER_GURGLE__STATIC ),
new dynitem( "DUKE_GETWEAPON4", DVPTR(DUKE_GETWEAPON4), DUKE_GETWEAPON4__STATIC ),
new dynitem( "JIBBED_ACTOR1", DVPTR(JIBBED_ACTOR1), JIBBED_ACTOR1__STATIC ),
new dynitem( "JIBBED_ACTOR2", DVPTR(JIBBED_ACTOR2), JIBBED_ACTOR2__STATIC ),
new dynitem( "JIBBED_ACTOR3", DVPTR(JIBBED_ACTOR3), JIBBED_ACTOR3__STATIC ),
new dynitem( "JIBBED_ACTOR4", DVPTR(JIBBED_ACTOR4), JIBBED_ACTOR4__STATIC ),
new dynitem( "JIBBED_ACTOR5", DVPTR(JIBBED_ACTOR5), JIBBED_ACTOR5__STATIC ),
new dynitem( "JIBBED_ACTOR6", DVPTR(JIBBED_ACTOR6), JIBBED_ACTOR6__STATIC ),
new dynitem( "JIBBED_ACTOR7", DVPTR(JIBBED_ACTOR7), JIBBED_ACTOR7__STATIC ),
new dynitem( "DUKE_GOTHEALTHATLOW", DVPTR(DUKE_GOTHEALTHATLOW), DUKE_GOTHEALTHATLOW__STATIC ),
new dynitem( "BOSSTALKTODUKE", DVPTR(BOSSTALKTODUKE), BOSSTALKTODUKE__STATIC ),
new dynitem( "WAR_AMBIENCE1", DVPTR(WAR_AMBIENCE1), WAR_AMBIENCE1__STATIC ),
new dynitem( "WAR_AMBIENCE2", DVPTR(WAR_AMBIENCE2), WAR_AMBIENCE2__STATIC ),
new dynitem( "WAR_AMBIENCE3", DVPTR(WAR_AMBIENCE3), WAR_AMBIENCE3__STATIC ),
new dynitem( "WAR_AMBIENCE4", DVPTR(WAR_AMBIENCE4), WAR_AMBIENCE4__STATIC ),
new dynitem( "WAR_AMBIENCE5", DVPTR(WAR_AMBIENCE5), WAR_AMBIENCE5__STATIC ),
new dynitem( "WAR_AMBIENCE6", DVPTR(WAR_AMBIENCE6), WAR_AMBIENCE6__STATIC ),
new dynitem( "WAR_AMBIENCE7", DVPTR(WAR_AMBIENCE7), WAR_AMBIENCE7__STATIC ),
new dynitem( "WAR_AMBIENCE8", DVPTR(WAR_AMBIENCE8), WAR_AMBIENCE8__STATIC ),
new dynitem( "WAR_AMBIENCE9", DVPTR(WAR_AMBIENCE9), WAR_AMBIENCE9__STATIC ),
new dynitem( "WAR_AMBIENCE10", DVPTR(WAR_AMBIENCE10), WAR_AMBIENCE10__STATIC ),
new dynitem( "ALIEN_TALK1", DVPTR(ALIEN_TALK1), ALIEN_TALK1__STATIC ),
new dynitem( "ALIEN_TALK2", DVPTR(ALIEN_TALK2), ALIEN_TALK2__STATIC ),
new dynitem( "EXITMENUSOUND", DVPTR(EXITMENUSOUND), EXITMENUSOUND__STATIC ),
new dynitem( "FLY_BY", DVPTR(FLY_BY), FLY_BY__STATIC ),
new dynitem( "DUKE_SCREAM", DVPTR(DUKE_SCREAM), DUKE_SCREAM__STATIC ),
new dynitem( "SHRINKER_HIT", DVPTR(SHRINKER_HIT), SHRINKER_HIT__STATIC ),
new dynitem( "RATTY", DVPTR(RATTY), RATTY__STATIC ),
new dynitem( "INTO_MENU", DVPTR(INTO_MENU), INTO_MENU__STATIC ),
new dynitem( "BONUSMUSIC", DVPTR(BONUSMUSIC), BONUSMUSIC__STATIC ),
new dynitem( "DUKE_BOOBY", DVPTR(DUKE_BOOBY), DUKE_BOOBY__STATIC ),
new dynitem( "DUKE_TALKTOBOSSFALL", DVPTR(DUKE_TALKTOBOSSFALL), DUKE_TALKTOBOSSFALL__STATIC ),
new dynitem( "DUKE_LOOKINTOMIRROR", DVPTR(DUKE_LOOKINTOMIRROR), DUKE_LOOKINTOMIRROR__STATIC ),
new dynitem( "PIG_ROAM3", DVPTR(PIG_ROAM3), PIG_ROAM3__STATIC ),
new dynitem( "KILLME", DVPTR(KILLME), KILLME__STATIC ),
new dynitem( "DRON_JETSND", DVPTR(DRON_JETSND), DRON_JETSND__STATIC ),
new dynitem( "SPACE_DOOR1", DVPTR(SPACE_DOOR1), SPACE_DOOR1__STATIC ),
new dynitem( "SPACE_DOOR2", DVPTR(SPACE_DOOR2), SPACE_DOOR2__STATIC ),
new dynitem( "SPACE_DOOR3", DVPTR(SPACE_DOOR3), SPACE_DOOR3__STATIC ),
new dynitem( "SPACE_DOOR4", DVPTR(SPACE_DOOR4), SPACE_DOOR4__STATIC ),
new dynitem( "SPACE_DOOR5", DVPTR(SPACE_DOOR5), SPACE_DOOR5__STATIC ),
new dynitem( "ALIEN_ELEVATOR1", DVPTR(ALIEN_ELEVATOR1), ALIEN_ELEVATOR1__STATIC ),
new dynitem( "VAULT_DOOR", DVPTR(VAULT_DOOR), VAULT_DOOR__STATIC ),
new dynitem( "JIBBED_ACTOR13", DVPTR(JIBBED_ACTOR13), JIBBED_ACTOR13__STATIC ),
new dynitem( "DUKE_GETWEAPON6", DVPTR(DUKE_GETWEAPON6), DUKE_GETWEAPON6__STATIC ),
new dynitem( "JIBBED_ACTOR8", DVPTR(JIBBED_ACTOR8), JIBBED_ACTOR8__STATIC ),
new dynitem( "JIBBED_ACTOR9", DVPTR(JIBBED_ACTOR9), JIBBED_ACTOR9__STATIC ),
new dynitem( "JIBBED_ACTOR10", DVPTR(JIBBED_ACTOR10), JIBBED_ACTOR10__STATIC ),
new dynitem( "JIBBED_ACTOR11", DVPTR(JIBBED_ACTOR11), JIBBED_ACTOR11__STATIC ),
new dynitem( "JIBBED_ACTOR12", DVPTR(JIBBED_ACTOR12), JIBBED_ACTOR12__STATIC ),
new dynitem( "DUKE_KILLED4", DVPTR(DUKE_KILLED4), DUKE_KILLED4__STATIC ),
new dynitem( "DUKE_KILLED5", DVPTR(DUKE_KILLED5), DUKE_KILLED5__STATIC ),
new dynitem( "ALIEN_SWITCH1", DVPTR(ALIEN_SWITCH1), ALIEN_SWITCH1__STATIC ),
new dynitem( "DUKE_STEPONFECES", DVPTR(DUKE_STEPONFECES), DUKE_STEPONFECES__STATIC ),
new dynitem( "DUKE_LONGTERM_PAIN2", DVPTR(DUKE_LONGTERM_PAIN2), DUKE_LONGTERM_PAIN2__STATIC ),
new dynitem( "DUKE_LONGTERM_PAIN3", DVPTR(DUKE_LONGTERM_PAIN3), DUKE_LONGTERM_PAIN3__STATIC ),
new dynitem( "DUKE_LONGTERM_PAIN4", DVPTR(DUKE_LONGTERM_PAIN4), DUKE_LONGTERM_PAIN4__STATIC ),
new dynitem( "COMPANB2", DVPTR(COMPANB2), COMPANB2__STATIC ),
new dynitem( "KTIT", DVPTR(KTIT), KTIT__STATIC ),
new dynitem( "HELICOP_IDLE", DVPTR(HELICOP_IDLE), HELICOP_IDLE__STATIC ),
new dynitem( "STEPNIT", DVPTR(STEPNIT), STEPNIT__STATIC ),
new dynitem( "SPACE_AMBIENCE1", DVPTR(SPACE_AMBIENCE1), SPACE_AMBIENCE1__STATIC ),
new dynitem( "SPACE_AMBIENCE2", DVPTR(SPACE_AMBIENCE2), SPACE_AMBIENCE2__STATIC ),
new dynitem( "SLIM_HATCH", DVPTR(SLIM_HATCH), SLIM_HATCH__STATIC ),
new dynitem( "RIPHEADNECK", DVPTR(RIPHEADNECK), RIPHEADNECK__STATIC ),
new dynitem( "FOUNDJONES", DVPTR(FOUNDJONES), FOUNDJONES__STATIC ),
new dynitem( "ALIEN_DOOR1", DVPTR(ALIEN_DOOR1), ALIEN_DOOR1__STATIC ),
new dynitem( "ALIEN_DOOR2", DVPTR(ALIEN_DOOR2), ALIEN_DOOR2__STATIC ),
new dynitem( "ENDSEQVOL3SND4", DVPTR(ENDSEQVOL3SND4), ENDSEQVOL3SND4__STATIC ),
new dynitem( "ENDSEQVOL3SND5", DVPTR(ENDSEQVOL3SND5), ENDSEQVOL3SND5__STATIC ),
new dynitem( "ENDSEQVOL3SND6", DVPTR(ENDSEQVOL3SND6), ENDSEQVOL3SND6__STATIC ),
new dynitem( "ENDSEQVOL3SND7", DVPTR(ENDSEQVOL3SND7), ENDSEQVOL3SND7__STATIC ),
new dynitem( "ENDSEQVOL3SND8", DVPTR(ENDSEQVOL3SND8), ENDSEQVOL3SND8__STATIC ),
new dynitem( "ENDSEQVOL3SND9", DVPTR(ENDSEQVOL3SND9), ENDSEQVOL3SND9__STATIC ),
new dynitem( "WHIPYOURASS", DVPTR(WHIPYOURASS), WHIPYOURASS__STATIC ),
new dynitem( "ENDSEQVOL2SND1", DVPTR(ENDSEQVOL2SND1), ENDSEQVOL2SND1__STATIC ),
new dynitem( "ENDSEQVOL2SND2", DVPTR(ENDSEQVOL2SND2), ENDSEQVOL2SND2__STATIC ),
new dynitem( "ENDSEQVOL2SND3", DVPTR(ENDSEQVOL2SND3), ENDSEQVOL2SND3__STATIC ),
new dynitem( "ENDSEQVOL2SND4", DVPTR(ENDSEQVOL2SND4), ENDSEQVOL2SND4__STATIC ),
new dynitem( "ENDSEQVOL2SND5", DVPTR(ENDSEQVOL2SND5), ENDSEQVOL2SND5__STATIC ),
new dynitem( "ENDSEQVOL2SND6", DVPTR(ENDSEQVOL2SND6), ENDSEQVOL2SND6__STATIC ),
new dynitem( "ENDSEQVOL2SND7", DVPTR(ENDSEQVOL2SND7), ENDSEQVOL2SND7__STATIC ),
new dynitem( "GENERIC_AMBIENCE23", DVPTR(GENERIC_AMBIENCE23), GENERIC_AMBIENCE23__STATIC ),
new dynitem( "SOMETHINGFROZE", DVPTR(SOMETHINGFROZE), SOMETHINGFROZE__STATIC ),
new dynitem( "DUKE_LONGTERM_PAIN5", DVPTR(DUKE_LONGTERM_PAIN5), DUKE_LONGTERM_PAIN5__STATIC ),
new dynitem( "DUKE_LONGTERM_PAIN6", DVPTR(DUKE_LONGTERM_PAIN6), DUKE_LONGTERM_PAIN6__STATIC ),
new dynitem( "DUKE_LONGTERM_PAIN7", DVPTR(DUKE_LONGTERM_PAIN7), DUKE_LONGTERM_PAIN7__STATIC ),
new dynitem( "DUKE_LONGTERM_PAIN8", DVPTR(DUKE_LONGTERM_PAIN8), DUKE_LONGTERM_PAIN8__STATIC ),
new dynitem( "WIND_REPEAT", DVPTR(WIND_REPEAT), WIND_REPEAT__STATIC ),
new dynitem( "MYENEMY_ROAM", DVPTR(MYENEMY_ROAM), MYENEMY_ROAM__STATIC ),
new dynitem( "MYENEMY_HURT", DVPTR(MYENEMY_HURT), MYENEMY_HURT__STATIC ),
new dynitem( "MYENEMY_DEAD", DVPTR(MYENEMY_DEAD), MYENEMY_DEAD__STATIC ),
new dynitem( "MYENEMY_SHOOT", DVPTR(MYENEMY_SHOOT), MYENEMY_SHOOT__STATIC ),
new dynitem( "STORE_MUSIC", DVPTR(STORE_MUSIC), STORE_MUSIC__STATIC ),
new dynitem( "STORE_MUSIC_BROKE", DVPTR(STORE_MUSIC_BROKE), STORE_MUSIC_BROKE__STATIC ),
new dynitem( "ACTOR_GROWING", DVPTR(ACTOR_GROWING), ACTOR_GROWING__STATIC ),
new dynitem( "NEWBEAST_ROAM", DVPTR(NEWBEAST_ROAM), NEWBEAST_ROAM__STATIC ),
new dynitem( "NEWBEAST_RECOG", DVPTR(NEWBEAST_RECOG), NEWBEAST_RECOG__STATIC ),
new dynitem( "NEWBEAST_ATTACK", DVPTR(NEWBEAST_ATTACK), NEWBEAST_ATTACK__STATIC ),
new dynitem( "NEWBEAST_PAIN", DVPTR(NEWBEAST_PAIN), NEWBEAST_PAIN__STATIC ),
new dynitem( "NEWBEAST_DYING", DVPTR(NEWBEAST_DYING), NEWBEAST_DYING__STATIC ),
new dynitem( "NEWBEAST_SPIT", DVPTR(NEWBEAST_SPIT), NEWBEAST_SPIT__STATIC ),
new dynitem( "VOL4_1", DVPTR(VOL4_1), VOL4_1__STATIC ),
new dynitem( "SUPERMARKET", DVPTR(SUPERMARKET), SUPERMARKET__STATIC ),
new dynitem( "MOUSEANNOY", DVPTR(MOUSEANNOY), MOUSEANNOY__STATIC ),
new dynitem( "BOOKEM", DVPTR(BOOKEM), BOOKEM__STATIC ),
new dynitem( "SUPERMARKETCRY", DVPTR(SUPERMARKETCRY), SUPERMARKETCRY__STATIC ),
new dynitem( "DESTRUCT", DVPTR(DESTRUCT), DESTRUCT__STATIC ),
new dynitem( "EATFOOD", DVPTR(EATFOOD), EATFOOD__STATIC ),
new dynitem( "MAKEMYDAY", DVPTR(MAKEMYDAY), MAKEMYDAY__STATIC ),
new dynitem( "WITNESSSTAND", DVPTR(WITNESSSTAND), WITNESSSTAND__STATIC ),
new dynitem( "VACATIONSPEECH", DVPTR(VACATIONSPEECH), VACATIONSPEECH__STATIC ),
new dynitem( "YIPPEE1", DVPTR(YIPPEE1), YIPPEE1__STATIC ),
new dynitem( "YOHOO1", DVPTR(YOHOO1), YOHOO1__STATIC ),
new dynitem( "YOHOO2", DVPTR(YOHOO2), YOHOO2__STATIC ),
new dynitem( "DOLPHINSND", DVPTR(DOLPHINSND), DOLPHINSND__STATIC ),
new dynitem( "TOUGHGALSND1", DVPTR(TOUGHGALSND1), TOUGHGALSND1__STATIC ),
new dynitem( "TOUGHGALSND2", DVPTR(TOUGHGALSND2), TOUGHGALSND2__STATIC ),
new dynitem( "TOUGHGALSND3", DVPTR(TOUGHGALSND3), TOUGHGALSND3__STATIC ),
new dynitem( "TOUGHGALSND4", DVPTR(TOUGHGALSND4), TOUGHGALSND4__STATIC ),
new dynitem( "TANK_ROAM", DVPTR(TANK_ROAM), TANK_ROAM__STATIC ),
new dynitem( "BOS4_ROAM", DVPTR(BOS4_ROAM), BOS4_ROAM__STATIC ),
new dynitem( "BOS4_RECOG", DVPTR(BOS4_RECOG), BOS4_RECOG__STATIC ),
new dynitem( "BOS4_ATTACK", DVPTR(BOS4_ATTACK), BOS4_ATTACK__STATIC ),
new dynitem( "BOS4_PAIN", DVPTR(BOS4_PAIN), BOS4_PAIN__STATIC ),
new dynitem( "BOS4_DYING", DVPTR(BOS4_DYING), BOS4_DYING__STATIC ),
new dynitem( "NEWBEAST_ATTACKMISS", DVPTR(NEWBEAST_ATTACKMISS), NEWBEAST_ATTACKMISS__STATIC ),
new dynitem( "VOL4_2", DVPTR(VOL4_2), VOL4_2__STATIC ),
new dynitem( "COOKINGDEEPFRIER", DVPTR(COOKINGDEEPFRIER), COOKINGDEEPFRIER__STATIC ),
new dynitem( "WHINING_DOG", DVPTR(WHINING_DOG), WHINING_DOG__STATIC ),
new dynitem( "DEAD_DOG", DVPTR(DEAD_DOG), DEAD_DOG__STATIC ),
new dynitem( "LIGHTNING_SLAP", DVPTR(LIGHTNING_SLAP), LIGHTNING_SLAP__STATIC ),
new dynitem( "THUNDER", DVPTR(THUNDER), THUNDER__STATIC ),
new dynitem( "HAPPYMOUSESND1", DVPTR(HAPPYMOUSESND1), HAPPYMOUSESND1__STATIC ),
new dynitem( "HAPPYMOUSESND2", DVPTR(HAPPYMOUSESND2), HAPPYMOUSESND2__STATIC ),
new dynitem( "HAPPYMOUSESND3", DVPTR(HAPPYMOUSESND3), HAPPYMOUSESND3__STATIC ),
new dynitem( "HAPPYMOUSESND4", DVPTR(HAPPYMOUSESND4), HAPPYMOUSESND4__STATIC ),
new dynitem( "ALARM", DVPTR(ALARM), ALARM__STATIC ),
new dynitem( "RAIN", DVPTR(RAIN), RAIN__STATIC ),
new dynitem( "DTAG_GREENRUN", DVPTR(DTAG_GREENRUN), DTAG_GREENRUN__STATIC ),
new dynitem( "DTAG_BROWNRUN", DVPTR(DTAG_BROWNRUN), DTAG_BROWNRUN__STATIC ),
new dynitem( "DTAG_GREENSCORE", DVPTR(DTAG_GREENSCORE), DTAG_GREENSCORE__STATIC ),
new dynitem( "DTAG_BROWNSCORE", DVPTR(DTAG_BROWNSCORE), DTAG_BROWNSCORE__STATIC ),
new dynitem( "INTRO4_1", DVPTR(INTRO4_1), INTRO4_1__STATIC ),
new dynitem( "INTRO4_2", DVPTR(INTRO4_2), INTRO4_2__STATIC ),
new dynitem( "INTRO4_3", DVPTR(INTRO4_3), INTRO4_3__STATIC ),
new dynitem( "INTRO4_4", DVPTR(INTRO4_4), INTRO4_4__STATIC ),
new dynitem( "INTRO4_5", DVPTR(INTRO4_5), INTRO4_5__STATIC ),
new dynitem( "INTRO4_6", DVPTR(INTRO4_6), INTRO4_6__STATIC ),
new dynitem( "SCREECH", DVPTR(SCREECH), SCREECH__STATIC ),
new dynitem( "BOSS4_DEADSPEECH", DVPTR(BOSS4_DEADSPEECH), BOSS4_DEADSPEECH__STATIC ),
new dynitem( "BOSS4_FIRSTSEE", DVPTR(BOSS4_FIRSTSEE), BOSS4_FIRSTSEE__STATIC ),
new dynitem( "PARTY_SPEECH", DVPTR(PARTY_SPEECH), PARTY_SPEECH__STATIC ),
new dynitem( "POSTAL_SPEECH", DVPTR(POSTAL_SPEECH), POSTAL_SPEECH__STATIC ),
new dynitem( "TGSPEECH", DVPTR(TGSPEECH), TGSPEECH__STATIC ),
new dynitem( "DOGROOMSPEECH", DVPTR(DOGROOMSPEECH), DOGROOMSPEECH__STATIC ),
new dynitem( "SMACKED", DVPTR(SMACKED), SMACKED__STATIC ),
new dynitem( "MDEVSPEECH", DVPTR(MDEVSPEECH), MDEVSPEECH__STATIC ),
new dynitem( "AREA51SPEECH", DVPTR(AREA51SPEECH), AREA51SPEECH__STATIC ),
new dynitem( "JEEPSOUND", DVPTR(JEEPSOUND), JEEPSOUND__STATIC ),
new dynitem( "BIGDOORSLAM", DVPTR(BIGDOORSLAM), BIGDOORSLAM__STATIC ),
new dynitem( "BOS4_LAY", DVPTR(BOS4_LAY), BOS4_LAY__STATIC ),
new dynitem( "WAVESOUND", DVPTR(WAVESOUND), WAVESOUND__STATIC ),
new dynitem( "ILLBEBACK", DVPTR(ILLBEBACK), ILLBEBACK__STATIC ),
new dynitem( "VOL4ENDSND1", DVPTR(VOL4ENDSND1), VOL4ENDSND1__STATIC ),
new dynitem( "VOL4ENDSND2", DVPTR(VOL4ENDSND2), VOL4ENDSND2__STATIC ),
new dynitem( "EXPANDERHIT", DVPTR(EXPANDERHIT), EXPANDERHIT__STATIC ),
new dynitem( "SNAKESPEECH", DVPTR(SNAKESPEECH), SNAKESPEECH__STATIC ),
new dynitem( "EXPANDERSHOOT", DVPTR(EXPANDERSHOOT), EXPANDERSHOOT__STATIC ),
new dynitem( "GETBACKTOWORK", DVPTR(GETBACKTOWORK), GETBACKTOWORK__STATIC ),
new dynitem( "JIBBED_ACTOR14", DVPTR(JIBBED_ACTOR14), JIBBED_ACTOR14__STATIC ),
new dynitem( "JIBBED_ACTOR15", DVPTR(JIBBED_ACTOR15), JIBBED_ACTOR15__STATIC ),
new dynitem( "INTRO4_B", DVPTR(INTRO4_B), INTRO4_B__STATIC ),
new dynitem( "BIGBANG", DVPTR(BIGBANG), BIGBANG__STATIC ),
new dynitem( "HORNSND", DVPTR(HORNSND), HORNSND__STATIC ),
new dynitem( "BELLSND", DVPTR(BELLSND), BELLSND__STATIC ),
new dynitem( "GOAWAY", DVPTR(GOAWAY), GOAWAY__STATIC ),
new dynitem( "JOKE", DVPTR(JOKE), JOKE__STATIC ),
new dynitem( null, NULL, -1 ),
];

//#ifdef DYNSOUNDREMAP_ENABLE

var KICK_HIT = KICK_HIT__STATIC;
var PISTOL_RICOCHET = PISTOL_RICOCHET__STATIC;
var PISTOL_BODYHIT = PISTOL_BODYHIT__STATIC;
var PISTOL_FIRE = PISTOL_FIRE__STATIC;
var EJECT_CLIP = EJECT_CLIP__STATIC;
var INSERT_CLIP = INSERT_CLIP__STATIC;
var CHAINGUN_FIRE = CHAINGUN_FIRE__STATIC;
var RPG_SHOOT = RPG_SHOOT__STATIC;
var POOLBALLHIT = POOLBALLHIT__STATIC;
var RPG_EXPLODE = RPG_EXPLODE__STATIC;
var CAT_FIRE = CAT_FIRE__STATIC;
var SHRINKER_FIRE = SHRINKER_FIRE__STATIC;
var ACTOR_SHRINKING = ACTOR_SHRINKING__STATIC;
var PIPEBOMB_BOUNCE = PIPEBOMB_BOUNCE__STATIC;
var PIPEBOMB_EXPLODE = PIPEBOMB_EXPLODE__STATIC;
var LASERTRIP_ONWALL = LASERTRIP_ONWALL__STATIC;
var LASERTRIP_ARMING = LASERTRIP_ARMING__STATIC;
var LASERTRIP_EXPLODE = LASERTRIP_EXPLODE__STATIC;
var VENT_BUST = VENT_BUST__STATIC;
var GLASS_BREAKING = GLASS_BREAKING__STATIC;
var GLASS_HEAVYBREAK = GLASS_HEAVYBREAK__STATIC;
var SHORT_CIRCUIT = SHORT_CIRCUIT__STATIC;
var ITEM_SPLASH = ITEM_SPLASH__STATIC;
var DUKE_BREATHING = DUKE_BREATHING__STATIC;
var DUKE_EXHALING = DUKE_EXHALING__STATIC;
var DUKE_GASP = DUKE_GASP__STATIC;
var SLIM_RECOG = SLIM_RECOG__STATIC;
//// int32_t ENDSEQVOL3SND1 = ENDSEQVOL3SND1__STATIC;
var DUKE_URINATE = DUKE_URINATE__STATIC;
var ENDSEQVOL3SND2 = ENDSEQVOL3SND2__STATIC;
var ENDSEQVOL3SND3 = ENDSEQVOL3SND3__STATIC;
var DUKE_PASSWIND = DUKE_PASSWIND__STATIC;
var DUKE_CRACK = DUKE_CRACK__STATIC;
var SLIM_ATTACK = SLIM_ATTACK__STATIC;
var SOMETHINGHITFORCE = SOMETHINGHITFORCE__STATIC;
var DUKE_DRINKING = DUKE_DRINKING__STATIC;
var DUKE_KILLED1 = DUKE_KILLED1__STATIC;
var DUKE_GRUNT = DUKE_GRUNT__STATIC;
var DUKE_HARTBEAT = DUKE_HARTBEAT__STATIC;
var DUKE_ONWATER = DUKE_ONWATER__STATIC;
var DUKE_DEAD = DUKE_DEAD__STATIC;
var DUKE_LAND = DUKE_LAND__STATIC;
var DUKE_WALKINDUCTS = DUKE_WALKINDUCTS__STATIC;
var DUKE_GLAD = DUKE_GLAD__STATIC;
var DUKE_YES = DUKE_YES__STATIC;
var DUKE_HEHE = DUKE_HEHE__STATIC;
var DUKE_SHUCKS = DUKE_SHUCKS__STATIC;
var DUKE_UNDERWATER = DUKE_UNDERWATER__STATIC;
var DUKE_JETPACK_ON = DUKE_JETPACK_ON__STATIC;
var DUKE_JETPACK_IDLE = DUKE_JETPACK_IDLE__STATIC;
var DUKE_JETPACK_OFF = DUKE_JETPACK_OFF__STATIC;
var LIZTROOP_GROWL = LIZTROOP_GROWL__STATIC;
var LIZTROOP_TALK1 = LIZTROOP_TALK1__STATIC;
var LIZTROOP_TALK2 = LIZTROOP_TALK2__STATIC;
var LIZTROOP_TALK3 = LIZTROOP_TALK3__STATIC;
var DUKETALKTOBOSS = DUKETALKTOBOSS__STATIC;
var LIZCAPT_GROWL = LIZCAPT_GROWL__STATIC;
var LIZCAPT_TALK1 = LIZCAPT_TALK1__STATIC;
var LIZCAPT_TALK2 = LIZCAPT_TALK2__STATIC;
var LIZCAPT_TALK3 = LIZCAPT_TALK3__STATIC;
var LIZARD_BEG = LIZARD_BEG__STATIC;
var LIZARD_PAIN = LIZARD_PAIN__STATIC;
var LIZARD_DEATH = LIZARD_DEATH__STATIC;
var LIZARD_SPIT = LIZARD_SPIT__STATIC;
var DRONE1_HISSRATTLE = DRONE1_HISSRATTLE__STATIC;
var DRONE1_HISSSCREECH = DRONE1_HISSSCREECH__STATIC;
var DUKE_TIP2 = DUKE_TIP2__STATIC;
var FLESH_BURNING = FLESH_BURNING__STATIC;
var SQUISHED = SQUISHED__STATIC;
var TELEPORTER = TELEPORTER__STATIC;
var ELEVATOR_ON = ELEVATOR_ON__STATIC;
var DUKE_KILLED3 = DUKE_KILLED3__STATIC;
var ELEVATOR_OFF = ELEVATOR_OFF__STATIC;
var DOOR_OPERATE1 = DOOR_OPERATE1__STATIC;
var SUBWAY = SUBWAY__STATIC;
var SWITCH_ON = SWITCH_ON__STATIC;
var FAN = FAN__STATIC;
var DUKE_GETWEAPON3 = DUKE_GETWEAPON3__STATIC;
var FLUSH_TOILET = FLUSH_TOILET__STATIC;
var HOVER_CRAFT = HOVER_CRAFT__STATIC;
var EARTHQUAKE = EARTHQUAKE__STATIC;
var INTRUDER_ALERT = INTRUDER_ALERT__STATIC;
var END_OF_LEVEL_WARN = END_OF_LEVEL_WARN__STATIC;
var ENGINE_OPERATING = ENGINE_OPERATING__STATIC;
var REACTOR_ON = REACTOR_ON__STATIC;
var COMPUTER_AMBIENCE = COMPUTER_AMBIENCE__STATIC;
var GEARS_GRINDING = GEARS_GRINDING__STATIC;
var BUBBLE_AMBIENCE = BUBBLE_AMBIENCE__STATIC;
var MACHINE_AMBIENCE = MACHINE_AMBIENCE__STATIC;
var SEWER_AMBIENCE = SEWER_AMBIENCE__STATIC;
var WIND_AMBIENCE = WIND_AMBIENCE__STATIC;
var SOMETHING_DRIPPING = SOMETHING_DRIPPING__STATIC;
var STEAM_HISSING = STEAM_HISSING__STATIC;
var THEATER_BREATH = THEATER_BREATH__STATIC;
var BAR_MUSIC = BAR_MUSIC__STATIC;
var BOS1_ROAM = BOS1_ROAM__STATIC;
var BOS1_RECOG = BOS1_RECOG__STATIC;
var BOS1_ATTACK1 = BOS1_ATTACK1__STATIC;
var BOS1_PAIN = BOS1_PAIN__STATIC;
var BOS1_DYING = BOS1_DYING__STATIC;
var BOS2_ROAM = BOS2_ROAM__STATIC;
var BOS2_RECOG = BOS2_RECOG__STATIC;
var BOS2_ATTACK = BOS2_ATTACK__STATIC;
var BOS2_PAIN = BOS2_PAIN__STATIC;
var BOS2_DYING = BOS2_DYING__STATIC;
var GETATOMICHEALTH = GETATOMICHEALTH__STATIC;
var DUKE_GETWEAPON2 = DUKE_GETWEAPON2__STATIC;
var BOS3_DYING = BOS3_DYING__STATIC;
var SHOTGUN_FIRE = SHOTGUN_FIRE__STATIC;
var PRED_ROAM = PRED_ROAM__STATIC;
var PRED_RECOG = PRED_RECOG__STATIC;
var PRED_ATTACK = PRED_ATTACK__STATIC;
var PRED_PAIN = PRED_PAIN__STATIC;
var PRED_DYING = PRED_DYING__STATIC;
var CAPT_ROAM = CAPT_ROAM__STATIC;
var CAPT_ATTACK = CAPT_ATTACK__STATIC;
var CAPT_RECOG = CAPT_RECOG__STATIC;
var CAPT_PAIN = CAPT_PAIN__STATIC;
var CAPT_DYING = CAPT_DYING__STATIC;
var PIG_ROAM = PIG_ROAM__STATIC;
var PIG_RECOG = PIG_RECOG__STATIC;
var PIG_ATTACK = PIG_ATTACK__STATIC;
var PIG_PAIN = PIG_PAIN__STATIC;
var PIG_DYING = PIG_DYING__STATIC;
var RECO_ROAM = RECO_ROAM__STATIC;
var RECO_RECOG = RECO_RECOG__STATIC;
var RECO_ATTACK = RECO_ATTACK__STATIC;
var RECO_PAIN = RECO_PAIN__STATIC;
var RECO_DYING = RECO_DYING__STATIC;
var DRON_ROAM = DRON_ROAM__STATIC;
var DRON_RECOG = DRON_RECOG__STATIC;
var DRON_ATTACK1 = DRON_ATTACK1__STATIC;
var DRON_PAIN = DRON_PAIN__STATIC;
var DRON_DYING = DRON_DYING__STATIC;
var COMM_ROAM = COMM_ROAM__STATIC;
var COMM_RECOG = COMM_RECOG__STATIC;
var COMM_ATTACK = COMM_ATTACK__STATIC;
var COMM_PAIN = COMM_PAIN__STATIC;
var COMM_DYING = COMM_DYING__STATIC;
var OCTA_ROAM = OCTA_ROAM__STATIC;
var OCTA_RECOG = OCTA_RECOG__STATIC;
var OCTA_ATTACK1 = OCTA_ATTACK1__STATIC;
var OCTA_PAIN = OCTA_PAIN__STATIC;
var OCTA_DYING = OCTA_DYING__STATIC;
var TURR_ROAM = TURR_ROAM__STATIC;
var TURR_RECOG = TURR_RECOG__STATIC;
var TURR_ATTACK = TURR_ATTACK__STATIC;
var DUMPSTER_MOVE = DUMPSTER_MOVE__STATIC;
var SLIM_DYING = SLIM_DYING__STATIC;
var BOS3_ROAM = BOS3_ROAM__STATIC;
var BOS3_RECOG = BOS3_RECOG__STATIC;
var BOS3_ATTACK1 = BOS3_ATTACK1__STATIC;
var BOS3_PAIN = BOS3_PAIN__STATIC;
var BOS1_ATTACK2 = BOS1_ATTACK2__STATIC;
var COMM_SPIN = COMM_SPIN__STATIC;
var BOS1_WALK = BOS1_WALK__STATIC;
var DRON_ATTACK2 = DRON_ATTACK2__STATIC;
var THUD = THUD__STATIC;
var OCTA_ATTACK2 = OCTA_ATTACK2__STATIC;
var WIERDSHOT_FLY = WIERDSHOT_FLY__STATIC;
var TURR_PAIN = TURR_PAIN__STATIC;
var TURR_DYING = TURR_DYING__STATIC;
var SLIM_ROAM = SLIM_ROAM__STATIC;
var LADY_SCREAM = LADY_SCREAM__STATIC;
var DOOR_OPERATE2 = DOOR_OPERATE2__STATIC;
var DOOR_OPERATE3 = DOOR_OPERATE3__STATIC;
var DOOR_OPERATE4 = DOOR_OPERATE4__STATIC;
var BORNTOBEWILDSND = BORNTOBEWILDSND__STATIC;
var SHOTGUN_COCK = SHOTGUN_COCK__STATIC;
var GENERIC_AMBIENCE1 = GENERIC_AMBIENCE1__STATIC;
var GENERIC_AMBIENCE2 = GENERIC_AMBIENCE2__STATIC;
var GENERIC_AMBIENCE3 = GENERIC_AMBIENCE3__STATIC;
var GENERIC_AMBIENCE4 = GENERIC_AMBIENCE4__STATIC;
var GENERIC_AMBIENCE5 = GENERIC_AMBIENCE5__STATIC;
var GENERIC_AMBIENCE6 = GENERIC_AMBIENCE6__STATIC;
var BOS3_ATTACK2 = BOS3_ATTACK2__STATIC;
var GENERIC_AMBIENCE17 = GENERIC_AMBIENCE17__STATIC;
var GENERIC_AMBIENCE18 = GENERIC_AMBIENCE18__STATIC;
var GENERIC_AMBIENCE19 = GENERIC_AMBIENCE19__STATIC;
var GENERIC_AMBIENCE20 = GENERIC_AMBIENCE20__STATIC;
var GENERIC_AMBIENCE21 = GENERIC_AMBIENCE21__STATIC;
var GENERIC_AMBIENCE22 = GENERIC_AMBIENCE22__STATIC;
var SECRETLEVELSND = SECRETLEVELSND__STATIC;
var GENERIC_AMBIENCE8 = GENERIC_AMBIENCE8__STATIC;
var GENERIC_AMBIENCE9 = GENERIC_AMBIENCE9__STATIC;
var GENERIC_AMBIENCE10 = GENERIC_AMBIENCE10__STATIC;
var GENERIC_AMBIENCE11 = GENERIC_AMBIENCE11__STATIC;
var GENERIC_AMBIENCE12 = GENERIC_AMBIENCE12__STATIC;
var GENERIC_AMBIENCE13 = GENERIC_AMBIENCE13__STATIC;
var GENERIC_AMBIENCE14 = GENERIC_AMBIENCE14__STATIC;
var GENERIC_AMBIENCE15 = GENERIC_AMBIENCE15__STATIC;
var GENERIC_AMBIENCE16 = GENERIC_AMBIENCE16__STATIC;
var FIRE_CRACKLE = FIRE_CRACKLE__STATIC;
var BONUS_SPEECH1 = BONUS_SPEECH1__STATIC;
var BONUS_SPEECH2 = BONUS_SPEECH2__STATIC;
var BONUS_SPEECH3 = BONUS_SPEECH3__STATIC;
var PIG_CAPTURE_DUKE = PIG_CAPTURE_DUKE__STATIC;
var BONUS_SPEECH4 = BONUS_SPEECH4__STATIC;
var DUKE_LAND_HURT = DUKE_LAND_HURT__STATIC;
var DUKE_HIT_STRIPPER1 = DUKE_HIT_STRIPPER1__STATIC;
var DUKE_TIP1 = DUKE_TIP1__STATIC;
var DUKE_KILLED2 = DUKE_KILLED2__STATIC;
var PRED_ROAM2 = PRED_ROAM2__STATIC;
var PIG_ROAM2 = PIG_ROAM2__STATIC;
var DUKE_GETWEAPON1 = DUKE_GETWEAPON1__STATIC;
var DUKE_SEARCH2 = DUKE_SEARCH2__STATIC;
var DUKE_CRACK2 = DUKE_CRACK2__STATIC;
var DUKE_SEARCH = DUKE_SEARCH__STATIC;
var DUKE_GET = DUKE_GET__STATIC;
var DUKE_LONGTERM_PAIN = DUKE_LONGTERM_PAIN__STATIC;
var MONITOR_ACTIVE = MONITOR_ACTIVE__STATIC;
var NITEVISION_ONOFF = NITEVISION_ONOFF__STATIC;
var DUKE_HIT_STRIPPER2 = DUKE_HIT_STRIPPER2__STATIC;
var DUKE_CRACK_FIRST = DUKE_CRACK_FIRST__STATIC;
var DUKE_USEMEDKIT = DUKE_USEMEDKIT__STATIC;
var DUKE_TAKEPILLS = DUKE_TAKEPILLS__STATIC;
var DUKE_PISSRELIEF = DUKE_PISSRELIEF__STATIC;
var SELECT_WEAPON = SELECT_WEAPON__STATIC;
var WATER_GURGLE = WATER_GURGLE__STATIC;
var DUKE_GETWEAPON4 = DUKE_GETWEAPON4__STATIC;
var JIBBED_ACTOR1 = JIBBED_ACTOR1__STATIC;
var JIBBED_ACTOR2 = JIBBED_ACTOR2__STATIC;
var JIBBED_ACTOR3 = JIBBED_ACTOR3__STATIC;
var JIBBED_ACTOR4 = JIBBED_ACTOR4__STATIC;
var JIBBED_ACTOR5 = JIBBED_ACTOR5__STATIC;
var JIBBED_ACTOR6 = JIBBED_ACTOR6__STATIC;
var JIBBED_ACTOR7 = JIBBED_ACTOR7__STATIC;
var DUKE_GOTHEALTHATLOW = DUKE_GOTHEALTHATLOW__STATIC;
var BOSSTALKTODUKE = BOSSTALKTODUKE__STATIC;
var WAR_AMBIENCE1 = WAR_AMBIENCE1__STATIC;
var WAR_AMBIENCE2 = WAR_AMBIENCE2__STATIC;
var WAR_AMBIENCE3 = WAR_AMBIENCE3__STATIC;
var WAR_AMBIENCE4 = WAR_AMBIENCE4__STATIC;
var WAR_AMBIENCE5 = WAR_AMBIENCE5__STATIC;
var WAR_AMBIENCE6 = WAR_AMBIENCE6__STATIC;
var WAR_AMBIENCE7 = WAR_AMBIENCE7__STATIC;
var WAR_AMBIENCE8 = WAR_AMBIENCE8__STATIC;
var WAR_AMBIENCE9 = WAR_AMBIENCE9__STATIC;
var WAR_AMBIENCE10 = WAR_AMBIENCE10__STATIC;
var ALIEN_TALK1 = ALIEN_TALK1__STATIC;
var ALIEN_TALK2 = ALIEN_TALK2__STATIC;
var EXITMENUSOUND = EXITMENUSOUND__STATIC;
var FLY_BY = FLY_BY__STATIC;
var DUKE_SCREAM = DUKE_SCREAM__STATIC;
var SHRINKER_HIT = SHRINKER_HIT__STATIC;
var RATTY = RATTY__STATIC;
var INTO_MENU = INTO_MENU__STATIC;
var BONUSMUSIC = BONUSMUSIC__STATIC;
var DUKE_BOOBY = DUKE_BOOBY__STATIC;
var DUKE_TALKTOBOSSFALL = DUKE_TALKTOBOSSFALL__STATIC;
var DUKE_LOOKINTOMIRROR = DUKE_LOOKINTOMIRROR__STATIC;
var PIG_ROAM3 = PIG_ROAM3__STATIC;
var KILLME = KILLME__STATIC;
var DRON_JETSND = DRON_JETSND__STATIC;
var SPACE_DOOR1 = SPACE_DOOR1__STATIC;
var SPACE_DOOR2 = SPACE_DOOR2__STATIC;
var SPACE_DOOR3 = SPACE_DOOR3__STATIC;
var SPACE_DOOR4 = SPACE_DOOR4__STATIC;
var SPACE_DOOR5 = SPACE_DOOR5__STATIC;
var ALIEN_ELEVATOR1 = ALIEN_ELEVATOR1__STATIC;
var VAULT_DOOR = VAULT_DOOR__STATIC;
var JIBBED_ACTOR13 = JIBBED_ACTOR13__STATIC;
var DUKE_GETWEAPON6 = DUKE_GETWEAPON6__STATIC;
var JIBBED_ACTOR8 = JIBBED_ACTOR8__STATIC;
var JIBBED_ACTOR9 = JIBBED_ACTOR9__STATIC;
var JIBBED_ACTOR10 = JIBBED_ACTOR10__STATIC;
var JIBBED_ACTOR11 = JIBBED_ACTOR11__STATIC;
var JIBBED_ACTOR12 = JIBBED_ACTOR12__STATIC;
var DUKE_KILLED4 = DUKE_KILLED4__STATIC;
var DUKE_KILLED5 = DUKE_KILLED5__STATIC;
var ALIEN_SWITCH1 = ALIEN_SWITCH1__STATIC;
var DUKE_STEPONFECES = DUKE_STEPONFECES__STATIC;
var DUKE_LONGTERM_PAIN2 = DUKE_LONGTERM_PAIN2__STATIC;
var DUKE_LONGTERM_PAIN3 = DUKE_LONGTERM_PAIN3__STATIC;
var DUKE_LONGTERM_PAIN4 = DUKE_LONGTERM_PAIN4__STATIC;
var COMPANB2 = COMPANB2__STATIC;
var KTIT = KTIT__STATIC;
var HELICOP_IDLE = HELICOP_IDLE__STATIC;
var STEPNIT = STEPNIT__STATIC;
var SPACE_AMBIENCE1 = SPACE_AMBIENCE1__STATIC;
var SPACE_AMBIENCE2 = SPACE_AMBIENCE2__STATIC;
var SLIM_HATCH = SLIM_HATCH__STATIC;
var RIPHEADNECK = RIPHEADNECK__STATIC;
var FOUNDJONES = FOUNDJONES__STATIC;
var ALIEN_DOOR1 = ALIEN_DOOR1__STATIC;
var ALIEN_DOOR2 = ALIEN_DOOR2__STATIC;
var ENDSEQVOL3SND4 = ENDSEQVOL3SND4__STATIC;
var ENDSEQVOL3SND5 = ENDSEQVOL3SND5__STATIC;
var ENDSEQVOL3SND6 = ENDSEQVOL3SND6__STATIC;
var ENDSEQVOL3SND7 = ENDSEQVOL3SND7__STATIC;
var ENDSEQVOL3SND8 = ENDSEQVOL3SND8__STATIC;
var ENDSEQVOL3SND9 = ENDSEQVOL3SND9__STATIC;
var WHIPYOURASS = WHIPYOURASS__STATIC;
var ENDSEQVOL2SND1 = ENDSEQVOL2SND1__STATIC;
var ENDSEQVOL2SND2 = ENDSEQVOL2SND2__STATIC;
var ENDSEQVOL2SND3 = ENDSEQVOL2SND3__STATIC;
var ENDSEQVOL2SND4 = ENDSEQVOL2SND4__STATIC;
var ENDSEQVOL2SND5 = ENDSEQVOL2SND5__STATIC;
var ENDSEQVOL2SND6 = ENDSEQVOL2SND6__STATIC;
var ENDSEQVOL2SND7 = ENDSEQVOL2SND7__STATIC;
var GENERIC_AMBIENCE23 = GENERIC_AMBIENCE23__STATIC;
var SOMETHINGFROZE = SOMETHINGFROZE__STATIC;
var DUKE_LONGTERM_PAIN5 = DUKE_LONGTERM_PAIN5__STATIC;
var DUKE_LONGTERM_PAIN6 = DUKE_LONGTERM_PAIN6__STATIC;
var DUKE_LONGTERM_PAIN7 = DUKE_LONGTERM_PAIN7__STATIC;
var DUKE_LONGTERM_PAIN8 = DUKE_LONGTERM_PAIN8__STATIC;
var WIND_REPEAT = WIND_REPEAT__STATIC;
var MYENEMY_ROAM = MYENEMY_ROAM__STATIC;
var MYENEMY_HURT = MYENEMY_HURT__STATIC;
var MYENEMY_DEAD = MYENEMY_DEAD__STATIC;
var MYENEMY_SHOOT = MYENEMY_SHOOT__STATIC;
var STORE_MUSIC = STORE_MUSIC__STATIC;
var STORE_MUSIC_BROKE = STORE_MUSIC_BROKE__STATIC;
var ACTOR_GROWING = ACTOR_GROWING__STATIC;
var NEWBEAST_ROAM = NEWBEAST_ROAM__STATIC;
var NEWBEAST_RECOG = NEWBEAST_RECOG__STATIC;
var NEWBEAST_ATTACK = NEWBEAST_ATTACK__STATIC;
var NEWBEAST_PAIN = NEWBEAST_PAIN__STATIC;
var NEWBEAST_DYING = NEWBEAST_DYING__STATIC;
var NEWBEAST_SPIT = NEWBEAST_SPIT__STATIC;
var VOL4_1 = VOL4_1__STATIC;
var SUPERMARKET = SUPERMARKET__STATIC;
var MOUSEANNOY = MOUSEANNOY__STATIC;
var BOOKEM = BOOKEM__STATIC;
var SUPERMARKETCRY = SUPERMARKETCRY__STATIC;
var DESTRUCT = DESTRUCT__STATIC;
var EATFOOD = EATFOOD__STATIC;
var MAKEMYDAY = MAKEMYDAY__STATIC;
var WITNESSSTAND = WITNESSSTAND__STATIC;
var VACATIONSPEECH = VACATIONSPEECH__STATIC;
var YIPPEE1 = YIPPEE1__STATIC;
var YOHOO1 = YOHOO1__STATIC;
var YOHOO2 = YOHOO2__STATIC;
var DOLPHINSND = DOLPHINSND__STATIC;
var TOUGHGALSND1 = TOUGHGALSND1__STATIC;
var TOUGHGALSND2 = TOUGHGALSND2__STATIC;
var TOUGHGALSND3 = TOUGHGALSND3__STATIC;
var TOUGHGALSND4 = TOUGHGALSND4__STATIC;
var TANK_ROAM = TANK_ROAM__STATIC;
var BOS4_ROAM = BOS4_ROAM__STATIC;
var BOS4_RECOG = BOS4_RECOG__STATIC;
var BOS4_ATTACK = BOS4_ATTACK__STATIC;
var BOS4_PAIN = BOS4_PAIN__STATIC;
var BOS4_DYING = BOS4_DYING__STATIC;
var NEWBEAST_ATTACKMISS = NEWBEAST_ATTACKMISS__STATIC;
var VOL4_2 = VOL4_2__STATIC;
var COOKINGDEEPFRIER = COOKINGDEEPFRIER__STATIC;
var WHINING_DOG = WHINING_DOG__STATIC;
var DEAD_DOG = DEAD_DOG__STATIC;
var LIGHTNING_SLAP = LIGHTNING_SLAP__STATIC;
var THUNDER = THUNDER__STATIC;
var HAPPYMOUSESND1 = HAPPYMOUSESND1__STATIC;
var HAPPYMOUSESND2 = HAPPYMOUSESND2__STATIC;
var HAPPYMOUSESND3 = HAPPYMOUSESND3__STATIC;
var HAPPYMOUSESND4 = HAPPYMOUSESND4__STATIC;
var ALARM = ALARM__STATIC;
var RAIN = RAIN__STATIC;
var DTAG_GREENRUN = DTAG_GREENRUN__STATIC;
var DTAG_BROWNRUN = DTAG_BROWNRUN__STATIC;
var DTAG_GREENSCORE = DTAG_GREENSCORE__STATIC;
var DTAG_BROWNSCORE = DTAG_BROWNSCORE__STATIC;
var INTRO4_1 = INTRO4_1__STATIC;
var INTRO4_2 = INTRO4_2__STATIC;
var INTRO4_3 = INTRO4_3__STATIC;
var INTRO4_4 = INTRO4_4__STATIC;
var INTRO4_5 = INTRO4_5__STATIC;
var INTRO4_6 = INTRO4_6__STATIC;
var SCREECH = SCREECH__STATIC;
var BOSS4_DEADSPEECH = BOSS4_DEADSPEECH__STATIC;
var BOSS4_FIRSTSEE = BOSS4_FIRSTSEE__STATIC;
var PARTY_SPEECH = PARTY_SPEECH__STATIC;
var POSTAL_SPEECH = POSTAL_SPEECH__STATIC;
var TGSPEECH = TGSPEECH__STATIC;
var DOGROOMSPEECH = DOGROOMSPEECH__STATIC;
var SMACKED = SMACKED__STATIC;
var MDEVSPEECH = MDEVSPEECH__STATIC;
var AREA51SPEECH = AREA51SPEECH__STATIC;
var JEEPSOUND = JEEPSOUND__STATIC;
var BIGDOORSLAM = BIGDOORSLAM__STATIC;
var BOS4_LAY = BOS4_LAY__STATIC;
var WAVESOUND = WAVESOUND__STATIC;
var ILLBEBACK = ILLBEBACK__STATIC;
var VOL4ENDSND1 = VOL4ENDSND1__STATIC;
var VOL4ENDSND2 = VOL4ENDSND2__STATIC;
var EXPANDERHIT = EXPANDERHIT__STATIC;
var SNAKESPEECH = SNAKESPEECH__STATIC;
var EXPANDERSHOOT = EXPANDERSHOOT__STATIC;
var GETBACKTOWORK = GETBACKTOWORK__STATIC;
var JIBBED_ACTOR14 = JIBBED_ACTOR14__STATIC;
var JIBBED_ACTOR15 = JIBBED_ACTOR15__STATIC;
var INTRO4_B = INTRO4_B__STATIC;
var BIGBANG = BIGBANG__STATIC;
var HORNSND = HORNSND__STATIC;
var BELLSND = BELLSND__STATIC;
var GOAWAY = GOAWAY__STATIC;
var JOKE = JOKE__STATIC;

//#if !defined LUNATIC
//static hashtable_t h_names = {512, NULL};

function G_ProcessDynamicSoundMapping(szLabel: string, lValue: number): void
{
    todoThrow();
//    int32_t i;

//    if ((unsigned)lValue >= MAXSOUNDS || !szLabel)
//        return;

//    i = hash_find(&h_names,szLabel);
//    if (i>=0)
//    {
//        struct dynitem *di = &g_dynSoundList[i];
//#ifdef DEBUGGINGAIDS
//        if (di->staticval != lValue)
//            OSD_Printf("REMAP %s (%d) --> %d\n", di->str, di->staticval, lValue);
//#endif
//        *di->dynvalptr = lValue;
//    }
}

function initsoundhashnames() : void
{
    var i : number;

    hash_init(h_names);

    for (i=0; g_dynSoundList[i].staticval >= 0; i++)
        hash_add(h_names, g_dynSoundList[i].str, i, 0);
}

function freesoundhashnames(): void
{
    hash_free(h_names);
}
//#endif
//#endif

//// This is run after all CON define's have been processed to set up the
//// dynamic->static sound mapping.
//void G_InitDynamicSounds(void)
//{
//    int32_t i;

//    Bmemset(DynamicSoundMap, 0, sizeof(DynamicSoundMap));

//    for (i=0; g_dynSoundList[i].staticval >= 0; i++)
//#ifdef DYNSOUNDREMAP_ENABLE
//        DynamicSoundMap[*(g_dynSoundList[i].dynvalptr)] = g_dynSoundList[i].staticval;
//#else
//        DynamicSoundMap[g_dynSoundList[i].staticval] = g_dynSoundList[i].staticval;
//#endif

//}
